### ISSUE TITLE
[4.14][TAMA][AOSP11] Camera flashlight out of sync

### ISSUE THREAD

**Issue by MartinX3** [sonyxperiadev/bug_tracker#697] opened 2021-06-15 10:12 UTC
**Platform:** tama
**Device:** xz2
**Kernel version:** 4.14
**Android version:** 11
**Software binaries version:** v5

**Previously working on**
N/A

**Description**
I use the AOSP camera app and the flashlight is out of sync.

**Symptoms**
It flashes, then I need to wait a few seconds and then it takes the shot.
And the shot is black or very dark.
If I deactivate the flashlight, I see my picture.

**How to reproduce**
Taking a shot with the flashlight.

**Additional context**
I tried to make a log while using the flashlight, sadly the camx error loop while having the cam open makes it difficult to find the specific log timestamp.
[camera.log](https://github.com/sonyxperiadev/bug_tracker/files/6654756/camera.log)

**Comment by sraase** [comment] 2021-06-18 21:55
Are you sure this has ever worked correctly? I remember those sync issues since the very beginning.

**Comment by rinigus** [comment] 2021-06-28 05:49
It never worked in AOSP9 nor AOSP10

**Comment by MartinX3** [comment] 2021-06-28 08:15
Ups.

**Comment by rinigus** [comment] 2021-06-28 08:24
As far as I remember, @jerpelea tried to make it sync and had to eventually drop it. While it worked better in the lab, in real life sync was never good enough.

Reference to older issue: https://github.com/sonyxperiadev/bug_tracker/issues/406

**Comment by sraase** [comment] 2021-06-28 09:47
Thanks for the reference.

**Comment by sraase** [comment] 2022-02-28 10:19
About the only thing community can do is to increase the log levels and sift through the logs to figure out where things actually go wrong (at least that's what I'd need to do). This is very tedious and time-consuming work, and even then it is unlikely to yield anything substantial.

If someone can figure out what exactly is wrong and why, we have a higher chance of getting it fixed.

**Comment by faenil** [comment] 2022-02-28 10:41
@sraase thank you.

For my understanding, which component are you referring to when you say "increase the log levels"?

When you say that's the only thing community can do, is it because the problem is in the binary blobs?
Do we know at level of the stack the problem lies?

**Comment by sraase** [comment] 2022-02-28 10:59
CamX (HAL) logs, see camxoverridesettings.txt. It is part of the blobs. I suspect the camera tuning.

**Comment by faenil** [comment] 2022-02-28 11:30
I see, so we get logs by modifying camxoverridesettings.txt, then provide them to Sony and hope for the best?
(I assume camera tuning is part of the blobs too, and so out of our reach?)
Is my understanding correct?

**Comment by sraase** [comment] 2022-02-28 11:32
No. Get the logs, read the logs, understand the logs, then tell me what is wrong, how/why it is wrong and maybe I can figure out how to fix it.

**Comment by faenil** [comment] 2022-02-28 11:34
I am confused. Do you have access to blobs? :sweat_smile: 
Or are you saying it can be fixed by modifying the OSS parts?

**Closed** 2023-04-11 07:48 UTC
Labels: bug
