### ISSUE TITLE
[Ganges][kirin] Camera application crash unable to detect video qualities

### ISSUE THREAD

**Issue by AngryGami** [sonyxperiadev/bug_tracker#639] opened 2020-10-22 13:01 UTC
**Platform:** Ganges
**Device:** Kirin
**Kernel version:** 4.14
**Android version:** 10
**Software binaries version:** SW_binaries_for_Xperia_Android_10.0.7.1_r1_v11a_ganges.img

**Previously working on**
Android 9

**Description**
When activating default camera application it just closes immediately with following exception in the logs:

```
10-22 14:55:12.755  5283  5283 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.camera2/com.android.camera.CameraActivity}: java.lang.IllegalArgumentException: Could not find supported video qualities.
10-22 14:55:12.755  5283  5283 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
10-22 14:55:12.755  5283  5283 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
10-22 14:55:12.755  5283  5283 E AndroidRuntime:        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
10-22 14:55:12.755  5283  5283 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
10-22 14:55:12.755  5283  5283 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
10-22 14:55:12.755  5283  5283 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
10-22 14:55:12.755  5283  5283 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:107)
10-22 14:55:12.755  5283  5283 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:214)
10-22 14:55:12.755  5283  5283 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7356)
10-22 14:55:12.755  5283  5283 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
10-22 14:55:12.755  5283  5283 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
10-22 14:55:12.755  5283  5283 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
10-22 14:55:12.755  5283  5283 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: Could not find supported video qualities.
10-22 14:55:12.755  5283  5283 E AndroidRuntime:        at com.android.camera.settings.SettingsUtil.getNextSupportedVideoQualityIndex(SettingsUtil.java:347)
10-22 14:55:12.755  5283  5283 E AndroidRuntime:        at com.android.camera.settings.SettingsUtil.getSelectedVideoQualities(SettingsUtil.java:319)
10-22 14:55:12.755  5283  5283 E AndroidRuntime:        at com.android.camera.settings.PictureSizeLoader.computeQualitiesForCamera(PictureSizeLoader.java:154)
10-22 14:55:12.755  5283  5283 E AndroidRuntime:        at com.android.camera.settings.PictureSizeLoader.computePictureSizes(PictureSizeLoader.java:120)
10-22 14:55:12.755  5283  5283 E AndroidRuntime:        at com.android.camera.CameraActivity.onCreateTasks(CameraActivity.java:1509)
10-22 14:55:12.755  5283  5283 E AndroidRuntime:        at com.android.camera.util.QuickActivity.onCreate(QuickActivity.java:114)
10-22 14:55:12.755  5283  5283 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:7825)
10-22 14:55:12.755  5283  5283 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:7814)
10-22 14:55:12.755  5283  5283 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
10-22 14:55:12.755  5283  5283 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
10-22 14:55:12.755  5283  5283 E AndroidRuntime:        ... 11 more
```

**Additional context**
Pretty much same error as in #618 , though now on kirin.

**Comment by MarijnS95** [comment] 2020-10-22 13:03
Yeah that's a duplicate of #618. Same issue, the camera framework doesn't properly report video qualities for the tertiary camera that was recently enabled even though these should report video recording just fine.

**Comment by AngryGami** [comment] 2020-10-22 13:03
Will same "fix" work here?

**Comment by MarijnS95** [comment] 2020-10-22 13:08
There's not even a proposed fix in the pipeline, far as I understood everyone is pretty swamped with other tasks.

I don't have insight in the camera framework but this could either be a generic issue or based on a device/camera specific configuration that happens to be messed up on both of them. I'll ask around.

Workaround for now is to disable the camera in `camera_config.xml` if you absolutely must have AOSP cam or switch to a more capable app.

**Comment by AngryGami** [comment] 2020-10-22 13:14
I'll happily change to a more capable camera app :) as soon as I find any that doesn't have licensing issues (i.e. Apache or MIT or similar license, NOT GPL/GPL2) or/and not require google library installed at rom. Do you know any?

**Comment by MarijnS95** [comment] 2020-10-22 13:28
Well opencamera is GPLv3 and I can even record on the third cam with it, on both APIs :shrug: 

Guess I'll have to poke someone to prioritize this, it should be something simple.

**Comment by jerpelea** [comment] 2021-04-12 10:40
provided solution to removing the 3rd camera from config or switch to Open Camera aplication

**Closed by jerpelea** 2021-04-12 10:40 UTC
Labels: bug
