### ISSUE TITLE
[Lilac][Yoshino] Android 10 4.14 kernel stuck at logo

### ISSUE THREAD

**Issue by andrwgldmn** [sonyxperiadev/bug_tracker#508] opened 2019-12-10 20:08 UTC
**Platform:** Yoshino
**Device:** Lilac
**Kernel version:** 4.14
**Android version:** 10 r15

**Description**
Stucked at logo, logs are not available

**How to reproduce**
Build Q r15 without any editions

Should I try to switch to 4.9 kernel like in https://github.com/sonyxperiadev/bug_tracker/issues/499 ? And what I should do with SW_binaries_for_Xperia? (because any words about it in manual..) 
Thanks

**Comment by MarijnS95** [comment] 2019-12-10 20:20
> Should I try to switch to 4.9 kernel like in #499 ?

This is, in fact, a duplicate of that issue (same platform, same device, same kernel, same "bug"). As [mentioned yesterday](https://github.com/sonyxperiadev/bug_tracker/issues/507#issuecomment-563421804), 4.14 is simply not ready for use yet.

Feel free to switch to Android 9 which uses kernel 4.9 (use the latest binaries for Android 9), wait for 4.14 to stabilize or try 4.9 on Android 10 (also use the binaries for Android 9), which is "not really a supported combination". That is to say I have been using it like that during the initial bringup and two months after it, simply because 4.14 was not viable yet.
Not "officially" supporting 4.9 on Android 10 is decided upon because maintaining all these combinations is getting more and more complicated the more we get into stabilizing and finalizing 4.14, and there are by far not enough contributors to keep it all running and tested.

**Comment by andrwgldmn** [comment] 2019-12-10 20:23
Ok, thanks a lot! And what I should do with SW_binaries_for_Xperia? (because any words about it in manual..) Flash it or what?

**Comment by wyzco** [comment] 2019-12-10 20:37
Which OEM Binaries are you using? 
V2C was released today [https://developer.sony.com/file/download/software-binaries-for-aosp-android-10-0-kernel-4-14-yoshino/](https://developer.sony.com/file/download/software-binaries-for-aosp-android-10-0-kernel-4-14-yoshino/)
Try with that if you aren't already.

**Comment by andrwgldmn** [comment] 2019-12-10 20:40
@wyzco what I should do with them?? flash in some partition or smth else?

**Comment by MarijnS95** [comment] 2019-12-10 20:42
> And what I should do with SW_binaries_for_Xperia? (because any words about it in manual..) Flash it or what?

Ah - misunderstood the question - thought you weren't sure which binary distribution to take.

https://developer.sony.com/develop/open-devices/guides/aosp-build-instructions/build-aosp-android-android-10-0-0#tutorial-step-7

The build instructions definitely tell how to extract and flash it...

**Comment by andrwgldmn** [comment] 2019-12-11 19:48
So. I switched to 4.9 like in https://github.com/sonyxperiadev/bug_tracker/issues/499 but now I have reboot on logo to fastboot. No logs available. I tried SW binaries for 9.0 and for 10.0 but any result. android 10.0_r10 was used. Any ideas?

**Comment by andrwgldmn** [comment] 2019-12-11 20:59
@MarijnS95 @wyzco after booting there are some heavy interface lags for 1-3 minutes.. how to fix it if it`s possible?

**Comment by wyzco** [comment] 2019-12-11 21:19
> @MarijnS95 @wyzco after booting there are some heavy interface lags for 1-3 minutes.. how to fix it if it`s possible?
So you have gotten it to boot? 
With what commination:
OEM binary
Kernel versiin
Android version
You can start producing logcats

**Comment by andrwgldmn** [comment] 2019-12-11 21:24
@wyzco 
SW_binaries_for_Xperia_Android_9.0_2.3.2_v9_yoshino
4.9
Android 10.0_r10

**Comment by MarijnS95** [comment] 2019-12-11 23:02
@andrwgldmn Without logs there's nothing I can do/recommend.

**Comment by stefanhh0** [comment] 2019-12-12 06:29
> @MarijnS95 @wyzco after booting there are some heavy interface lags for 1-3 minutes.. how to fix it if it`s possible?

@andrwgldmn 
With K 4.9 and Android 10 I guess I am experiencing the same behavior. My workaround is to switch off the display by pressing the power button. After the display went off, press the power-button again and then the phone is reacting normally. 
If that workaround is not working for you then you probably have a different problem.
Anyway, as Marijn said, it would be good to post logcat and dmesg logs.

We should wait for K 4.14 to arrive, then re-check the behavior on the supported configuration, and open a new bug if it is then still a problem.

@MarijnS95 I have reported similar/same behavior some time ago here: https://github.com/sonyxperiadev/bug_tracker/issues/456#issuecomment-533848561

**Comment by andrwgldmn** [comment] 2019-12-12 16:57
@stefanhh0 yes, it`s the same problem. And how you boot your system up? I need to push vol+ button multiple times to boot up but not always it work`s correctly..

**Comment by wyzco** [comment] 2019-12-12 18:26
> @stefanhh0 yes, it`s the same problem. And how you boot your system up? I need to push vol+ button multiple times to boot up but not always it work`s correctly..

@stefanhh0  did you notice OEM10.0.7.1_R1_V2C was out?

**Comment by MarijnS95** [comment] 2019-12-12 19:15
Yoshino isn't the only device with display problems on startup. We're trying to sort it out in kernel 4.14.

For now powering down and up the panel is the only thing you can do, apart providing dmesg which may help us spot the problem or at least compare when we are doing 4.14.

**Comment by andrwgldmn** [comment] 2019-12-12 19:31
@MarijnS95 @wyzco can`t install any apps and there are no access to internal memory (can`t create any file, etc) https://gist.github.com/andrwgldmn/f817c9830bc8564fa1bbe509dccf4d21 
r10
K4.9

**Comment by stefanhh0** [comment] 2019-12-13 05:02
> And how you boot your system up? I need to push vol+ button multiple times to boot up but not always it work's correctly..

I don't have that problem, I am able to boot normally. What exactly happens when your phone fails to boot? Is the android logo coming for the failing boot? If so, just grab the log via `adb logcat > logcat.log` and then you should upload it here.

**Comment by andrwgldmn** [comment] 2019-12-13 05:05
@stefanhh0 I have reboot on logo with some graphic artifacts. Adb is not available on that moment..

**Comment by stefanhh0** [comment] 2019-12-13 05:20
Well, okay now you say that, I remember I had that problem in the past as well already several times. But not so recent. Most of the times it worked for me after power-cycling it once only very rarely required to power-cycle twice.

**Comment by stefanhh0** [comment] 2019-12-13 05:33
> @stefanhh0 did you notice OEM10.0.7.1_R1_V2C was out?

Yes I noticed, but I haven't yet the time to test it. I have some things to say about it:
- I have built k4.14 in the past using clang, but that one had anyway issues and I should have used gcc instead that time back
- With the integration of https://github.com/sonyxperiadev/kernel/pull/2120 clang should work now, however I'd first try building k4.14 with the gcc
- Important to be aware of, Kernel 4.14.83 was released end of november last year so maybe it has more security íssues than 4.9.194!

**Comment by stefanhh0** [comment] 2019-12-13 05:43
>@MarijnS95 @wyzco cant install any apps and there are no access to internal memory (cant create any file, etc)

I don't have such problems, how exactly do you build it? Building Android 10 with k4.9 requires several adjustments to the source tree. Maybe you haven't done all required changes to source tree? You should compare it with the latest version of the script: https://github.com/stefanhh0/aosp-10/blob/master/build-4.9.sh

**Comment by stefanhh0** [comment] 2019-12-13 05:48
@andrwgldmn which version-baseband are you using (`fastboot getvar version-baseband`)? 
It has to be: `47.1.A.16.20`

**Comment by andrwgldmn** [comment] 2019-12-13 19:34
@stefanhh0  I am using `version-baseband: 1307-7511_47.2.A.11.228` 
Also I am using your script for compiling https://github.com/stefanhh0/aosp-10/blob/master/build-4.9.sh (you should change some commit id`s (sepolicy) due to mismatches)

**Comment by andrwgldmn** [comment] 2019-12-13 19:52
@MarijnS95 @wyzco @stefanhh0 Not be able to create/delete anything from internal memory + applications can`t be installed https://gist.github.com/andrwgldmn/f817c9830bc8564fa1bbe509dccf4d21
r10
4.9
SW_binaries_for_Xperia_Android_9.0_2.3.2_v9_yoshino
version-baseband: 1307-7511_47.2.A.11.228

**Comment by stefanhh0** [comment] 2019-12-14 01:03
> @stefanhh0 I am using `version-baseband: 1307-7511_47.2.A.11.228`

Please downgrade to `47.1.A.16.20` it helps fixing problems! Use the flash tool from https://developer.sony.com/develop/open-devices/get-started/flash-tool for it and do the full flash including user data erase. After you have done so, boot into the stock rom once with inserted SIM card. Afterwards reflash your AOSP.  

`47.2.A.11.228` is not running fine together with AOSP! See as well the statements from Alin, a senior dev from sony: #361, https://github.com/sonyxperiadev/bug_tracker/issues/412#issuecomment-496327880

> Also I am using your script for compiling https://github.com/stefanhh0/aosp-10/blob/master/build-4.9.sh (you should change some commit id`s (sepolicy) due to mismatches)

Very good, can you give me the commit hashcodes which are problematic in sepolicy you are referring to?

**Comment by stefanhh0** [comment] 2019-12-14 01:09
> @MarijnS95 @wyzco @stefanhh0 Not be able to create/delete anything from internal memory + applications can`t be installed https://gist.github.com/andrwgldmn/f817c9830bc8564fa1bbe509dccf4d21
> r10
> 4.9
> SW_binaries_for_Xperia_Android_9.0_2.3.2_v9_yoshino
> version-baseband: 1307-7511_47.2.A.11.228

You mean you have trouble with the storage and not with the memory, correct? You are using an external sdcard? How are you using it? Is your sdcard extending the internal storage, that allows to install apps on it? If so, relocate the apps to the internal storage. That should fix your problem.

**Comment by samoylenko** [comment] 2019-12-14 01:23
> Very good, can you give me the commit hashcodes which are problematic in sepolicy you are referring to?

I assume that's the same ones I saw, too: https://github.com/stefanhh0/aosp-10/pull/1

**Comment by stefanhh0** [comment] 2019-12-14 01:26
> > Very good, can you give me the commit hashcodes which are problematic in sepolicy you are referring to?
> 
> I assume that's the same ones I saw, too: [stefanhh0/aosp-10#1](https://github.com/stefanhh0/aosp-10/pull/1)

Yes, just realized, thanks for you PR, just integrated!

**Comment by andrwgldmn** [comment] 2019-12-14 07:52
> Please downgrade to `47.1.A.16.20` it helps fixing problems! Use the flash tool from https://developer.sony.com/develop/open-devices/get-started/flash-tool for it and do the full flash including user data erase. After you have done so, boot into the stock rom once with inserted SIM card. Afterwards reflash your AOSP.
>
It didn`t help me.. result is the same: bootloops, graphical artefacts but not the successful booting.. can you give me boot.img and oem which you use for test, please?

**Comment by stefanhh0** [comment] 2019-12-14 08:34
You can download it from ftp://91.11.233.213/current.zip it is a full clean build from yesterday I am currently running. You'd flash all the contained img files to have a consistent state.
Please tell me when you are finished, I don't want to have it online for too long...

**Comment by andrwgldmn** [comment] 2019-12-14 08:58
@stefanhh0 yeah, I am finished

**Comment by stefanhh0** [comment] 2019-12-21 07:50
@andrwgldmn can you close this one in favor of #512. It is kind of duplicate and in the other issue it is at least already in a bootloop :-)

**Closed** 2019-12-23 01:28 UTC
Labels: bug
