### ISSUE TITLE
[Discovery] 4.14 kernel mm-camera shim errors on AOSP 10.

### ISSUE THREAD

**Issue by alaskalinuxuser** [sonyxperiadev/bug_tracker#513] opened 2020-01-02 22:40 UTC
**Platform:** Nile
**Device:** Discovery
**Kernel version:** 4.14
**Android version:** 10
**Software binaries version:** SW_binaries_for_Xperia_Android_10.0.7.1_r1_v2c_nile

**Description**
While following the SODP AOSP 10 build guide, the build completes as normal, boots up, and everything seems to work except the camera. The camera display is black and most apps cannot connect to the camera. Logs show this error:

01-02 13:15:38.529  1014  1302 I CameraService_proxy: Could not notify camera service of user switch, retrying...
01-02 13:15:38.545  1492  1492 E mm-camera: <SHIM  ><ERROR> 73: get_config_node_name: get_config_node_name: /dev/media0
01-02 13:15:38.546  1492  1492 E mm-camera: <SHIM  ><ERROR> 234: mct_shimlayer_process_module_init: open config node : 
01-02 13:15:38.546  1492  1492 E mm-camera: <SHIM  ><ERROR> 238: mct_shimlayer_process_module_init: Failed to open config node. errno 21 (Is a directory)

**Symptoms**
Camera preview is black or the apps say that it cannot connect to the camera.

**How to reproduce**
Build AOSP 10 following the SODP 10 build guide, using either the prebuilt kernel, or build it again with GCC. Flash to phone with the latest software binaries. Boot and try to open the camera.

Attached logcat messages here:
[logCameraDiscovery.txt](https://github.com/sonyxperiadev/bug_tracker/files/4017596/logCameraDiscovery.txt)

**Comment by MarijnS95** [comment] 2020-01-02 22:51
Hi @alaskalinuxuser,

Unfortunately the camera is currently only working on the "new camera framework" (CamX) on 4.14, found in the most recent devices in the Tama/Kumano platform series.

We have identified that the camera probes fine in the kernel (hence `/dev/media0` is available), so this seems to be a misconfiguration issue in the blobs (those in the SW_binaries file, that are not compiled from source and thus much harder to look at). Due to the holidays this has not yet been confirmed nor addressed, but this is an excellent opportunity to tag @sraase to take a look at the logs :grin:

**Comment by alaskalinuxuser** [comment] 2020-01-03 01:34
Thanks, yes, I figured it was in the vendor blobs, which really cuts down on any chance I had at fixing it. Of course, with the 4.9 kernel and blobs, the camera works great, but without a working camera, I could see that any advancement would cripple uses on other platforms like nile, so I wanted to get it posted. Or does this bug tracker only track for the source that is compiled?

**Comment by MartinX3** [comment] 2020-01-03 09:22
The bug tracker tracks everything, don't worry.
Sraase does the camera development in the blobs.

You can run 10.0 with 4.9 blobs of you want
https://github.com/stefanhh0/aosp-10

**Comment by MarijnS95** [comment] 2020-01-03 12:05
> but without a working camera, I could see that any advancement would cripple uses on other platforms like nile, so I wanted to get it posted.

Don't worry, we'll get 4.14 on all platforms sorted at "some" point, it is just going to take a while with only one developer fully capable of tackling the kernel and a few others working on lighter issues and userspace around it.

Unfortunately I'm not able to get to Discovery (or any other phone with the "legacy" camera2/mm-camera framework) within at least another 24 hours, but I have a strong feeling where the issue is which we should be able to fix without blob magic. More info follows tomorrow!

**Comment by alaskalinuxuser** [comment] 2020-01-03 14:49
Thanks guys. Don't worry, I don't expect an overnight fix. :D 
I'm currently using AOSP 10 with the 4.9 kernel and blobs, and it works great, thanks to you guys!

**Comment by sraase** [comment] 2020-01-07 09:43
I have to admit that my mm-camera knowledge is _extremely_ limited. I've only done bring-up on CamX, which is not supported on Nile. The mm-camera bring-up for all devices was done by @jerpelea.

**Comment by jerpelea** [comment] 2020-01-07 09:57
I am already looking at the issue

**Comment by jerpelea** [comment] 2020-01-13 09:36
fied and will be released in v3

**Closed** 2020-01-13 09:39 UTC
Labels: bug

**Comment by alaskalinuxuser** [comment] 2020-01-13 15:38
You guys are the best!
