### ISSUE TITLE
broken LTE with less than 4mbps speed with Android 10 and kernel 4.14

### ISSUE THREAD

**Issue by KingArron** [sonyxperiadev/bug_tracker#524] opened 2020-01-27 14:20 UTC
**Platform:** Tama
**Device:** XZ2 H8216
**Kernel version:** 4.14.150
**Android version:** 10
**Software binaries version:** 10.0.7.1_R1_V3A_TAMA

**Description**
With SODP or any sony AOSP based ROM alongside 10.0.7.1_R1_V3A_TAMA binary I can never get over 4mbps speed with 4G LTE whereas on stock based ROM on 4.9 kernel or GSI I can hit 100+mbps over LTE.

**How to reproduce**
Flash SODP 10 or Pixel Experience 10 ROM with latest 4.14 OEM from Sony on Sony XZ2 and LTE speed no matter what will always stay below 4mbps on EE network in the UK

**Comment by Paulbouchara** [comment] 2020-01-27 14:24
Confirmed on SFR network too in France. From 200mb/s to 4.5/5 mb/s

**Comment by MartinX3** [comment] 2020-03-01 19:24
Confirm it too
Slow speeds here.
2-3 mb down and 4-5 mb up

**Comment by Raphos** [comment] 2020-06-19 11:21
Confirmed on SFR Red network too in France.
Tested with my Z5C, 76.38 Mbps with my XZ2C, 2.25Mbps

**Comment by Gouster4** [comment] 2020-06-28 16:40
I can confirm that with Telekom SK provider on Telekomk DE network (roaming).
download is  at max 4mbps (mostly between 2 and 3), and upload is way faster, around 40mbps, sometimes more.

**Comment by MartinX3** [comment] 2020-06-28 16:48
Since OEMv8 I reach now
3.3 mbit down
12.4 mbit up
German O2 LTE

**Comment by Gouster4** [comment] 2020-06-28 17:20
> Since OEMv8 I reach now
> 3.3 mbit down
> 12.4 mbit up
> O2 Germany

yeah, seems oem v8 phixed upload

**Comment by MartinX3** [comment] 2020-06-28 17:31
> > Since OEMv8 I reach now
> > 3.3 mbit down
> > 12.4 mbit up
> > O2 Germany
> 
> yeah, seems oem v8 phixed upload

Not really. It's just a bit better.
The locked single sim XZ2 with stock and O2 Germany here reach a faster upload.

**Comment by Raphos** [comment] 2020-07-17 09:38
Tested with OEMv8, LTE speed is still very slow.
2.49Mbps with 4G on SFR Red network in France.
124Mbps with a Nighthawk R7100LG, same provider.

**Comment by MartinX3** [comment] 2020-07-17 16:07
Forced LTE only
[logcat-b_radio.log](https://github.com/sonyxperiadev/bug_tracker/files/4938806/logcat-b_radio.log)

**Comment by jerpelea** [comment] 2021-04-12 10:25
fixed on later releases

**Closed by jerpelea** 2021-04-12 10:25 UTC
Labels: bug
