### ISSUE TITLE
Cannot boot G8441

### ISSUE THREAD

**Issue by LadaBr** [sonyxperiadev/bug_tracker#453] opened 2019-08-29 00:47 UTC
**Platform:** Yoshino
**Device:** G8441
**Android version:** android-9.0.0_r46
**Kernel**: 4.9

**Description**
I followed official guide on sony website and device is stuck on bootloop.

**Symptoms**
It shows Android logo and freezes. Sony logo shows on different positions around the screen on each boot. There are also 1 or 2 green lines randomly showing around the logo. Only once it managed to boot after like 20 reboots but when I touched the power button to wake it up, screen was glitching and I had to turn it off.

**How to reproduce**
Build android-9.0.0_r46 on Ubuntu 16.04 LTS and flash device

**Comment by stefanhh0** [comment] 2019-08-29 19:23
What is the output of `fastboot getvar version-baseband`? Should be: `47.1.A.16.20`  
Which OEM binary are you using: Should be: `SW_binaries_for_Xperia_Android_9.0_2.3.2_v9_yoshino.img`
On which kernel commit are you? Should be: `4.9.189-g5d08a48d2add` (`adb shell uname -a`)

At least that is a configuration with that most things work fine for me on that device.

**Comment by LadaBr** [comment] 2019-08-29 20:04
Baseband: 1307-7511_47.2.A.10.107
I downloaded latest OEM, the one you mentioned.
Also kernel should be 4.9 (flashing boot from 9.0.0_r46)

**Comment by LadaBr** [comment] 2019-08-29 20:08
Baseband is the latest one for Pie. I thought 47.1 is Orea.

**Comment by wyzco** [comment] 2019-08-29 20:17
> What is the output of `fastboot getvar version-baseband`? Should be: `47.1.A.16.20`
> Which OEM binary are you using: Should be: `SW_binaries_for_Xperia_Android_9.0_2.3.2_v9_yoshino.img`
> On which kernel commit are you? Should be: `4.9.189-g5d08a48d2add` (`adb shell uname -a`)
> 
> At least that is a configuration with that most things work fine for me on that device.

Hey stefanhh0 could you share the images of this build so i could flash them?

What are the things not working if you dont mind saying?

**Comment by stefanhh0** [comment] 2019-08-29 20:37
47.2.A.10.107 is not stable. AOSP works stable only with 47.1.A.16.20. 
Therefore please downgrade.
See e.g. here:
https://github.com/sonyxperiadev/bug_tracker/issues/412#issuecomment-496327880
47.1.A.16.20 works fine with Pie.

Additionally you are then probably using the prebuilt kernel. You should just delete the prebuilts, so that the latest kernel gets built:
`rm -r kernel/sony/msm-4.9/common-kernel`
Then rebuilt the boot image with
make bootimage

**Comment by LadaBr** [comment] 2019-08-29 20:38
Thank you very much.

**Comment by stefanhh0** [comment] 2019-08-29 20:41
@wyzco No new issues with current builds, all the yoshino issues that are open here...
Will get back to you with the info how to download. Will create a tar.xz file for you... May take a little.

**Comment by LadaBr** [comment] 2019-08-29 21:21
Where do I get 47.1.A.16.20 ? I tried to flash some TFT i found but fastboot keeps saying it is 47.2.A.10.107

**Comment by stefanhh0** [comment] 2019-08-29 21:25
Use the flashtool from sony:
https://developer.sony.com/develop/open-devices/get-started/flash-tool/download-flash-tool/

After you have flashed, boot into the flashed stock rom with inserted SIM, that will update the version-baseband

**Comment by LadaBr** [comment] 2019-08-29 21:46
So i have 47.1.A.16.20 now and i flashed system, boot, vendor, recovery, userdata, oem and it doesn't boot.

**Comment by stefanhh0** [comment] 2019-08-29 22:01
Sure, give it a try download via anonymous ftp from 91.11.226.37

When you do a fastboot provide once -w to erase and format userdata and cache...  flash only boot, oem, system and vendor

To have a better recovery use twrp-3.3.1-0-lilac-pie-4.img from https://androidfilehost.com/?w=files&flid=286272&sort_by=date&sort_dir=DESC

**Comment by LadaBr** [comment] 2019-08-29 22:26
I tried your images and no difference. I am hopeless. My steps:
fastboot -w
flash oem
flash system
flash vendor
flash boot

**Comment by stefanhh0** [comment] 2019-08-29 22:34
That is unfortunate. You could give it a last try as outlined above...

**Comment by LadaBr** [comment] 2019-08-29 22:53
Followed your instructions and nothing changed. Sony logo appears randomly on the screen on each bootloop iteration. Sometimes it is even like this: |NY     SO|

Looks like I have to use stock ROM :(

**Comment by stefanhh0** [comment] 2019-08-29 22:57
The sony logo issue is a known issue... see #371. 

After you have flashed it takes some time to boot, only if it takes really too long like two minutes or so, then the phone is really stuck and needs another powercycle.

**Comment by LadaBr** [comment] 2019-08-29 22:59
So is it supposed to restart like 20 times? Because i saw Android logo for couple of seconds and then it reboot itself again.

**Comment by stefanhh0** [comment] 2019-08-29 23:02
Ah okay boot loop is for sure not expected... maybe you have a different hw revision of the phone that has not yet reported issues...

**Comment by stefanhh0** [comment] 2019-08-29 23:05
Just to be sure, you have verified with fastboot getvar version-baseband that it now shows 47.1.A.16.20?

**Comment by LadaBr** [comment] 2019-08-29 23:06
version-baseband: 1307-7511_47.1.A.16.20
Finished. Total time: 0.015s

**Comment by stefanhh0** [comment] 2019-08-29 23:15
Try booting the device with adb logcat | tee logcat.log maybe we get some output from the boot process. And attach the logcat.log here

Another approach would be to flash once again clean with sony flashtool, boot into it with SIM inserted and then flash all the img files again from my tar.

**Comment by stefanhh0** [comment] 2019-08-29 23:22
I have I slightly different version-baseband:
1308-8921_47.1.A.16.20
If I remember correctly it is from the G8441_Customized_US_1310-4371_47.1.A.16.20_R8B. Not so sure that the minor difference in the version number has an effect, anyway it would be good to flash that one to eliminate that difference...

**Comment by stefanhh0** [comment] 2019-08-29 23:25
Also wyzco is using the version-baseband that I am using:
https://github.com/sonyxperiadev/bug_tracker/issues/412#issuecomment-496441199

**Comment by LadaBr** [comment] 2019-08-29 23:53
logcat was not possible since adb won't even connect.

I flashed US one and behavior is exactly same like every try before.

**Comment by stefanhh0** [comment] 2019-08-30 05:02
No, 28 is not the hardware revision of your phone. It is the API version for Android Pie. I don't know how to get the exact hardware revision for the phone. 

There has been a report in the past related to sdcards and boot issues. Are you using an sdcard? If so, you could give it a try booting without any sdcard to see if that is the problem. Maybe also without SIM inserted.

Additionally after you have flashed all the images  are you then at least able to boot into recovery via `fastboot boot recover.img` (for that command you have to be in the directory where the recovery.img is).

Additionally could you upload here your `adb shell dmesg >dmesg.log` from the flashed stock rom right after boot?

**Comment by LadaBr** [comment] 2019-08-30 05:43
I get this response: dmesg: /dev/kmsg: Permission denied

I googled that I need to root the phone. adb root is not working tho. Should I do it some other way?

**Comment by djselbeck** [comment] 2019-08-30 06:02
Sounds very similar to #368

**Comment by LadaBr** [comment] 2019-08-30 06:28
Whatever I do it always end up in fastboot mode or bootloop if not connected after sony logo

**Comment by djselbeck** [comment] 2019-08-30 06:46
Have you tried a wall charger, as in connected to power but not to a computer?

**Comment by LadaBr** [comment] 2019-08-30 06:55
Yep. Right after your message.

**Comment by LadaBr** [comment] 2019-08-30 09:53
Is internal storage supposed to look like this?
![image](https://user-images.githubusercontent.com/19284819/64011836-c4a23b80-cb1c-11e9-9cf7-16c0a3d5ff93.png)

**Comment by stefanhh0** [comment] 2019-09-09 03:01
> I tried your images and no difference. I am hopeless. My steps:
> fastboot -w
> flash oem
> flash system
> flash vendor
> flash boot

Internal storage should not look like what you've posted, but when I looked again at what you have flashed you should at least flash as well userdata. The fastboot -w is not needed if you flash all images including cache and userdata.

Please try to flash completely and don't leave out a single img:
fastboot flash boot boot.img
fastboot flash cache cache.img
fastboot flash oem oem.img
fastboot flash recovery recovery.img
fastboot flash system system.img
fastboot flash userdata userdata.img
fastboot flash vendor vendor.img

**Comment by LadaBr** [comment] 2019-09-09 19:10
I tried it before already and no difference. I think that encryption is
issue and I didn't find out how to remove it. It said it was one time
change that cannot be reverted when I did it. At least it saved me when my
phone was stolen and guy didn't manage to reinstall it so police found him.

Dne po 9. 9. 2019 5:03 uživatel stefanhh0 <notifications@github.com> napsal:

**Comment by stefanhh0** [comment] 2019-09-09 21:27
Afaik encryption is resetted if one reflashes all images **in one go** including userdata. Not completely sure, but I think per default on android Pie the internal storage encryption is always applied. An external sdcard can be reformatted as well as new at any time with and without encryption after one has booted to the system. I never heard of something like that there are old encryption remnants when flashing all images... But maybe there is something I am missing.

When you e.g. start twrp recovery, it should just apply the decryption keys automatically, at least that happens with my phone, that is as well a g8441. If you have defined a device pin, which can't be the case for you, since your phone does not boot to the system, twrp would also ask for the device pin.

I haven't tried to flash on top of a stock 47.1.A.16.20 since a longer time, especially I didn't flash userdata.img for quite a while since I was not in need for that. So maybe one of the encryption  resp. adoptable storage changes that has been done in the more recent past may have caused a bug when flashing also userdata.img.

Since you can't boot aosp to the system, how did you do the screenshot you have provided, resp. what was the state of the phone when you did the screenshot?

Additionally you are again trying to get aosp running on top of 47.2.A.10.107 which is known to be a bad idea, especially since in general 47.2.A.* is known to have issues with aosp pie. Therefore please follow the instructions:
- Remove the external sdcard completely (to avoid any interference by external sdcard issues)
- Flash the stockrom: 1308-8921_47.1.A.16.20 (The full image including the erase of userdata not just firmware update!)
- Boot once into the Android 8 stockrom with simcard inserted
- Boot into fastboot mode (blue led) and verify that you are on 1308-8921_47.1.A.16.20 (fastboot getvar version-baseband)
- Flash all the images in fastboot mode (blue led) that I have provided in one go, including userdata.img and cache.img
- Disconnect usb and restart the device

Additionally:
- The very first boot takes a little longer, so just give it the time it requires
- Once in a while phone hangs a while on first boot and then reboots again. In most cases 2nd time boot is then successful
- If 2nd boot is as well not successful, powercycle the phone

I may have time to check this weekend if I can reproduce the boot loop issue you have reported when flashing all the images on top of android 8 stockrom and booting into pure aosp 9... However you should be sure you followed the instructions closely since that may already fix the problem...

**Comment by LadaBr** [comment] 2019-09-09 21:57
The screenshot provided was taken right after flash of AOSP with 47.1.A.16.20 firmware.

I carefully followed all the steps you provided and repeated them three times in case i did some mistake. Result was always same. Bootloop.

**Comment by MartinX3** [comment] 2019-09-10 10:13
If TWRP ask for the PIN and decrypt it successfully:
1. android encrypted it successfully
2. the deception works

Does it reboot to twrp after a bootloop?
Or could you try to press the TWRP boot buttons instant after you saw it crashing again?
Maybe `/sys/fs/pstore/` has some tasty logs.

btw. a permission denied error while using `adb shell dmesg` sounds weird.
Sure the rom is build as `-userdebug` and not as `-user` ?

**Comment by stefanhh0** [comment] 2019-09-21 06:59
Tried today to reproduce your problem but I failed.

I have flashed the stock rom via emma, have a look at the screenshot:
![EmmaFlash](https://user-images.githubusercontent.com/28729344/65369335-dd999a80-dc4b-11e9-8ce2-23a6e9e63dad.png)

Maybe you find any significant differences in how it looked like for you when you did it, afterwards I flashed a clean android 9r46 build from 15th:
```
stefan@mars:~/android/bin/current$ fastboot flash boot boot.img 
target reported max download size of 536870912 bytes
sending 'boot' (16581 KB)...
OKAY [  0.550s]
writing 'boot'...
OKAY [  0.003s]
finished. total time: 0.553s
stefan@mars:~/android/bin/current$ fastboot flash cache cache.img 
target reported max download size of 536870912 bytes
erasing 'cache'...
OKAY [ 15.101s]
sending 'cache' (164 KB)...
OKAY [  0.020s]
writing 'cache'...
OKAY [  0.000s]
finished. total time: 15.121s
stefan@mars:~/android/bin/current$ fastboot flash oem oem.img 
target reported max download size of 536870912 bytes
sending 'oem' (221048 KB)...
OKAY [  7.299s]
writing 'oem'...
OKAY [  0.000s]
finished. total time: 7.299s
stefan@mars:~/android/bin/current$ fastboot flash recovery recovery.img 
target reported max download size of 536870912 bytes
sending 'recovery' (34548 KB)...
OKAY [  1.169s]
writing 'recovery'...
OKAY [  0.000s]
finished. total time: 1.170s
stefan@mars:~/android/bin/current$ fastboot flash system system.img 
target reported max download size of 536870912 bytes
erasing 'system'...
OKAY [ 13.436s]
sending sparse 'system' 1/3 (524284 KB)...
OKAY [ 17.240s]
writing 'system' 1/3...
OKAY [  0.000s]
sending sparse 'system' 2/3 (524284 KB)...
OKAY [ 21.760s]
writing 'system' 2/3...
OKAY [  0.000s]
sending sparse 'system' 3/3 (132996 KB)...
OKAY [  8.490s]
writing 'system' 3/3...
OKAY [  0.000s]
finished. total time: 60.926s
stefan@mars:~/android/bin/current$ fastboot flash userdata userdata.img 
target reported max download size of 536870912 bytes
erasing 'userdata'...
OKAY [ 15.201s]
sending 'userdata' (4832 KB)...
OKAY [  0.169s]
writing 'userdata'...
OKAY [  0.000s]
finished. total time: 15.370s
stefan@mars:~/android/bin/current$ fastboot flash vendor vendor.img 
target reported max download size of 536870912 bytes
sending 'vendor' (53476 KB)...
OKAY [  1.823s]
writing 'vendor'...
OKAY [  0.000s]
finished. total time: 1.823s
stefan@mars:~/android/bin/current$ ls -la
insgesamt 28
drwxr-xr-x 1 stefan stefan 136 Sep 21 08:16 .
drwxr-xr-x 1 stefan stefan 356 Sep 21 08:17 ..
lrwxrwxrwx 1 stefan stefan  22 Sep 21 08:16 boot.img -> ../2019_09_15/boot.img
lrwxrwxrwx 1 stefan stefan  23 Sep 21 08:16 cache.img -> ../2019_09_15/cache.img
lrwxrwxrwx 1 stefan stefan  58 Sep 21 08:06 oem.img -> ../SW_binaries_for_Xperia_Android_9.0_2.3.2_v9_yoshino.img
lrwxrwxrwx 1 stefan stefan  31 Sep 21 07:20 recovery.img -> ../twrp-3.3.1-0-lilac-pie-5.img
lrwxrwxrwx 1 stefan stefan  24 Sep 21 08:16 system.img -> ../2019_09_15/system.img
lrwxrwxrwx 1 stefan stefan  26 Sep 21 08:16 userdata.img -> ../2019_09_15/userdata.img
lrwxrwxrwx 1 stefan stefan  24 Sep 21 08:16 vendor.img -> ../2019_09_15/vendor.img
```

Without any other modifications I was then able to boot into the AOSP system just fine.
Sometimes you managed to boot to the system, right? In that case your display is broken you told. If you reach that stage, copy the dmesg and logcat as follows via using adb from your host:
`adb logcat -d > logcat.log`
`adb shell dmesg >dmesg.log`

Upload those files here. Someone who is able to read the files may then have a look and figure out what is going wrong (That wouldn't be me, since I am just a user not an android dev...)

**Comment by stefanhh0** [comment] 2019-09-29 13:10
Without providing logs and since no one else could reproduce the problem, there is little that can be done I guess and thus the issue might be eligible for being closed.

**Comment by ix5** [comment] 2020-03-06 19:14
Ping @jerpelea for closing

**Closed** 2020-03-09 09:35 UTC
