### ISSUE TITLE
Bug: Problem with camera zoom-function:

### ISSUE THREAD

**Issue by XperiaDeveloper** [sonyxperiadev/bug_tracker#138] opened 2018-06-13 09:50 UTC
**Platform:** loire
**Device:** suzu
**Kernel version:** 4.4 
**Android version:** 8.1 r20 & r26

**Description**
I've build and flashed Android 8 release 26 on XperiaX device following
the build instruction in https://developer.sony.com/develop/open-devices/guides/aosp-build-instructions/build-aosp-nougat-8-1-oreo-4-4 

**Symptoms**
A strange pixel stripe appears vertically on the screen when i zoom-in
into a picture or video, it disappears when i zoom-out again. 

**How to reproduce**
- Build 8.1 and flush XperiaX: https://developer.sony.com/develop/open-devices/guides/aosp-build-instructions/build-aosp-nougat-8-1-oreo-4-4
- Start camera
- zoom in/out

![sonyxperiax_cameraproblem](https://user-images.githubusercontent.com/39955310/41409277-e9e2aa72-6fd5-11e8-9b7b-d26b184ff9ea.png)

**Comment by XperiaDeveloper** [comment] 2018-06-14 11:21
![sonyxperiax_cameraproblem](https://user-images.githubusercontent.com/39955310/41409258-d6d1244a-6fd5-11e8-9b82-15d2f7a4a309.png)

**Comment by erikcas** [comment] 2018-06-14 13:40
afaik this is present since android-7.1?

**Comment by oshmoun** [comment] 2018-06-15 20:19
this issue came to be after the switch from 3.10 to 4.4 kernel, so it might be related to the camera blobs or camera hal.
Since this doesn't affect the recorded videos and pics (they don't show the stripe), then it's probably not related to the media hal.

**Comment by erikcas** [comment] 2018-06-16 09:52
@oshmoun I have it in recorded video's here on multiple camera apps

**Comment by oshmoun** [comment] 2018-06-16 10:49
oh sorry yup. recorded videos have the stripe, only photos don't.

**Comment by XperiaDeveloper** [comment] 2018-06-22 14:32
Another observation that may relate to this issue is that, when starting the camera aimed at a very close white background (white table or wall), the screen turns green for a while until you start moving the phone around. 
This issue is a bit difficult to reproduce, so you have to try it few times.


![img_20180608_224401](https://user-images.githubusercontent.com/39955310/41782050-608b3a4a-7639-11e8-9b33-e5251a146698.jpg)

**Comment by jerpelea** [comment] 2018-06-29 14:19
the issue has been replicated and we are working on a fix 
thanks for reporting the bug

**Comment by jerpelea** [comment] 2018-07-09 15:02
the zoom bug is fixed and it will be released in vendor V14

**Comment by oshmoun** [comment] 2018-07-12 14:20
Can confirm that the zoom issue is fixed with v14

**Closed** 2018-07-18 12:01 UTC

**Comment by MarijnS95** [comment] 2018-07-18 13:31
I cannot see the artifacts anymore, but this might be due to the reduced zoom level. is that intended, or am I missing something?

**Comment by jerpelea** [comment] 2018-07-18 13:32
the zoom reduction is on purpose

**Comment by jamuir** [comment] 2018-07-19 14:32
thanks.

**Comment by jamuir** [comment] 2018-09-06 16:35
I can confirm that the issue with the camera zoom range on maple has been fixed in v15.

It is now back to 8x.
