### ISSUE TITLE
Build issue with android-13.0.0_r61

### ISSUE THREAD

**Issue by MartinX3** [sonyxperiadev/bug_tracker#801] opened 2023-07-20 09:33 UTC
**Platform:** TAMA
**Device:** AKARI
**Kernel version:** 4.19
**Android version:** 13
**Software binaries version:** 12 4.19 V3A

**Previously working on**
android-13.0.0_r51

**Description**
Build issue.

**Symptoms**
Can't build.

**How to reproduce**
Build the device.

**Additional context**
```
FAILED: out/soong/build.ninja
cd "$(dirname "out/host/linux-x86/bin/soong_build")" && BUILDER="$PWD/$(basename "out/host/linux-x86/bin/soong_build")" && cd / && env -i  "$BUILDER"     --top "$TOP"     --soong_out "out/soong"     --out "out">
error: device/google/tangorpro/powerstats/Android.bp:15:1: module "soong_namespace": namespace device/google/gs201/powerstats does not exist
```

**Comment by MarijnS95** [comment] 2023-07-20 13:04
This looks like a direct duplicate of https://github.com/sonyxperiadev/bug_tracker/issues/800, but this time for the `tangorpro` device. Can you just PR an `untracked_devices` addition for that?

**Closed** 2023-07-31 13:05 UTC
Labels: bug
