### ISSUE TITLE
Slow WiFi or WiFi Not working at all

### ISSUE THREAD

**Issue by Johnkarazou** [sonyxperiadev/bug_tracker#627] opened 2020-09-07 08:03 UTC
Platform: Ganges
Device: Mermaid , Xperia 10 Plus
Kernel version: 4.14
Android version: 10.0
Software binaries version: v9c (latest)

**Previously working on**
Android 9 and 10 Stock

**Description**
Hello, I will try to be as detailed as i can be and simple.
(Same device, same Router, same internet provider)
On stock Android 9 and Android 10 WiFi is working perfect (~95mb download speed, 10mb upload speed)
When I flash SODP 10 from Android 9 base, WiFi speed drops 50% (~50mb download speed, 10mb upload speed) 
When I flash SODP 10 from Android 10 base, WiFi not working (Cannot enable, WiFi not starting, no MAC address)

**Symptoms**
Slow WiFi from Android 9 to SODP 
WiFi broken from Android 10 to SODP

**How to reproduce**
 Slow WiFi speed:
 Flash & boot stock 9 first.
Then flash SODP.
Connect to WiFi and speedtest.
WiFi Not working:
 Flash & boot stock 10 first.
Then flash SODP.
WiFi not working at all.

**Additional context**
Logs when booting.
[WiFi_Boot.txt](https://github.com/sonyxperiadev/bug_tracker/files/5181794/WiFi_Boot.txt)

**Comment by Haxk20** [comment] 2020-09-14 08:54
I cannot reproduce this locally on kirin.
@MarijnS95 You have mermaid that you dont mind flashing. Can you test ?

**Comment by MarijnS95** [comment] 2020-10-02 22:35
This issue appears when upgrading to stock Android 10 `bdwlan` firmware. Perhaps our qcacld became incompatible and we have to upgrade, switch to different tags or pick some patches.

The only relevant hint appearing in dmesg:
```
7139:08-27 16:07:35.335     0     0 E icnss   : Driver probe failed: -22, state: 0x40d87, probe_cnt: 1
```

`0x40d87` = `0b1000000110110000111`, which equates to the following state:

```c
enum icnss_driver_state {
	ICNSS_WLFW_CONNECTED,
	ICNSS_POWER_ON,
	ICNSS_FW_READY,
	// ICNSS_DRIVER_PROBED,
	// ICNSS_FW_TEST_MODE,
	// ICNSS_PM_SUSPEND,
	// ICNSS_PM_SUSPEND_NOIRQ,
	ICNSS_SSR_REGISTERED,
	ICNSS_PDR_REGISTERED,
	// ICNSS_PD_RESTART,
	ICNSS_MSA0_ASSIGNED,
	ICNSS_WLFW_EXISTS,
	// ICNSS_SHUTDOWN_DONE,
	// ICNSS_HOST_TRIGGERED_PDR,
	// ICNSS_FW_DOWN,
	// ICNSS_DRIVER_UNLOADING,
	// ICNSS_REJUVENATE,
	// ICNSS_MODE_ON,
	ICNSS_BLOCK_SHUTDOWN,
	// ICNSS_PDR,
	// ICNSS_MODEM_CRASHED,
	// ICNSS_MODEM_SHUTDOWN,
};
```

**Comment by derWahnsinn** [comment] 2020-10-20 13:09
I'm experiencing the same issue as @Johnkarazou and @MarijnS95 described.

dmesg shows the same result:

`[   22.055438] icnss: Driver probe failed: -22, state: 0x40d87, probe_cnt: 1`

Is there any update regarding the issue?

thanks in advance

**Comment by MarijnS95** [comment] 2020-10-20 21:30
@derWahnsinn It appears no-one had time to look into this further, at least I have more high-prio things to do.

You can downgrade to Android 9 firmware again, but since only WiFi is problematic you might also pull the `bdwlan` firmware images from Android 9 and overwrite them on your device.

On a running device these can be found in `/vendor/firmware_mnt/image/bdwlan*`. Be sure to remount the partition writable before pushing the files: `mount -woremount /vendor/firmware_mnt`.

**Comment by jerpelea** [comment] 2021-04-12 10:37
fixed with the latest release 
please sync and rebuild

**Closed by jerpelea** 2021-04-12 10:37 UTC
Labels: bug
