### ISSUE TITLE
[Lilac]Can't make a call. android 9. oem v2

### ISSUE THREAD

**Issue by russel5** [sonyxperiadev/bug_tracker#222] opened 2018-10-22 18:08 UTC
**Platform:** Yoshino
**Device:** Lilac
**Kernel version:** 4.9
**Android version:** 9

**Description**
Can't make a call

**Symptoms**
When enter number and press call button, phone immediately drop call.
Try on LTE, 3G and 2G

**How to reproduce**
Use android 9 on lilac and try to make a call.

**Comment by ix5** [comment] 2018-10-23 18:20
I suspect it's due to some gapps thing. Tested without any gapps and calls work, but there's no sound.
Could be related to the fact that when toggling the mute button in-call, this error appears:
```
W DeviceHAL: Error from HAL Device in function set_mic_mute: Function not implemented
```

**Comment by russel5** [comment] 2018-10-24 01:00
I do not install any gapps

**Comment by ix5** [comment] 2018-10-25 14:47
@jerpelea Can you reproduce? Someone mentioned it may have something to do with VNDK updates?

**Comment by jerpelea** [comment] 2018-11-14 08:20
the issue is fixed in vendor v3 and will be released soon

**Closed by jerpelea** 2018-11-14 08:20 UTC
