### ISSUE TITLE
[Tama] [Apollo] 4G/4G+ is slow compared to stock

### ISSUE THREAD

**Issue by AntonioBiscuit** [sonyxperiadev/bug_tracker#616] opened 2020-07-15 16:24 UTC
Platform: Tama
Device: Apollo
Kernel version: 4.14
Android version: PixelExperience_h8324-10.0-20200714-1039-OFFICIAL
Software binaries version: V9C

**Previously working on**
Stock Android (~200Mbit/s)

**Description**
4G/4G+ bandwidth is low compared to what I am used to see. It seems that I am capped to around 2 to 3Mbit/s (Upload and Download) on the same tower I was getting download speeds of 200Mbit/s (sustained) to even 300Mbit/s (peak).

**How to reproduce**
Speedtest or use the phone normally to notice slowdowns and low bandwidth.

**Additional Info**
I have -100dBm and 40 asu when making this speedtest. 2600MHz+1800MHz+700MHz bands are available.
I am able to get more bandwidth (>100Mbit/s) on an other phone at the same place, time and operator (Free). 
The tower is close to me and in countryside. Therefore, few people are using it too or making interference.

On a computer that was getting 300Mbit/s with Tethering on stock :

![image](https://user-images.githubusercontent.com/64173083/87569062-e5d53180-c6c6-11ea-94d2-6d6475917b55.png)

Phone Speedtest:

![Screenshot_20200715-175222](https://user-images.githubusercontent.com/64173083/87567798-043a2d80-c6c5-11ea-8d07-7e98ace22054.png)

Frequencies used during the test: 3CC logo means 2600MHz+1800MHz+700MHz bands used at the same time

![Screenshot_20200715-175232](https://user-images.githubusercontent.com/64173083/87567829-0ac8a500-c6c5-11ea-817e-487e5f214d9f.png)

**Comment by MartinX3** [comment] 2020-07-16 10:47
Duplicate of https://github.com/sonyxperiadev/bug_tracker/issues/524

Only XZ2/c hast the problem.
XZ3 is fine.

**Comment by bogi788** [comment] 2020-07-16 19:04
seems to happen on maple (XZ Premium) as well

**Comment by shinonome05** [comment] 2020-08-02 04:24
It happen on xz3 too.(h8416)

**Comment by ix5** [comment] 2020-08-08 17:12
Several devices should have gotten speed upgrades during latest kernel changes. Can you test again?

**Comment by MartinX3** [comment] 2020-08-08 17:33
XZ2
Forced LTE only
18.80 mbps down
1.05 mbps up

**Comment by bogi788** [comment] 2020-08-18 08:44
lte on maple is much faster now - i'm getting 50 down and 10 up (which is my plan's cap)

**Comment by AntonioBiscuit** [comment] 2020-08-18 09:09
Those are very good news to hear, I can't wait to test it out too :)

**Comment by jerpelea** [comment] 2021-04-12 10:42
fixed

**Closed** 2021-04-12 10:42 UTC
Labels: bug
