### ISSUE TITLE
[yoshino] xperiadev android10 (and Pie) not compatible with Treble gsi

### ISSUE THREAD

**Issue by iotY** [sonyxperiadev/bug_tracker#527] opened 2020-01-29 16:24 UTC
Actually all gsi bootloop on xperiadev Sony logo.

Is it possible to have Treble (Generic System Image) compatibility working with: XperiaDev's /vendor.img /boot.img, and corresponding Sony /oem.img (SW_xxx) ?

**Comment by ix5** [comment] 2020-01-29 18:17
Needs more information. Please fill in the information that was requested of you via the [issue template](https://github.com/sonyxperiadev/bug_tracker/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) when you created this bug.

**Comment by stefanhh0** [comment] 2020-02-01 13:23
Missing android 10 and pie compatibility with treble is not a bug but a feature request. The label of this issue should be changed accordingly.

Also aosp/sodp bootloops currently - I got a hint and will check if with that I get a working yoshino on aosp/sodp with Android-10 and Kernel-4.14.

**Comment by MarijnS95** [comment] 2020-02-01 13:33
@stefanhh0 That depends on the device. Given that we have everything set up properly it would be a bug if it doesn't work.

In fact, we are fully aware what problem @iotY is likely facing, but if he or she deliberately doesn't care to fill in the template, there is no need for us to waste time explaining that "likely" case either.

The bootloop on Yoshino non-Maple is likely caused by https://github.com/sonyxperiadev/kernel/commit/b0ee974, see https://github.com/sonyxperiadev/bug_tracker/issues/529.

**Comment by stefanhh0** [comment] 2020-02-01 16:08
Reverting https://github.com/sonyxperiadev/kernel/commit/b0ee974 did not do the trick. I'll open just another issue with the details.

**Comment by ix5** [comment] 2020-03-02 13:13
Please close this
@jerpelea

**Closed** 2020-03-02 13:18 UTC
Labels: bug
