### ISSUE TITLE
[Tama] - Android 8.1r46 - Touchscreen problems

### ISSUE THREAD

**Issue by MartinX3** [sonyxperiadev/bug_tracker#180] opened 2018-10-04 17:57 UTC
**Platform:** tama
**Device:** akari
**Kernel version:** 4.9
**Android version:** 8.1r46

**Description**
The touchscreen is not working as expected, it's picked up as a touchpad.
As you would move a mouse.

**Symptoms**
See descriptions.

**How to reproduce**
Use the touch.

**Comment by kholk** [comment] 2018-10-04 18:44
This problem cannot be reproduced on Synaptics Clearpad TS.

Please post the affected touchscreen model. Thanks.
P.S.: This issue smells of missing idc file!

**Comment by MartinX3** [comment] 2018-10-04 19:10
The XZ2 akari models having different touchscreen models?
Could you explan that for me? :)

**Comment by MartinX3** [comment] 2018-10-04 19:35
How to determine the model?
It was tested by another XDA user for me.

Which of the touchscreen models /hardware revisions fixed the touchscreen bugs?
When I write on my software keybard, sometimes it does ghost swipes or doesn't recognize my touches.

**Comment by kholk** [comment] 2018-10-04 19:41
On the stock rom, you can verify that in the service menu (*#*#SERVICE#*#*), since you cannot get a dmesg. 
I'm sorry but in this moment I have no stock device with me, so I cannot completely walk you through.

The Clearpad TS doesn't have the mouse issue, but I didn't test extensively for obvious reasons so I cannot tell you about ghost and/or missed touch events. 

Please always write your touchscreen model when reporting any kind of touchscreen bug on the entire Tama platform.
Thanks.

**Comment by MartinX3** [comment] 2018-10-04 19:46
Thank you!

@fl3x1324
Please dial `*#*#7378423#*#*` in stock rom and tell us which kind of touchscreen model you are using. :)

My one (i didn't test this bug) is
The window was white and dissappeared.

**Comment by jerpelea** [comment] 2018-10-04 19:46
please post a dmesg

**Comment by kholk** [comment] 2018-10-04 19:49
Alin, they can't take dmesg on stock!!

**Comment by MartinX3** [comment] 2018-10-04 19:50
@fl3x1324
And we need dmesg from the AOSP image.

**Comment by kholk** [comment] 2018-10-04 19:53
By the way, you tested your ts before I did paranoid fixes here and there. The display damage most probably derived from a bad setting of the LAB/IBB regulator, that was producing insane heat on the display driver ic.
To be clear, the driver ic on Akari is more or less behind the Sony logo on the glass. 

By the way, wrong voltage setting of this regulator will most probably create noise on the touchscreen itself, leading to any kind of ghosting and missed event issue. That can be an explaination of what you were experiencing.

**Comment by jerpelea** [comment] 2018-10-04 19:55
i added the se cond ts idc last week so it should be fixed now

**Comment by jamuir** [comment] 2018-10-04 20:02
> Alin, they can't take dmesg on stock!!

if you need it, then `adb bugreport` should capture dmesg on stock.

**Comment by MartinX3** [comment] 2018-10-04 21:05
@kholk 
Oh, the ghosting and not recognized touches while writing fast on the keyboard is my problem with stock firmware.
At 50% battery or in battery savings g mode it starts.
It got.much much better since the touch fixing monthly fix in the past.
But everyone I know (who uses a xz2 or xz2c) has this problem.
Sony is not helpful while answering at support.
Only told us to send the phone to repair or fullwipe it.

**Comment by kholk** [comment] 2018-10-04 21:49
Please don't mix stock issues with Open Devices issues.
Stock uses a different codebase and this bug tracker is for Open Devices only. If you want to report a stock bug, please use the dedicated support app on your phone or post on the Sony forums.

The display thing didn't have any more development since my last message about it.
Wait for Alin to get the userspace bits sorted out to allow an extensive prolonged test.

**Comment by kholk** [comment] 2018-10-04 21:50
@jamuir I've completely forgot that. Thanks for the precious reminder.

**Comment by MartinX3** [comment] 2018-10-04 21:53
@kholk yes of course, it was only a personal question.

This issue ticket is of course about the aosp build.

Okay. :)

**Comment by fl3x1324** [comment] 2018-10-04 22:08
@MartinX3 mine is with the Synaptics clearpad td4353jdi
I'll post dmesg from the aosp asap

**Comment by fl3x1324** [comment] 2018-10-04 22:44
@MartinX3 Is it ok if I use your build for h8266 if I'm with h8216? My build machine is down.

**Comment by MartinX3** [comment] 2018-10-04 23:44
Of course yes.
It will work with your phone.
The only difference is, that you will see a second SIM card slot menu entry. But that's a config entry.

**Comment by jerpelea** [comment] 2018-10-11 12:11
fixed and should work

**Closed by jerpelea** 2018-10-11 12:11 UTC
