### ISSUE TITLE
[Loire] encryption hangs boot very often on Android P 

### ISSUE THREAD

**Issue by harryharryharry** [sonyxperiadev/bug_tracker#214] opened 2018-10-19 11:26 UTC
**Platform:** Loire
**Device:** Kugo
**Kernel version:** 4.9.103-gdd5bd91d742b
**Android version:** 9.0

**Description**
After enabling encryption AND pattern unlock (or any unlock method really), the device hangs after providing the correct pattern on boot very often (I think it boots correctly about 1 in 20 times - or even less).
Logcat of hang at boot: http://ix.io/1pxr

**Symptoms**
Boot hangs on enabling encryption AND pattern unlock very often. However, only enabling encryption **without* pattern unlock (so no lock method enabled) boots the encrypted (as shown in settings) device fine, but without asking for unlocking (so useless encryption).

**How to reproduce**
After clean flash, I enabled pattern unlock and enable encryption.

Another quirk (maybe not related to android or omnirom, but to twrp 3.2.3): I found out that twrp provides the wrong unlock method for the encrypted android system: When I have set up a pattern unlocking, twrp shows a keyboard, and when I set up  unlock pin, twrp shows a pattern input.

**Comment by jerpelea** [comment] 2018-11-21 23:52
I can not replicate the issue 
please retest with vendor v3

**Comment by harryharryharry** [comment] 2018-11-22 11:50
Boot hangs with encryption still occur with v3: [logcat](http://ix.io/1u9X)
I tried booting with oem 8.1.6.4_r1_v16_loire (not expecting it to boot at all, because it is supposed to be for linux 4.4) but it does in fact boot into (encrypted) omnirom9: [logcat](http://ix.io/1u9W)

**Comment by jerpelea** [comment] 2018-11-22 11:58
@oshmoun can you replicate ?

**Comment by oshmoun** [comment] 2018-11-22 19:52
can't check unfortunately, due to using loire as a daily driver
it would be very bad if I lost my data due to this :sweat_smile: 

(@harryharryharry about slow sim detection, that is probably omni only
https://gerrit.omnirom.org/#/c/android_device_sony_common/+/32508/
feel free to try starting the service earlier to see if that helps)

**Comment by bartcubbins** [comment] 2018-11-30 04:16
> (aside: v3 also has the same sim issue v2 has: it takes a couple of minutes on boot before the sim is detected. I thought this was related to [this issue](https://github.com/sonyxperiadev/bug_tracker/issues/215), but since that is closed as fixed, should I create a separate bug issue ?)
also can confirm this

**Comment by Gray47Maxx** [comment] 2018-12-23 08:15
Can confirm this as well on suzu. Without any passwords the phone works just fine.

**Comment by harryharryharry** [comment] 2018-12-23 09:09
I had a boot loop again the first time I flashed v4 (I had adb enabled and saw some 'skia unlinked error messages during the hang), but I managed to get things working again through twrp (I think I did a wipe of 'system' and flashed omnirom again - which I heard might be a little superfluous, flashing the rom might have been enough.)

**Comment by gerg5c42g542g2c54g52c** [comment] 2019-01-14 14:16
Does this only happen on Omnirom?

@bartcubbins @Gray47Maxx

**Comment by bartcubbins** [comment] 2019-01-14 15:02
No, not only

**Comment by gerg5c42g542g2c54g52c** [comment] 2019-01-14 16:08
@bartcubbins unmodified AOSP android-9.0.0_r21 too?

**Comment by bartcubbins** [comment] 2019-01-14 16:15
yes r21

**Comment by gerg5c42g542g2c54g52c** [comment] 2019-01-22 14:53
Confirming. This happens on suzu with clean, unmodified AOSP android-9.0.0_r30 (whole repo synced yesterday), vendor image v5.

I don't even have to enter the password for the device to restart, just wait a bit and `Shutting down...` message appears and the device reboots. It reboots whether I enter the password or not, if I enter it, sometimes I see the `Shutting down...` message, sometimes not (properly depends on how fast I enter the password).

Please fix this as soon as possible, it's been a few months already.

**Comment by Gray47Maxx** [comment] 2019-01-22 16:10
And again, confirmed. Getting the same thing + it boots sometimes,but for 1-2 minutes and it's **very** laggy.

**Comment by oshmoun** [comment] 2019-01-22 17:41
@gerg5c42g542g2c54g52c that comment is obsolete by now. kugo here is encrypted currently.
I can't seem to get the issue to appear though, using pattern unlock.

**Comment by gerg5c42g542g2c54g52c** [comment] 2019-01-22 19:15
> Another quirk (maybe not related to android or omnirom, but to twrp 3.2.3): I found out that twrp provides the wrong unlock method for the encrypted android system: When I have set up a pattern unlocking, twrp shows a keyboard, and when I set up unlock pin, twrp shows a pattern input.

Confirming this too. How do you get into TWRP in this case?

I managed to boot it after reflashing and setting a pattern unlock instead of a password, but this is insecure and the issue is still there, it's simply bypassed by entering the password/pattern fast enough. I recommend using a 16 char long password to test this and also trying not entering the password and waiting for a few minutes to see if it reboots. Also, when one flashes TWRP it will reboot to recovery instead of bootlooping.

You can also try a 32 or 64 char long password after applying this patch:
```
diff --git a/frameworks/base/core/java/android/app/admin/DevicePolicyManager.java b/frameworks/base/core/java/android/app/admin/DevicePolicyManager.java
index 22367b21221..04b81b9404a 100644
--- a/frameworks/base/core/java/android/app/admin/DevicePolicyManager.java
+++ b/frameworks/base/core/java/android/app/admin/DevicePolicyManager.java
@@ -2765,7 +2765,7 @@ public class DevicePolicyManager {
      */
     public int getPasswordMaximumLength(int quality) {
         // Kind-of arbitrary.
-        return 16;
+        return 64;
     }

     /**
--
```

**Comment by oshmoun** [comment] 2019-01-23 21:48
@gerg5c42g542g2c54g52c I rebooted kugo, left it on the black screen for about 5 minutes, then entered the correct pattern and it decrypted and continued the boot just fine. should these steps have been sufficient to trigger the issue you are describing or am I doing something different?
I also tried entering the wrong pattern, no crashing, just an error message and then back to the pattern unlock screen.
I'll try password next

**Comment by jerpelea** [comment] 2019-02-07 12:17
I can not reproduce anymore

**Comment by gerg5c42g542g2c54g52c** [comment] 2019-02-17 12:37
> I can not reproduce anymore

@jerpelea please reopen. Still not fixed on suzu, vendor v5, built yesterday.

**Comment by oshmoun** [comment] 2019-02-17 20:15
@gerg5c42g542g2c54g52c can you please try a small change?
https://github.com/sonyxperiadev/device-sony-loire/blob/master/rootdir/vendor/etc/rqbalance_config.xml
force all cores online by making sure `min_cpus="6"` and `max_cpus="6"` anywhere in that file

**Comment by gerg5c42g542g2c54g52c** [comment] 2019-03-07 21:07
@oshmoun built with your change today, bootloops not only when booting, but also after booting to the OS.

**Comment by oshmoun** [comment] 2019-03-07 21:59
@gerg5c42g542g2c54g52c it is improbable there is a relation between the change to force all cores on and bootloops, but just to be safe, can you try without it?

**Comment by gerg5c42g542g2c54g52c** [comment] 2019-03-08 10:56
@oshmoun you're right, it bootloops without this change too. I'll be debugging. Does the yesterday's (or current) HEAD bootloops for anyone else? Did you have to reflash userdata after going to either vendor v6 or android-9.0.0_r34?

**Comment by gerg5c42g542g2c54g52c** [comment] 2019-03-08 13:11
Ok, confirmed that the second bootloop is unrelated (no clue about the cause, no changes on my part). The first bootloop remains unfixed.

**Comment by oshmoun** [comment] 2019-03-11 11:56
@gerg5c42g542g2c54g52c was your test with or without this?
https://github.com/sonyxperiadev/kernel/pull/1935
regardless, you can try going back to a previously known working kernel and seeing if that helps. For instance, you can `git checkout` this commit:
https://github.com/sonyxperiadev/kernel/commit/d5a42cdc522d688bdbf7adc5be3d63e0c02a9d06

**Comment by jerpelea** [comment] 2019-03-11 12:58
I just build suzu on HEAD^ and there is no bootloop on the first boot 
The device booed fine to Homescreen

**Comment by oshmoun** [comment] 2019-06-04 22:12
any more reports of this issue happening? if not, this could be closed.

**Comment by harryharryharry** [comment] 2019-06-04 22:17
For me, this issue can be closed. I've not had issues with encryption since half December.

**Closed** 2019-06-05 07:01 UTC
