### ISSUE TITLE
[tama] sensors crash and cause a soft reboot

### ISSUE THREAD

**Issue by oshmoun** [sonyxperiadev/bug_tracker#266] opened 2018-12-15 18:55 UTC
**Platform:** tama
**Device:** apollo
**Kernel version:** 4.9
**Android version:** 9.0

**Description**
When sensors are utilized by multiple apps at once, the hal crashes and causes a soft reboot

**Symptoms**
Sensors hal crashes with the following error:
https://del.dog/yutiyocuxa.rb
a soft reboot follows, which leads back to the lockscreen

**How to reproduce**
1. open the app GPS Status (https://play.google.com/store/apps/details?id=com.eclipsim.gpsstatus2)
2. press the home button to switch to Picture-in-Picture mode
3. launch Google maps
4. device will soft reboot

**Comment by oshmoun** [comment] 2018-12-23 21:54
can confirm it still happens, just have to try a couple times
https://del.dog/wovodapuga.coffeescript

**Comment by MarijnS95** [comment] 2018-12-23 21:54
This is reproducible for me on v4 blobs, with all repositories updated just a few hours ago.

To reproduce this you have to try a few times. In my case it happened right after opening Google Maps for the second time.

**Comment by jerpelea** [comment] 2019-01-09 13:40
@MarijnS95 please test after sync

**Comment by MarijnS95** [comment] 2019-01-09 22:49
@jerpelea Still able to reproduce. It seems to be an issue in the odm sensor blob, which is not magically solved by syncing and rebuilding the open source repos.

If you want I can arrange a log with more debugging information.

**Comment by jerpelea** [comment] 2019-01-10 04:46
I suspected the dsp subsystem and I could not reproduce it with the latest bootloader and code

**Comment by jerpelea** [comment] 2019-02-22 09:13
fixed in v6

**Closed by jerpelea** 2019-02-22 09:13 UTC
