### ISSUE TITLE
[TAMA] [AKATSUKI] [CRITICAL??] Speakers clipping and distortion

### ISSUE THREAD

**Issue by kholk** [sonyxperiadev/bug_tracker#411] opened 2019-05-27 09:17 UTC
**Platform:** Tama
**Device:** Akatsuki
**Kernel version:** 4.9.x
**Android version:** 9.0.x

**Description**
When playing any kind of sound, apart (so, not with) phone calls on the earpiece only, but
including phone calls on loudspeaker, ringtones, music or whatever else using the amplified
paths, the device suffers of _really bad clipping_ and some distortion.

Please note that **this is getting worse over time**, meaning that maybe the speakers
are indeed _getting damaged_, or when the speaker grills/channels get lil dirty (despite
the user paying attention in keeping the grills clean) the audio quality degrades like that.

**Symptoms**
Audio clipping and distortion on loudspeaker calls or music reproduction.

**How to reproduce**
Just raise the volume to at least "3/4 of the volume bar" and play something,
or just make the phone ring by calling yourself or setting up an alarm.

Tagging @richardtullberg to inform him of the issue.

**Comment by haldi4803** [comment] 2019-05-28 12:50
You mean like this?

https://youtu.be/ot3rFUuC7sQ

**Comment by kholk** [comment] 2019-05-28 13:42
No it's not like this, the major issue is clipping and distortion is strictly relative to clipping.
Also, the issue on Akatsuki happens on both speakers, but mainly on the loudspeaker, lightly on the earpiece.

**Comment by MartinX3** [comment] 2019-05-28 13:50
I can confirm the same on akari.

**Comment by ozamyatin** [comment] 2019-05-28 22:08
I can confirm this issue for Akatsuki XZ3 Dual Sim 9436 and all of the roms available on xda for our device, namely Sony AOSP and Omni ROM.

**Comment by MartinX3** [comment] 2019-05-30 10:06
I will via ADB output the `tinymix` result on STOCK and on SODP at 2:03
https://youtu.be/S7rRA-V-0zY

Maybe it will help us.
I will attach the 2 files soon.

PS:
The sound is so crispy like crispy chicken.

**Comment by ix5** [comment] 2019-06-02 13:11
Kagura is also affected (closing #365 in favour of this)

**Comment by kholk** [comment] 2019-06-02 13:52
@ix5 This is a per-device configuration thing for the 99%, so your Kagura issue is not a duplicate of this one and needs to be addressed separately anyway, so... Reopen yours ;)

**Comment by manuerduarte** [comment] 2019-08-05 13:34
hi, i kind of solve the problem in my device XZ2 (Akari) editing this files. First i tried to lower the volume of speakers change the mixer_paths.xml file, but the problem remains at a much lower volume, at 75% of the volume slider the clipping start, so i change the other 2 files, limiting the max value of the volume slider of the device.

    <reference name="FULL_SCALE_VOLUME_CURVE">
    
        <point>0,0</point>
        **<point>100,0</point>**
    </reference>
    <reference name="SILENT_VOLUME_CURVE">
        <point>0,-9600</point>
        **<point>100,-9600</point>**
    </reference>
    <reference name="DEFAULT_SYSTEM_VOLUME_CURVE">
    
        <point>1,-2400</point>
        <point>33,-2000</point>
        <point>66,-1800</point>
        <point>100,**-1200**</point>

as you can see, the max value of the volumen slider is 0, the less is -9600, so i change the max 0 to -1200 in media, ringtone, notification and alarms. 
The device don't cliiping any more but the volume is weaker, so i raise the speaker volume in mixer_paths again changing RX7 and RX8 from 84 to 88 or 90 for now, and the clipping and distortion don't appear, even at max volume, so i thing the problem is let the volume slider raise to 0 (max) level in volume files and not the real volume of the speakers.
obviusly if my first attemp, i will still trying to see the limits of the speakers volume without clipping and distortion, these configs work well in xz2 Akari, in others devices probably you will need to test, and change values according to the results.
I hope this contribution is useful to you.
[XZ2 AOSP SP FIX.zip](https://github.com/sonyxperiadev/bug_tracker/files/3467766/XZ2.AOSP.SP.FIX.zip)
All files are from vendor/etc

**Comment by Bronxxx** [comment] 2020-02-13 06:31
Mmy wife abd me have Xperia xz3 out of the box and booth have that issue. But not only from speaker, but also when the device is conected via bluetooth.

**Closed** 2021-04-12 10:27 UTC
