### ISSUE TITLE
[kirin] [aosp 10] [kernel 4.14] GPU-related crashes hang the device

### ISSUE THREAD

**Issue by xperia10dev** [sonyxperiadev/bug_tracker#559] opened 2020-03-16 18:25 UTC
**Platform:** ganges
**Device:** kirin (i4113)
**Kernel version:** 4.14.172
**Android version:** android-10.0.0_r30
**Software binaries version:** 10.0.7.1_r1_v4c_ganges

**Previously working on**
Not sure, this is the first time I use an Android 10 / Kernel 4.14 build on this device for any amount of time significant enough to notice these GPU crashes.

**Description**
Sometimes, apparently in a random manner, after a period of time being in use, the phone becomes unresponsive to any inputs (power button, fingerprint reader) and the screen becomes fully white or grey. The application being used does not seem to matter, it has happened multiple times with different applications.

**Symptoms**
Fully white or grey screen, no response to input on physical buttons, device reachable via adb.

**How to reproduce**
Use the device normally for a few hours / days.

**Additional context**
Attached logcat with GPU crashes.
[logcat_gpu_crashes.txt](https://github.com/sonyxperiadev/bug_tracker/files/4339763/logcat_gpu_crashes.txt)

**Comment by MarijnS95** [comment] 2020-03-16 18:32
This is likely a duplicate of #510, except that it _does_ include the requested traces from dmesg.

The crash itself is long known, but no-one except @haxk20 had time to look into it. I don't know the current state of fixing it, aside safe parking - which is an unnecessary hack in and of itself) - not solving it either (though it at least seems to alleviate the issue somewhat).

**Comment by MarijnS95** [comment] 2020-03-16 18:41
To be more clear, I have [reverted safe parking](https://github.com/MarijnS95/kernel/commit/40781b9c48a7) and [extended logging](https://github.com/MarijnS95/kernel/commit/cd55550dee44) quite some time ago in hopes to reproduce the issue and understand under what occasions this seems to happen. Without result.

Would you mind applying those commits and post the complete dmesg as soon as it appears?

**Comment by Haxk20** [comment] 2020-03-16 19:12
Yeah i did look into it slightly.
But as Marijn suggested. Please revert safe parking and enable extended logging and post full dmesg. Not only the last lines.
Thank you.

**Comment by MarijnS95** [comment] 2020-03-16 19:15
I would say the last lines are fine, _as long as it includes the first update_config_ failure. Include a couple lines before that to err on the safe side.

That said I'm looking into the clock tree right now, and there are interesting changes to say the least. We might have a testable fix later tonight, if these diffs don't turn out to be moot...

**Comment by xperia10dev** [comment] 2020-03-17 05:25
I booted the kernel patched with https://github.com/MarijnS95/kernel/commit/40781b9c48a7 and https://github.com/MarijnS95/kernel/commit/cd55550dee44 for a few hours, but unfortunately could not reproduce the issue.
Have to go back to Android 9 / Kernel 4.9 for now since this is my daily driver device.

**Comment by MarijnS95** [comment] 2020-03-17 08:56
@xperia10dev Would you mind testing https://github.com/sonyxperiadev/kernel/pull/2217 instead? That _should_ fix the issue entirely. Apply https://github.com/MarijnS95/kernel/commit/cd55550dee44 on top just in case it keeps happening, that gives us ever so slightly more information about the current and requested state.

**Comment by xperia10dev** [comment] 2020-03-17 09:01
Sorry, I won't be able to perform more tests anytime soon, device is back to Android 9 / Kernel 4.9 to ensure stability as I need it to be fully funcional right now. Will get back to you when possible.

**Closed** 2020-03-17 15:06 UTC
Labels: bug
