### ISSUE TITLE
[nile/pioneer] Android 9 - reboot on making call

### ISSUE THREAD

**Issue by igkn02** [sonyxperiadev/bug_tracker#298] opened 2019-01-09 13:30 UTC
**Platform:** nile
**Device:**  pioneer h3113
**Kernel version:** 4.9.144, 4.9.146
**Android version:** 9.0.0_r16 (Checkout 20 Dec), 9.0.0_r21 (Checkout 6 Jan)

**OEM:** SW_binaries_for_Xperia_Android_9.0_2.3.2_v4_nile (also reproducible on v3,v2..)
**Baseband:** both 2018/08 and 2018/02

**Description**
When starting call from dialer, or receiving a call, device goes into immediate cold reboot (e.g. not system_server/zygote crash - bootloader unlocked screen, boot logo, etc).

**Symptoms**
Doesn't seem to be kernel panic as there's only normal 2 logs in /sys/fs/pstore.
Nothing relevant in logs - Telecom reports call initiation, then - bang reboot.

**How to reproduce**
Build, flash, call.

----
1) repo_update applied properly on both source trees, clean sources were used to confirm crash.
2) using different workarounds (reboot commands disabled in system_server source, different log levels for kernel achieved with ```echo 7 > /proc/sys/kernel/print && echo 600 > /proc/sys/kernel/panic````)  got a couple of hints (like system_server receving reboot request and processes being killed, or some crashes inside adsprpcd), but no success tracing problem to its root yet. Could be either kernel triggering some nasty stuff in chipset or some bad vendor binary for all I know... any pointers? Is 4.9 kernel OK for sdm660?

**Comment by kholk** [comment] 2019-01-11 15:09
This issue is a duplicate of https://github.com/sonyxperiadev/bug_tracker/issues/272 .
Solved in https://github.com/sonyxperiadev/kernel/pull/1867

**Closed** 2019-01-11 16:40 UTC
