### ISSUE TITLE
[tone][dora] Top speaker does not work in media apps

### ISSUE THREAD

**Issue by Mohnach** [sonyxperiadev/bug_tracker#331] opened 2019-02-07 16:49 UTC
**Platform:** Tone
**Device:** Dora F8132
**Kernel version:** 4.9.152
**Android version:** 9.0.0_r30

**Description**
Top speaker does not work in media apps, but works well in phone app. Strange thing: after a phone call, the speaker begins to work in media applications, but only until the reboot

**Symptoms**
Top speaker does not work in media apps
Bottom speaker always works correctly

**How to reproduce**
Play any audio file in any player. I run deezer in attached logfile
[2019-02-06-22-01-12.txt](https://github.com/sonyxperiadev/bug_tracker/files/2841833/2019-02-06-22-01-12.txt)

**Comment by djselbeck** [comment] 2019-02-07 16:50
Perhaps a duplicate of #231

**Closed** 2019-02-08 03:15 UTC
