### ISSUE TITLE
[lilac] [aosp 10] [kernel 4.14] In main: Sensor is null

### ISSUE THREAD

**Issue by AlbertBackenhof** [sonyxperiadev/bug_tracker#520] opened 2020-01-21 18:04 UTC
**Platform:** yoshino
**Device:** lilac (g8441)
**Kernel version:** 4.14.83
**Android version:** android-10.0.0_r21
**Software binaries version:** 10.0.7.1_r1_v3a_yoshino

**Description**
After boot the device is very slow and after a few seconds it reboots. The logs show "fatal exception", in the main of booting up, caused by the Accelerometer sensor being null. This seems to have been an issue previously on Android 8.1.0 (#265) , caused by a race condition. From what I've found this should be fixed though. I've tried the solution from #515 but that didn't work for me.

**How to reproduce**
Build and flash according to the sony guide.

[logcat.log](https://github.com/sonyxperiadev/bug_tracker/files/4092757/logcat.log)

**Comment by MarijnS95** [comment] 2020-01-21 18:32
The `adsprpcd` errors are more worrisome, and likely the cause of sensor failures.

Hence why we have recently (yesterday) merged a simple patch to _finally_ enable error logging for the kernel driver that is preventing this from working: https://github.com/sonyxperiadev/kernel/pull/2160.

Can you make sure that you have the kernel compiled with that commit? The [most recent prebuilts](https://github.com/sonyxperiadev/kernel-sony-msm-4.14-common/commit/5233beee3799ff1a84319c21b48cf5ed87c1c0bf) include it too.

After that, pass us a `dmesg`.

**Comment by AlbertBackenhof** [comment] 2020-01-21 19:46
Will do. Thanks!

**Comment by AlbertBackenhof** [comment] 2020-01-22 13:31
Just finished building and flashing. With the new kernel the device restarts before reaching the UI. While still on the "android" screen.
[logcat.log](https://github.com/sonyxperiadev/bug_tracker/files/4097531/logcat.log)
[dmesg.log](https://github.com/sonyxperiadev/bug_tracker/files/4097532/dmesg.log)

**Comment by MarijnS95** [comment] 2020-01-22 13:42
The reboots on Yoshino should be caused by the modem failing (#512, with the fix just merged: https://github.com/sonyxperiadev/kernel/pull/2163), though I don't see the same issues in your dmesg.

Thanks for the dmesg anyway, that makes the error pretty obvious. The driver creates  the cdev without the device ever probing. Ioctls called on the device will later run into that device missing: `drivers/char/adsprpc.c:3268:error: -1: NULL != me->channel[cid].rpdev`.
I'll check the DT and reply if I find something.

**Comment by AlbertBackenhof** [comment] 2020-02-08 19:21
I no longer see this error in the logs

**Closed** 2020-02-08 19:21 UTC
