### ISSUE TITLE
[kirin] [aosp 10] [kernel 4.14] Thermal crashes on boot

### ISSUE THREAD

**Issue by xperia10dev** [sonyxperiadev/bug_tracker#516] opened 2020-01-19 10:58 UTC
**Platform:** ganges 
**Device:** kirin (i4113)
**Kernel version:** 4.14.83 
**Android version:** android-10.0.0_r21 
**Software binaries version:** 10.0.7.1_r1_v3_ganges 

**Description**
Thermal crashes on boot

**Symptoms**
No apparent observable symptoms, crashes found in logcat

**How to reproduce**
Boot the device

**Additional context**
Logcat attached
[thermal_crashes.log](https://github.com/sonyxperiadev/bug_tracker/files/4082542/thermal_crashes.log)

**Comment by MarijnS95** [comment] 2020-01-19 11:00
https://github.com/sonyxperiadev/bug_tracker/issues?q=is%3Aissue+thermal

Duplicate of https://github.com/sonyxperiadev/bug_tracker/issues/470

**Closed** 2020-03-02 14:01 UTC
Labels: bug
