### ISSUE TITLE
[LILAC] Device encryption not functional

### ISSUE THREAD

**Issue by bobobo1618** [sonyxperiadev/bug_tracker#15] opened 2017-10-29 23:28 UTC
Device: XZ1 Compact (G8441)
Kernel version: Git gfa0fbdd
Android version: 8.0.0 (AOSP)

**Description**
Enabling device encryption using Android's settings menu causes the device to continuously reboot without reaching the lock screen.

**How to reproduce**

- Install
- Set a lockscreen pattern/PIN/password
- Settings -> Security & Location -> Encryption & Credentials -> Encrypt Phone
- (Android picture is displayed)
- (Phone enters bootloop)

I've also attempted:

- `fastboot --wipe-and-use-fbe` - Simply doesn't do anything
- `vdc cryptfs enablefilecrypto` - Causes `vold` to segfault
- `vdc cryptfs enablecrypto inplace pin 1234` - Puts the device in a state where it freezes at the Sony logo
- `vdc cryptfs enablecrypto wipe pin 1234` - Before rebooting to the `android` logo indefinitely, spits out these logs in ADB:

```
01-01 12:09:12.587   611   611 E keymaster1_device: Generate key send cmd failed
01-01 12:09:12.587   611   611 E keymaster1_device: ret: 0
01-01 12:09:12.587   611   611 E keymaster1_device: resp->status: -30
01-01 12:09:12.587  4896  4961 E vold    : generate_key failed, code -30
01-01 12:09:12.587  4896  4961 E Cryptfs : Failed to generate keypair
01-01 12:09:12.587  4896  4961 E Cryptfs : keymaster_create_key failed
01-01 12:09:12.587  4896  4961 E Cryptfs : Cannot create encrypted master key
01-01 12:09:12.587  4896  4961 E Cryptfs : Error enabling encryption after framework is shutdown, no data changed, restarting system
```

**Comment by jamuir** [comment] 2017-10-30 01:11
Does recovery mode work on the XZ1 Compact?  If not, then that might explain why selecting "Encrypt Phone" from Settings does nothing.

I tried to enable FBE on the XZ Premium, but was not successful.

**Comment by jerpelea** [comment] 2017-10-30 09:14
can you enter recovery by using 
adb reboot recovery

**Comment by bobobo1618** [comment] 2017-10-31 00:50
Yes but it presents the apparently horizontally truncated error message:

```
Can't load Android system. Your data ma
If you continue to get this message, yo
perform a factory data reset and erase 
stored on this device
```

Note that contrary to the published instructions, I flashed the `recovery.img` that resulted from an AOSP build. I tried before doing so but it just appeared to do a regular reboot.

**Comment by bobobo1618** [comment] 2017-10-31 02:04
I built a TWRP recovery using a lightly modified [tree](https://github.com/TeamWin/android_device_sony_maple/) and even with a working recovery, encryption doesn't work. The significant line from what I can see is:

```
10-30 19:00:37.833   557  5249 E Cryptfs : Bad magic for real block device /dev/block/bootdevice/by-name/userdata
10-30 19:00:37.833   557  5249 E Cryptfs : Orig filesystem overlaps crypto footer region.  Cannot encrypt in place.
```

**Comment by jerpelea** [comment] 2017-11-01 12:07
recovery mode is fixed on yoshino platform 
i will test the encryption soon

**Comment by jamuir** [comment] 2017-11-01 14:09
Looks like the userdata partition size may need to be adjusted:

https://github.com/CyanogenMod/android_device_motorola_xt907/issues/3

**Comment by jerpelea** [comment] 2017-11-01 14:15
fastboot getvar all will report the partition size

**Comment by jerpelea** [comment] 2017-11-01 20:37
for poplar the reported size seems to differ from actual size on sw 47.1.A.2.324

fastboot getvar all
(bootloader) partition-size:userdata: 0xCFA976000
(bootloader) partition-size:system: 0x138800000

vs
cat /proc/partitions
252        0    5040116 dm-0 (system)
259       50   54437336 sda66 (userdata)

which would lead to the new sizes
+BOARD_SYSTEMIMAGE_PARTITION_SIZE := 5161078784
+# Reserve space for data encryption (5574382592-16384)
+BOARD_USERDATAIMAGE_PARTITION_SIZE := 5574366208

**Comment by bobobo1618** [comment] 2017-11-02 03:14
Your userdata sizes seem to match there:
```
0xCFA976000   = 55743832064
54437336*1024 = 55743832064
```

Shouldn't the new size be 55743830436?

And this doesn't seem to be a problem on Lilac:

```
> fastboot getvar all
(bootloader) partition-size:cache: 0x17C00000 (398458880)
(bootloader) partition-size:userdata: 0x587D76000 (23753875456)
(bootloader) partition-size:system: 0x138800000 (5242880000)

> adb shell cat /proc/partitions
 259       37     389120 sda53 (cache - 398458880)
 259       50   23197144 sda66 (userdata - 23753875456)
 259       49    5120000 sda65 (system - 5242880000)
```

By the way if you have root you can use `blockdev --getsize64 /dev/block/sda66` which will save you some conversion effort.

I investigated a little more and when I ran `tune2fs -l /dev/block/sda66`, I found this:

```
Block count:              5799286
Block size:               4096
```

It turned out my earlier error was a result of me using `fastboot format userdata` thinking it was the same as flashing the empty userdata. It wasn't. `fastboot format` uses the entire block device, so the footer at the end isn't there.

After fixing that by flashing `userdata.img`, I get past `Orig filesystem overlaps crypto footer region.` but I still get a bootloop.

Oddly, I'm now unable to boot into recovery again. I was able to with an earlier image but after syncing and rebuilding, I get the "Can't load Android system" message. Perhaps I've done something wrong, I'll keep investigating.

**Comment by jerpelea** [comment] 2017-11-02 06:19
@bobobo1618 dod you check after you flashed the  47.1.A.2.324 sw or after you flashed AOSP?

**Comment by bobobo1618** [comment] 2017-11-02 06:28
After flashing AOSP.

**Comment by jerpelea** [comment] 2017-11-02 06:58
in this case your partition report is irelevant
sizes must be compared on 47.1.A.2.324 sw

**Comment by bobobo1618** [comment] 2017-11-02 16:49
Fair enough. I inspected the GPT partition table from Sony's image directly by extracting and hex dumping `partition-image-LUN0_X-FLASH-ALL-C93B.sin`:

- Cache starts at LBA 207731 and ends at LBA 110452, which is a size of 398458880
- System starts at LBA 730757 and ends at LBA 2010756, which is a size of 5242880000
- Userdata starts at LBA 2010757 and ends at LBA 7810042, which is a size of 23753875456

All match.

**Comment by jerpelea** [comment] 2017-11-02 19:15
I investigated lilac on sw 47.1.A.2.324

fastboot getvar all
(bootloader) partition-size:userdata: 0x587D76000
(bootloader) partition-size:system: 0x138800000

cat /proc/partitions
259       50   23197144 sda66 (data)
252        0    5040116 dm-0 (system)

**Comment by jerpelea** [comment] 2017-11-15 08:38
bug confirmed on lilac and poplar

**Comment by jamuir** [comment] 2017-12-11 19:54
@bobobo1618 :  is this still broken?

device encryption is working on maple now, as per the following change:

https://github.com/sonyxperiadev/device-sony-maple/commit/0de5978ea421695656a186f5ac9600e0c3e9ad00

(that commit is on the nougat branch -- I haven't tried it in oreo)

Another way to fix this, which I have used on maple, is to use the `fsmetadata` partition to hold the device encryption meta data.

**Comment by jerpelea** [comment] 2018-01-12 13:27
fixed on the v7 blob release

**Closed by jerpelea** 2018-01-12 13:27 UTC
