### ISSUE TITLE
[yoshino] - Android 9 - Black screen when waking device from sleep/doze

### ISSUE THREAD

**Issue by invalidsudo** [sonyxperiadev/bug_tracker#167] opened 2018-09-15 04:33 UTC
**Platform:** yoshino
**Device:** lilac
**Kernel version:** 4.9
**Android version:** 9

**Description**
When the device goes into deep sleep/doze and is woken by pressing the power button, the display turns on but shows nothing, then turns back off following the standard inactivity timeout duration.

Worth noting that the device is actually responsive, double-pressing the power button leads to a vibration indicating that the camera app has opened.

**Symptoms**
Black screen when waking device.
Hard reset (vol-up and power) required in order to use device normally.

**How to reproduce**
1. Put device into sleep for around a minute.
2. Attempt to wake device from sleep by pressing the power button.

**Comment by oshmoun** [comment] 2018-09-15 13:01
this affects all yoshino devices

**Comment by jerpelea** [comment] 2018-10-01 14:07
the issue is mostly mitigated and display will resume almost all the time

**Comment by jerpelea** [comment] 2018-10-03 13:54
@invalidsudo please check the status

**Comment by jerpelea** [comment] 2018-11-01 10:00
the full fix will be released in the next vendor release

**Closed by jerpelea** 2018-11-01 10:00 UTC
