### ISSUE TITLE
[Tama] - Android 8.1r46 - Camera is not accessible(just gray screen with the navbar at the bottom)

### ISSUE THREAD

**Issue by MartinX3** [sonyxperiadev/bug_tracker#188] opened 2018-10-04 18:03 UTC
**Platform:** tama
**Device:** akari
**Kernel version:** 4.9
**Android version:** 8.1r46

**Description**
Camera is not accessible(just gray screen with the navbar at the bottom)

**Symptoms**
Camera is not accessible(just gray screen with the navbar at the bottom)

**How to reproduce**
Camera is not accessible(just gray screen with the navbar at the bottom)

**Comment by jerpelea** [comment] 2018-10-04 19:53
camera support is not added yet

**Comment by jerpelea** [comment] 2018-11-14 08:20
the issue is fixed in vendor v3 and will be released soon

**Closed by jerpelea** 2018-11-14 08:20 UTC
