### ISSUE TITLE
[Yoshino/Lilac] Bluetooth audio music listening causes reboots

### ISSUE THREAD

**Issue by djselbeck** [sonyxperiadev/bug_tracker#348] opened 2019-02-27 09:02 UTC
**Platform:** Yoshino
**Device:** Lilac
**Kernel version:** 4.9.155-g43d94cf08051-dirty
**Android version:** `Sony/aosp_g8441/lilac:9/PQ2A.190205.001/hendrik02220811:userdebug/test-keys`

**Description**
Listening to music over a bluetooth audio device will sporadically reboot the device. I have to bluetooth music receivers (Fiio BTR3 with LDAC and a Logitech Boom something box with SBC)

I first noticed the problems after upgrading to vendor v6.
**Symptoms**
The device will just freeze and reboot.

**How to reproduce**
Listening to music over bluetooth audio devices

I attach the pstore files. (pmsg includes some bluetooth related messages at the end, device wake up failed)

[console-ramoops-0.txt](https://github.com/sonyxperiadev/bug_tracker/files/2909351/console-ramoops-0.txt)
[pmsg-ramoops-0.txt](https://github.com/sonyxperiadev/bug_tracker/files/2909352/pmsg-ramoops-0.txt)

To be sure I will do a new build now and continue testing

**Comment by djselbeck** [comment] 2019-02-27 10:24
It froze again with a up-to-date build.

[console-ramoops-0.txt](https://github.com/sonyxperiadev/bug_tracker/files/2909739/console-ramoops-0.txt)
[pmsg-ramoops-0.txt](https://github.com/sonyxperiadev/bug_tracker/files/2909740/pmsg-ramoops-0.txt)

**Comment by djselbeck** [comment] 2019-02-27 13:15
The crashes also happen with vendor v5

**Comment by jamuir** [comment] 2019-02-27 16:53
Do you have google apps on the device?

If so, then try disabling "location" to see if that improves things.

On maple, I found that Google Play Services (the google location provider) was repeatedly scanning for bt devices every 5 seconds (changing the "Location mode" to "device only" did not stop it).  This caused audio issues when using bt.

**Comment by djselbeck** [comment] 2019-02-27 16:56
No but microg with network-based location providers.

I will try it tomorrow as I left my BT receiver in my office.

**Comment by djselbeck** [comment] 2019-02-28 09:43
Disabling the "location" within Android did unfortunately not help

**Comment by stefanhh0** [comment] 2019-02-28 18:22
@djselbeck I am also having intermittent reboots, sometimes I play music over bt, sometimes via connected audio cable and sometimes when not playing audio. Don't know though if that is related to what you are experiencing.

See also #317 

The reboots occur nearly every day, however sometimes the phone runs stable for a day. On bad days I have several reboots a day.

**Comment by djselbeck** [comment] 2019-02-28 18:28
No I don't think it is related.

I can listen to music over wired headphones for hours without any problems. Today my BT audio, however, crashed every second track or so.

**Comment by jerpelea** [comment] 2019-03-01 13:06
one of the instability causes was identified in the zram and the offending patches were reverted 
please rebuild the kernel and check if you can replicate the reported issues

**Comment by djselbeck** [comment] 2019-03-02 08:20
After roughly an hour of music listening over bluetooth the device just rebooted itself again

**Comment by stefanhh0** [comment] 2019-03-02 18:54
@djselbeck are you using any non-default bluetooth setting in the developer options, like AVRCP 1.6 or so? At least I had a freeze/crash reboot using that one while playing music over bt.
For now I've switched back to 1.4 to see if that makes a difference...

Infos about that occurrence:
**Kernel version:** 4.9.158-g40f2ede5e12a
**Android version:** android-9.0.0_r31
**OEM Image:** SW_binaries_for_Xperia_Android_9.0_2.3.2_v6_yoshino.img
**Build:** aosp_g8441-userdebug 9 PQ2A.190205.001 eng.stefan.20190302.081554
**Version baseband:** 1307-7511_47.1.A.16.20
**Logs:** [pstore.tar.gz](https://github.com/sonyxperiadev/bug_tracker/files/2922412/pstore.tar.gz)

**Comment by stefanhh0** [comment] 2019-03-02 19:27
Also with AVRCP 1.4 freeze/crash and reboot occurred while playing music over bt. This time no dmesg file was written: [pstore.tar.gz](https://github.com/sonyxperiadev/bug_tracker/files/2922436/pstore.tar.gz)

**Comment by ix5** [comment] 2019-03-03 15:41
@stefanhh0 your pmsg-ramoops is very odd, are you perhaps running a GSI on top of your aosp build?

These denials shouldn't be happening:
```
avc:  denied  { add } for service=vendor.qcom.PeripheralManager pid=656 uid=1000 scontext=u:r:per_mgr:s0 tcontext=u:object_r:per_mgr_service:s0 tclass=service_manager permissive=1
avc:  denied  { find } for service=vendor.qcom.PeripheralManager pid=704 uid=1000 scontext=u:r:per_proxy:s0 tcontext=u:object_r:per_mgr_service:s0 tclass=service_manager permissive=1
avc:  denied  { find } for service=vendor.qcom.PeripheralManager pid=764 uid=1000 scontext=u:r:wcnss_service:s0 tcontext=u:object_r:per_mgr_service:s0 tclass=service_manager permissive=1
```

We only define `thermal@1.0` in the manifest and add `thermal@1.0-impl` and `thermal@1.0-service` packages, so this is a bit odd to me, and I haven't seen this myself:
```
hwservicemanager getTransport: Cannot find entry android.hardware.bluetooth.a2dp@1.0::IBluetoothAudioOffload/default in either framework or device manifest.
hwservicemanager getTransport: Cannot find entry android.hardware.thermal@1.1::IThermal/default in either framework or device manifest.
```

**Comment by ix5** [comment] 2019-03-03 17:31
@stefanhh0 do you by any chance have any `PRODUCT_FULL_TREBLE` or `PRODUCT_ENFORCE_VINTF_MANIFEST_OVERRIDE` properties set?

**Comment by stefanhh0** [comment] 2019-03-03 19:04
@ix5 I don't know what GSI exactly is, I just do a aosp_g8441-userdebug build and flash the img files from `out/target/product/lilac`. After that I install magisk and opengapps via twrp, in case I have also flashed userdata.img, I also restore my backup via twrp. Thats basically it. Sometimes I start up a debian via proot inside my phone.

Regarding `PRODUCT_FULL_TREBLE` `PRODUCT_ENFORCE_VINTF_MANIFEST_OVERRIDE` I am not aware that I ever touched or changed such parameters... Where would I change it?

Did a search for it:
```
stefan@mars:~/android/source$ grep -rl PRODUCT_FULL_TREBLE *
build/make/core/config.mk
build/make/core/main.mk
build/make/target/product/emulator.mk
build/make/target/product/treble_common.mk
device/google/atv/products/treble_atv_common.mk
device/google/marlin/device-common.mk
system/sepolicy/tests/treble_sepolicy_tests.py
system/sepolicy/treble_sepolicy_tests_for_release.mk

stefan@mars:~/android/source$ grep -rl PRODUCT_ENFORCE_VINTF_MANIFEST_OVERRIDE *
stefan@mars:~/android/source$ 
```

**Comment by ix5** [comment] 2019-03-03 19:21
@stefanhh0 if you didn't touch anything it's fine. Let us worry about those denials from now, we'll see whether we can reproduce them.

Let's keep this issue about BT then.

Could it be another bad memory access @oshmoun ?
```
<3>[ 1817.849162] sps:bam 0x000000000c144000 0x0000000000000000(va);bam irq status=0x4.
<3>[ 1817.849162] sps: BAM_ERROR_IRQ
<6>[ 1817.849714] sps:bam 0x000000000c144000 0x0000000000000000(va) has 18 pipes.
<1>[ 1818.911905] Unable to handle kernel paging request at virtual address dead000000000208
<1>[ 1818.911985] pgd = ffffffe384984000
<1>[ 1818.912087] [dead000000000208] *pgd=00000000c4985003, *pud=00000000c4985003, *pmd=0000000000000000
<6>[ 1818.912347] ------------[ cut here ]------------
<2>[ 1818.912451] Kernel BUG at ffffff89a913220c [verbose debug info unavailable]
```

**Comment by stefanhh0** [comment] 2019-03-05 17:08
Meanwhile I've upgraded:
**Kernel version:** 4.9.160-gc3a9863a5575
**Android version:** android-9.0.0_r34
**OEM Image:** SW_binaries_for_Xperia_Android_9.0_2.3.2_v6_yoshino.img
**Build:** aosp_g8441-userdebug 9 PQ2A.190305.002 eng.stefan.20190305.084745
**Version baseband:** 1307-7511_47.1.A.16.20

On that version the bug is still there, probably not a surprise but I wanted to report.

From the "user" perspective it looks as follows:

When playing an ogg internet radio stream via "transistor" (a radio app from the fdroid app store) everything runs stable. 

However when playing local ogg music files via Vanilla Music Player it gets unstable (Listened to Stockhausens piano pieces... not that the music here is the problem ;-) - just a joke!). Got a freeze (no files available, had to powercycle) and a reboot (see attached file) in a relatively short amount of time.  

[pstore.tar.gz](https://github.com/sonyxperiadev/bug_tracker/files/2931927/pstore.tar.gz)

**Comment by stefanhh0** [comment] 2019-03-22 19:08
As mentioned in #196 with Kernel 4.9.162 the phone is stable for me when playing audio via BT. I'll continue testing using v7 this weekend and will report back.

Version infos:
**Kernel version:** 4.9.162-g7142c8274df5
**Android version:** android-9.0.0_r34
**OEM Image:** SW_binaries_for_Xperia_Android_9.0_2.3.2_v6_yoshino.img
**Build:** aosp_g8441-userdebug 9 PQ2A.190305.002 eng.stefan.20190320.064401
**Version baseband:** 1307-7511_47.1.A.16.20

**Comment by stefanhh0** [comment] 2019-03-23 07:15
**Platform:** Yoshino
**Device:** Lilac
**Kernel version:** 4.9.162-ge1ccab69b98e
**Android version:** android-9.0.0_r34
**OEM Image:** SW_binaries_for_Xperia_Android_9.0_2.3.2_v7_yoshino.img
**Build:** aosp_g8441-userdebug 9 PQ2A.190305.002 eng.stefan.20190322.182352
**Version baseband:** 1307-7511_47.1.A.16.20

**Description**
With a current build, I got 2 crashes/reboots while BT was active and playing something over a via BT connected speaker.
For the first crash I don't have more then the pstore contents, for the 2nd crash also a logcat output is available until logging stopped and the crash/reboot occurred.

**Pstore for 1st crash:** [pstore_1st.tar.gz](https://github.com/sonyxperiadev/bug_tracker/files/2999091/pstore_1st.tar.gz)
**Pstore for 2nd crash:** [pstore_2nd_07_16.tar.gz](https://github.com/sonyxperiadev/bug_tracker/files/2999092/pstore_2nd_07_16.tar.gz)
**Logcat for 2nd crash:** [logcat.log](https://github.com/sonyxperiadev/bug_tracker/files/2999093/logcat.log)

**Comment by stefanhh0** [comment] 2019-03-28 05:44
Although the BT disconnect problem seems to be fixed now, I got a phone crash / reboot with the very same build while playing a radio stream via a BT connected speaker. Unfortunately I did not collect the logs timely. I keep the ticket open and will add the updated infos of the latest crash when it happens again.

**Comment by jerpelea** [comment] 2019-03-28 06:34
the BT will be  updated in v8 to improve stability
Thanks for all the testing and logs

**Comment by jerpelea** [comment] 2019-04-18 13:29
@djselbeck 
v8 is released !
please rebuild and test

**Comment by stefanhh0** [comment] 2019-04-19 18:21
For me it is now a lot more stable. 
- Playing a radio stream over the internet via the transistor app for several hours did not trigger a single reboot yet. 
- Also playing music from the external sdcard over the vanilla music player app for more than an hour did not cause any reboots as before.

The phone was connected to an external speaker via BT. 
Uptime of the phone is currently > 18h

Additional I am going to test with my headphones via BT as with that it seemed to be sometimes more unstable especially when I was outside walking through the streets rather than being at home. I'll give an update on that later.

**Comment by stefanhh0** [comment] 2019-04-19 19:05
**Platform:** Yoshino
**Device:** Lilac
**Kernel version:** 4.9.168-g4ebcb68cc743
**Android version:** android-9.0.0_r35
**OEM Image:** SW_binaries_for_Xperia_Android_9.0_2.3.2_v8_yoshino.img
**Build:** aosp_g8441-userdebug 9 PQ2A.190405.003 eng.stefan.20190418.191851
**Version baseband:** 1307-7511_47.1.A.16.20

A reboot has just been triggered while playing music via the vanilla music app for more than 1h over BT.

I don't know though whether it was due to BT or if it was just one of the random reboots from #364.

When the phone crashed the vibrator was activated twice, which probably means double crash. If so the files in the pstore are then from the 2nd crash not from the original first crash, right? The dmesg output was taken after the double crash and the phone booted normally.

Uptime of the phone when the crash occurred was around 19h .

**Files**
[pstore.tar.gz](https://github.com/sonyxperiadev/bug_tracker/files/3099055/pstore.tar.gz)
[dmesg.log](https://github.com/sonyxperiadev/bug_tracker/files/3099056/dmesg.log)

**Comment by stefanhh0** [comment] 2019-04-24 20:20
**Platform:** Yoshino
**Device:** Lilac
**Kernel version:** 4.9.168-g72f952b6f2b5
**Android version:** android-9.0.0_r35
**OEM Image:** SW_binaries_for_Xperia_Android_9.0_2.3.2_v8_yoshino.img
**Build:** aosp_g8441-userdebug 9 PQ2A.190405.003 eng.stefan.20190423.201213
**Version baseband:** 1307-7511_47.1.A.16.20

Just an update, also with a more recent AOSP got a crash today while playing audio via BT, I think the vibrator was activated twice, but I am not 100% sure though unfortunately:
[pstore.tar.gz](https://github.com/sonyxperiadev/bug_tracker/files/3114004/pstore.tar.gz)

**Comment by stefanhh0** [comment] 2019-05-15 01:43
@djselbeck, @jerpelea 
This bug is open for quite a while, we still have crashes and reboots on yoshino (#399 and #403)

**Closed** 2019-05-20 10:26 UTC
