### ISSUE TITLE
[TAMA] Can't connect to PC by usb

### ISSUE THREAD

**Issue by Chiyoda0913** [sonyxperiadev/bug_tracker#531] opened 2020-02-02 03:00 UTC
**Platform:** TAMA
**Device:** Akari (H8296)
**Kernel version:** 4.14
**Android version:** 10.0
**Software binaries version:** 0.0.7.1_R1_V3A_TAMA

**Description**
Can't connect to pc by usb, no charge on mobile, and no device on pc. And it's same in the recovery.

**Comment by MartinX3** [comment] 2020-02-02 03:48
On which build datetime?
My h8296 build from 01. Feb 13:29 CET has a working usb.

**Comment by samduanx** [comment] 2020-02-19 15:52
Dear MartinX3, I have encountered this bug on a H8296 (Android 10, 4.14). The kernel was built on 14 Feb 20:32 CET.
Symptoms: USB does not connect, after reboot when pluging in again there is only less than a second of charging (LED orange) and then disconnect. Further attempts of connecting does not work either.
You are free to contact me if you need more information (seems hard to do dmesg since USB connection is normally mandatory).

**Comment by MartinX3** [comment] 2020-02-19 17:14
@samduanx could you try it with my build on XDA, too, since I never had this problem?
Since we have the same model we could locate the issue easier, then :)

**Comment by samduanx** [comment] 2020-02-19 23:20
@MartinX3 Yes sir, I have already using your XDA builds (both AOSP and LOS, latest version) and there is no sign of working.

**Comment by MartinX3** [comment] 2020-02-20 07:01
@samduanx
Can you confirm that it works on stock with the exact same computer, usb port and cable?
It sounds for me that the problem is either in the phone hardware, the usb cable, the usb port or the computer (maybe missing operatig system drivers, I use Linux to connect to my phone)

**Comment by samduanx** [comment] 2020-02-20 07:07
@MartinX3 Yes it works with the stock firmware (I actually flashed the stock firmware using newflasher   twice to confirm). The stock USB line did have a little contact issues but it worked flawlessly on Windows and Linux. My Windows laptop got all related drivers installed.

**Comment by MartinX3** [comment] 2020-02-20 07:45
@samduanx 
Now it becomes weird, since I own a H8296,too
(But I installed the central european stock firmware before)

Can you us a dmesg after you connect the phone with your computer?

And how did you flash stock and SODP if the connection didn't work? O.o

**Comment by samduanx** [comment] 2020-02-20 08:47
@MartinX3 
I have used adb via Wi-Fi and used dmesg | grep -i usb to get the following log file:
[dmesg_log.txt](https://github.com/sonyxperiadev/bug_tracker/files/4229678/dmesg_log.txt)
This was after plugging in the phone to the laptop.

The USB worked under fastboot and flash modes.

**Comment by MartinX3** [comment] 2020-02-20 09:44
@samduanx thank you :)

Oh and a last question
Does some weird entry appear in your windows device manager after you connected your phone or something like adb?

**Comment by samduanx** [comment] 2020-02-20 09:47
@MartinX3 No, nothing is shown in the device manager.

**Comment by MartinX3** [comment] 2020-02-20 14:12
@samduanx 
Hmm, does it work on linux? (Virtual Machine with USB passthrough or booted from a usb stick or installed on your machine)

**Comment by samduanx** [comment] 2020-02-20 14:19
@MartinX3 
No, I have got a Linux laptop (Arch, updated) and the phone doesn't want to connect still.

**Comment by MartinX3** [comment] 2020-02-20 15:36
Different OS, different cable, different Hardware (and usb port)

Hmmmm


Did you flash and boot stock 10 before ?

Now I can only think about a software bug, since fastboot works and the ADB problem is always the same.

**Comment by samduanx** [comment] 2020-02-20 23:58
I did booted stock 10 before, one without going through the first-time settings, and the other time did.
Also, the bug affects more than adb, you could not transfer files or even charge the phone.
This happed in both two ROMs, so I was firstly thinking of a kernel issue.

**Comment by samduanx** [comment] 2020-02-23 11:32
@MartinX3 I am happy to find my solution: Simply flash H8266's stock ROM first instead of H8296's. I think it is because of the probable difference between H8266 and H8296. Still thanks for your help!

**Comment by MartinX3** [comment] 2020-02-23 11:35
@samduanx 
That's indeed very weird.
You're welcome but please leave this ticket open and edit it to mention that it only happens with the H8296 stock firmware flashed before using SODP o.O
Or call the sony support immediately with a bug report.

**Comment by samduanx** [comment] 2020-02-23 11:42
Okay. I am currently creating a new issue regarding to this.

**Comment by samduanx** [comment] 2020-02-23 11:56
@MartinX3 
I have seen an issue from 2018 that Sony did not include config of H8296 first in SODP, but added after that (see issue #145). Did you add the config for it when building your ROM?

**Comment by MartinX3** [comment] 2020-02-23 12:03
@samduanx the H8296 device should work with a H8266 SODP ROM out of the box :)

**Comment by samduanx** [comment] 2020-02-23 12:04
@MartinX3 Got it.

**Comment by ix5** [comment] 2020-03-02 13:20
This issue should be closed in favour of https://github.com/sonyxperiadev/bug_tracker/issues/546 since the author here does not provide sufficient info.
@jerpelea

**Closed** 2020-03-02 13:22 UTC
Labels: bug
