### ISSUE TITLE
[AOSP11] SIM not detected at boot

### ISSUE THREAD

**Issue by llabadie** [sonyxperiadev/bug_tracker#765] opened 2022-03-29 08:09 UTC
**Platform:** Nile
**Device:** Pioneer
**Kernel version:** 4.14
**Android version:** 11 r36
**Software binaries version:** OEM Firmware v9 and SW Binaries 50.2.A.0.400

**Previously working on**
I am not able to say if it is new or not. I did test with OEM Firmware v7, v8 and v9 with the same result.

**Description**
When the phone boots sometimes the SIM card is not detected. 

**Symptoms**
I am not asked for a PIN code and there is no GSM icon, mobile data is greyed out.

**How to reproduce**
Reboot phone with working SIM card inside until it it not detected anymore. Sometimes it takes one reboot, sometimes 5 or 6.

**Additional context**
I tested with 2 different SIM cards from 2 different providers on 3 different devices.
The kernel was compiled with GCC to avoid camera bugs and you can find attached the commit for each repo.

[repostatus.txt](https://github.com/sonyxperiadev/bug_tracker/files/8369310/repostatus.txt)

**Comment by llabadie** [comment] 2022-03-29 08:28
An extract of the logs, the SIM is detected but some rules are not retrieved correctly :

``` 
03-29 09:52:15.731  2000  2106 I SecureElement-Terminal-SIM1: OnStateChange:true reason:Card has been detected
03-29 09:52:15.733  2000  2106 I SecureElement-AccessControlEnforcer: Allowed ACE mode: ara=true arf=true fullaccess=false
03-29 09:52:15.768  2000  2106 I SecureElement-AccessControlEnforcer: No ARA applet found in: SIM1
03-29 09:52:15.769  2000  2106 I SecureElement-PKCS15Handler: - Loading SIM1 rules...
03-29 09:52:15.807  2000  2106 I SecureElement-PKCS15Handler: Logical channels are used to access to PKC15
03-29 09:52:15.807  2000  2106 I ACE ARF EF_Dir: Analysing EF_DIR...
03-29 09:52:15.808  2000  2106 I SecureElement-AccessControlEnforcer: checkCommand() : Access = ALLOWED APDU Access = ALLOWED Reason = Unspecified
03-29 09:52:15.818  2000  2106 I SecureElement-Terminal-SIM1: Sent : 01a40004023f00
03-29 09:52:15.819  2000  2106 I SecureElement-Terminal-SIM1: Received : 6124
03-29 09:52:15.821  2000  2106 I SecureElement-Terminal-SIM1: Sent : 01c0000024
03-29 09:52:15.823  2000  2106 I SecureElement-Terminal-SIM1: Received : 62228202782183023f00a508800171830301d2008a01058b032f0602c6069001808301019000
03-29 09:52:15.824  2000  2106 I SecureElement-AccessControlEnforcer: checkCommand() : Access = ALLOWED APDU Access = ALLOWED Reason = Unspecified
03-29 09:52:15.854  2000  2106 I SecureElement-Terminal-SIM1: Sent : 01a40004022f00
03-29 09:52:15.854  2000  2106 I SecureElement-Terminal-SIM1: Received : 611c
03-29 09:52:15.857  2000  2106 I SecureElement-Terminal-SIM1: Sent : 01c000001c
03-29 09:52:15.858  2000  2106 I SecureElement-Terminal-SIM1: Received : 621a8205422100260283022f008a01058b032f06118002004c8801f09000
03-29 09:52:15.859  2000  2106 I SecureElementService ACE ARF: ReadRecord [1/38b]
03-29 09:52:15.860  2000  2106 I SecureElement-AccessControlEnforcer: checkCommand() : Access = ALLOWED APDU Access = ALLOWED Reason = Unspecified
03-29 09:52:15.887  2000  2106 I SecureElement-Terminal-SIM1: Sent : 01b2010426
03-29 09:52:15.889  2000  2106 I SecureElement-Terminal-SIM1: Received : 611e4f10a0000000871002ff33ff01890000010050045553494d51043f007ff0ffffffffffff9000
03-29 09:52:15.889  2000  2106 I SecureElementService ACE ARF: ReadRecord [2/38b]
03-29 09:52:15.890  2000  2106 I SecureElement-AccessControlEnforcer: checkCommand() : Access = ALLOWED APDU Access = ALLOWED Reason = Unspecified
03-29 09:52:15.899  2000  2106 I SecureElement-Terminal-SIM1: Sent : 01b2020426
03-29 09:52:15.900  2000  2106 I SecureElement-Terminal-SIM1: Received : ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff9000
03-29 09:52:15.901  2000  2106 E SecureElement-PKCS15Handler: SIM1 rules not correctly initialized! [Parser] Cannot retreive type
03-29 09:52:15.928  2000  2106 E SecureElement-AccessControlEnforcer: [Parser] Cannot retreive type
03-29 09:52:15.929  2000  2106 I SecureElement-AccessControlEnforcer: Deny any access to:SIM1
```

**Comment by voidanix** [comment] 2022-04-01 09:47
Have you checked that this is not a duplicate of #736? The symptoms sound like the same.

**Closed** 2022-08-11 08:53 UTC
Labels: bug
