### ISSUE TITLE
[pioneer] Device died after flashing FW

### ISSUE THREAD

**Issue by luk1337** [sonyxperiadev/bug_tracker#342] opened 2019-02-21 17:53 UTC
**Platform:** Nile
**Device:** Pioneer
**Kernel version:** Irrelevant
**Android version:** Irrelevant

**Description**
After flashing stock ROM with flashtool and forcing to boot to bootloader mode instead of letting it boot up normally device dies, blinking only green LED afterwards. Not sure if that's the exact way to reproduce this but this is what happened to me couple months ago.

**Symptoms**
Device is dead.

**How to reproduce**
1. Flash stock
2. After it's done flashing try to force boot to bootloader mode
3. Device should be dead (?)

**Comment by infixremix** [comment] 2019-02-21 20:56
Xa2 user here. When you mean dead ? You mean unrecoverable? Honestly shitting my self currently after reading this.

**Comment by luk1337** [comment] 2019-02-21 20:57
Yes. Last time I did that I just RMA'd my phone lol.

**Comment by infixremix** [comment] 2019-02-21 21:00
Okey doaky cheers for the reply 😂 Not had this issue yet. Just waiting .

**Comment by jerpelea** [comment] 2019-02-22 09:03
@luk1337 how did you flash your device and which SW version did you flash on the device?

**Comment by luk1337** [comment] 2019-02-22 10:53
>how did you flash your device?
Uh, I just flashed it b-but back then I was using unofficial flashtool. I was told to report it anyway even if I don't know if it's reproducible or if it happens with Sony's flashtool either.

>which SW version did you flash on the device?
Doesn't really matter as I flashed the same version few more times before bricking it.

**Comment by jerpelea** [comment] 2019-02-22 11:00
@luk1337 actually the SW version matters 
please check it if you can

**Comment by luk1337** [comment] 2019-02-22 11:05
uh it was few months ago so yeah I don't remember anymore.

**Comment by jerpelea** [comment] 2019-02-22 11:51
I will close this bug because we lack the information to reproduce it 
If this happens again please provide the SW version

**Closed by jerpelea** 2019-02-22 11:51 UTC

**Comment by infixremix** [comment] 2019-02-23 17:32
Confirmed. Many users are coming back to me telling me that is happening when people install stock after using aosp. Mixture off sw binaries. The most recent person that reported it was using January sw binaries and flashed stock rom version of 50.2.A.0.32 using Nile v5 software binaries.

**Comment by luk1337** [comment] 2019-02-23 18:18
@infixremix are you talking about "blinking green led" or "white vertical stripes on the display" kind of brick?

**Comment by infixremix** [comment] 2019-02-23 18:47
Had reports of both. The stripe one can be fixed by reverting to 8.0

**Comment by luk1337** [comment] 2019-02-23 18:49
rip then

**Comment by jerpelea** [comment] 2019-02-23 19:23
the strips are caused by a bug in the SW and the fix will be released soon. Please do not flash AOSP with an Android 9 bootloader.

**Comment by luk1337** [comment] 2019-02-23 19:25
uhh so speaking of that. Will there be a possibility to flash both slots with emma or have you tested dd-ing A firmware partitions to B on nile devices @jerpelea? I would try doing that myself but since I don't have a way to unbrick it I would feel safer if you said that it worked for you.

**Comment by jerpelea** [comment] 2019-02-23 19:30
Emma will always flash the a slot and set it bootable

**Comment by luk1337** [comment] 2019-02-23 19:30
uh, k. So how can I have same FW on both A and B?

**Comment by jerpelea** [comment] 2019-02-23 19:38
that should not be the case by default

**Comment by luk1337** [comment] 2019-02-23 19:39
That isn't an answer to my question.

**Comment by MartinX3** [comment] 2019-02-23 20:01
You need to switch the slot via fastboot.

Not pushing the same firmware on both slots exists for stability reasons.

**Comment by luk1337** [comment] 2019-02-23 20:03
So you mean that I'm supposed to forget about my B slot and using OTA on custom ROMs just cause they don't want me to do that?

**Comment by infixremix** [comment] 2019-02-23 20:07
Well what about full Hardbrick where there is a complete screen? Is the bootloader corrupt like it would be on most devices or is it recoverable

**Comment by luk1337** [comment] 2019-02-23 20:22
So a reminder: some time ago this was introduced https://developer.sony.com/posts/flash-tool-updated-with-new-feature/. It's pretty obvious that it's a feature for custom ROMs users and what not. Wouldn't it make sense for that feature to flash FW to both slots so that users don't have to stick to slot A and avoid OTA on custom ROMs?

**Comment by MartinX3** [comment] 2019-02-23 22:58
@luk1337 a custom rom ota update zip would copy the FW to the other slot, install the new firmware to the other slot and reboot k to the other slot. :)

But of course you can switch the slot via fastboot/TWRP and execute newflasher, flashtool or Emma. :)

**Comment by luk1337** [comment] 2019-02-23 23:01
>a custom rom ota update zip would copy the FW to the other slot,
No, it wouldn't do that. Have you looked at OTA on A/B devices? Also speaking of 'copying FW', I asked you @jerpelea if you tried that on nile devices cause i'm too scared to try it myself until someone else confirms it's safe.

>But of course you can switch the slot via fastboot/TWRP and execute newflasher, flashtool or Emma. :)
No you can't. Emma is ALWAYS flashing A. If emma was flashing $CURRENT_SLOT I wouldn't really be complaining, I would just tell users to flash their phone twice or something.

**Comment by MartinX3** [comment] 2019-02-23 23:06
Yes, I have the tama omnirom ota installer zip on my computer and the updater script does it, except the partitions which get installed by the custom rom of course.

Okay, except emma.
Why not using newflasher?

**Comment by luk1337** [comment] 2019-02-23 23:06
What? updater-script is dead on A/B. It's should be using payload.bin instead.

**Comment by luk1337** [comment] 2019-02-23 23:07
Are you sure that newflasher is flashing $CURRENT_SLOT?

**Comment by MartinX3** [comment] 2019-02-23 23:13
It worked on Apollo to flash B :)

As far as I remember my last flash correctly it used the current slot.

Or maybe try the ota script.
It runs through every partition and copy it to the other slot
Except the ones in the ignore list.
Boot, vbmeta, dtbo, system, vendor, oem (if you want). I hope I didn't forget one.
Or pm me and I send you the file after seeing the pm. :)

**Comment by luk1337** [comment] 2019-02-23 23:14
Ok i guess i'll try newflasher. I'll be really sad if this phone dies again.

**Comment by MartinX3** [comment] 2019-02-23 23:16
I would suggest to install a working firmware first to test the flashing. :)

**Comment by luk1337** [comment] 2019-02-23 23:17
Umm, I have working FW on both slots now cause I never flashed newer one.

**Comment by luk1337** [comment] 2019-02-23 23:17
I'm not going to flash P FW etc. I'm just going to flash newest O.

**Comment by MartinX3** [comment] 2019-02-23 23:19
Ah, I thought the Russian one I heard bricks from.

**Comment by luk1337** [comment] 2019-02-23 23:19
Yes, i'm not going to flash that one.

**Comment by luk1337** [comment] 2019-02-23 23:33
ok, newflasher worked. time to write a nice post in my thread ^.^

**Comment by MartinX3** [comment] 2019-02-23 23:35
Nice :)
Happy writing and happy happymaking of others :D

**Comment by luk1337** [comment] 2019-03-01 11:43
![image](https://user-images.githubusercontent.com/6830979/53636205-a74ced00-3c1f-11e9-974f-300e301ce2c8.png)
just sony things~

**Comment by MartinX3** [comment] 2019-03-01 11:55
I am starting to getting scared against flashing the next monthly stock firmware on my akari.

**Comment by luk1337** [comment] 2019-03-01 11:56
I think it's just nile devices that are unlucky.

**Comment by MartinX3** [comment] 2019-03-01 12:01
I hope so. (Okay, that may sounds impolite :P)

**Comment by jerpelea** [comment] 2019-03-01 12:23
why aren't you using the Emma flashtool ?

**Comment by luk1337** [comment] 2019-03-01 12:25
Not sure what this guy was trying to achieve but the reason why I'm not going to use Emma in foreseeable future is that Emma only flashes slot A and sets it active and I would prefer if it was either: "flashing $current_slot" or "flashing both slots".

**Comment by MartinX3** [comment] 2019-03-01 12:38
I am missing flashing of both slots and Linux support.

**Comment by luk1337** [comment] 2019-03-01 12:38
I mean, Emma is fine if you want to go back to stock but other than that I find it useless on A/B devices.
