### ISSUE TITLE
The Wifi keeps dropping and sim card signal

### ISSUE THREAD

**Issue by Tarrun1234** [sonyxperiadev/bug_tracker#602] opened 2020-06-18 12:40 UTC
**Platform:** Tama
**Device:** XZ2 Compact 
**Kernel version:** 4.14
**Android version:** 10
**Software binaries version:** v8

**Description**
This happens some times of the day 
like when i connect it to a pc

**Comment by MartinX3** [comment] 2020-06-18 12:59
Duplicate of https://github.com/sonyxperiadev/bug_tracker/issues/540 @Tarrun1234 ?

**Comment by MarijnS95** [comment] 2020-06-18 13:28
Also note that the bug report template is there to be **completely filled in**, not to be removed. Without it we can't do much but ignore the report.

**Comment by ix5** [comment] 2020-06-19 22:59
Please close this issue. It is a duplicate *and* also lacks required information.
Please respect the developers' time.

**Closed** 2020-06-20 04:39 UTC
Labels: bug
