### ISSUE TITLE
Akari not booting in android 12

### ISSUE THREAD

**Issue by AbelChT** [sonyxperiadev/bug_tracker#763] opened 2022-03-12 20:26 UTC
**Platform:** Tama
**Device:** Akari
**Kernel version:** 4.19
**Android version:** Android 12
**Software binaries version:** SW_binaries_for_Xperia_Android_12_4.19_v1c_tama.img

**Previously working on** Android 11
Has this always been a problem, or is it a new issue? New issue

**Description**
Write the issue description here.
The device (Akari h8216) doesn't boot after flashing Android 12 (compiled following the instructions in https://developer.sony.com/develop/open-devices/guides/aosp-build-instructions/build-aosp-android-12-0), it get stacked in the SONY logo (the SONY logo stays until the device is shutdown through adb reboot -p).
The device was previously working following the same instructions for Android 11.

**Symptoms**
Write the symptoms here.

**How to reproduce**
Write how to reproduce here.
For compiling have been used the latest commits in the moment this issue is reported.
local_manifests -> commit 6f842e1cee7b3603df2f9731e530d61353179e1b
device-sony-akari -> commit c171c88eeea28fcc1fc3b23b9a8decfeac80d659
device-sony-tama -> commit bf99d61d702c5e851a8598fd9142c6f5373d30fe
device-sony-common -> commit 3c17940d1a086ec520cfc5d2168da249b2d914db
common-kernel -> commit 2186796f617c5649941b277baa630413cf127308

**Additional context**
Add any other context, e.g. upload logs or screenshots about the bug here.

[logcat_exit.txt](https://github.com/sonyxperiadev/bug_tracker/files/8238347/logcat_exit.txt)

**Comment by faenil** [comment] 2022-04-01 21:26
probably duplicate of https://github.com/sonyxperiadev/bug_tracker/issues/748
building the most recent kernel source will fix it, however there are other major issues after that, e.g. https://github.com/sonyxperiadev/bug_tracker/issues/755

**Closed** 2022-08-14 19:24 UTC
Labels: bug
