### ISSUE TITLE
[Yoshino][Lilac] After booting, Phone keeps powering off/restarts to recovery (TWRP)

### ISSUE THREAD

**Issue by wyzco** [sonyxperiadev/bug_tracker#375] opened 2019-04-26 13:49 UTC
**Platform:** Yoshino 
**Device:** Lilac 
**Kernel version:** 4.9.168-g6bf0ef8bbdc4
**Android version:** android-9.0.0_r35
**OEM Image:** SW_binaries_for_Xperia_Android_9.0_2.3.2_v8_yoshino.img
**Build:** aosp_g8441-userdebug 9 PQ2A.190405.003
**Version baseband:** 1307-7511_47.1.A.16.20

**Description**
Phone powers-on, after entering pin and logging-in most widgets load.
The wifi connects sometimes, then the gsm signal drops then phone powers down/restarts and reboots in TWRP (Recovery).

**Symptoms**
Powering-off after booting up and logging-in
Here is a video of it also [https://1drv.ms/v/s!AkcSaiNvj4TZgshE3_yexG2uzfw6aQ](url)

**How to reproduce**

- Flashed G8441_Customized_NOBA_1311-0104_47.1.A.16.20_R22B via EMMA and booted once with sim inserted
- Flashed AOSP build created 24/04/2019
- fastboot flash boot boot.img
- fastboot flash recovery twrp-3.2.3-0-lilac-pie-2.img
- fastboot flash oem SW_binaries_for_Xperia_Android_9.0_2.3.2_v8_yoshino.img
- fastboot flash system system.img
- fastboot flash userdata userdata.img
- fastboot flash vendor vendor.img

Flashed Magisk and Gapps also.
I was able to grab this log before it powered-off after it booted.

**Files**
[logcat.log](https://github.com/sonyxperiadev/bug_tracker/files/3121580/logcat.log)

**Comment by stefanhh0** [comment] 2019-04-27 05:25
I can confirm that problem I am having the same issue as well now.

**Comment by stefanhh0** [comment] 2019-04-27 06:34
With pure AOSP (no restored aosp, no gapps and no Magisk) the behavior is a little different. The phone does not power done, however when entering the SIM PIN one gets "SIM PIN operation failed" several times.

The dmesg and logcat from those attempts: 
[dmesg.log](https://github.com/sonyxperiadev/bug_tracker/files/3123595/dmesg.log)
[logcat.log](https://github.com/sonyxperiadev/bug_tracker/files/3123587/logcat.log)

**Comment by stefanhh0** [comment] 2019-04-27 07:12
After upgrading from verson baseband 47.1.A.16.20 to 47.2.A.10.45 it is working again.

@jerpelea So for the time this bug is open we can't continue testing on 47.1.A.16.20 baseband version but have to switch to something newer (e.g. latest baseband version: 47.2.A.10.45)

**Comment by wyzco** [comment] 2019-04-27 09:13
Yea I switch baseband to 47.2.A.2.33...  all well so far.

**Comment by wyzco** [comment] 2019-04-27 22:56
I think I found what seems to be the problem/solution. The same issue happened on baseband 47.2.A.10.45 .
What i did that seem to stop the issue was 
- go to the testing menu by dialing *#*#info#*#*
- choose "Phone information"
- choose a for the item"Set preferred network type" choose a compatible option.

After doing that the cell stopped restarting as it seemed to be a network selection/comparability issue.
As I noticed the cell had no reception and had issue connecting to the network before it restarted.
Oddly even when I choose aeroplane mode this did not fix the issue so I am a bit uncertain if this is really a fix but it works fr now.

**Comment by wyzco** [comment] 2019-04-29 21:10
I was able to get some log, Yay! :-)
At 15:59:03:224 you can see where android.phone crashed too many times. then afterwards triggering a shutdown I suspect. It seems to be related to the network selection. I cannot access it fast enough before the cell shuts down though. I retrieved the logs before logging-in to the cell.
```
[ 04-29 15:59:03.224  1056: 2790 W/RescueParty ]
Noticed 1 events for UID 1001 in last 29 sec

[ 04-29 15:59:03.224  1056: 2790 W/ActivityManager ]
Process com.android.phone has crashed too many times: killing!

[ 04-29 15:59:03.225  2865: 2865 I/Process  ]
Sending signal. PID: 2865 SIG: 9

[ 04-29 15:59:03.254  1056: 1306 I/ActivityManager ]
Process com.android.phone (pid 2865) has died: pers PER 

[ 04-29 15:59:03.255   541:  541 I/ServiceManager ]
service 'iphonesubinfo' died


[ 04-29 15:59:03.255  1056: 1306 W/ActivityManager ]
Scheduling restart of crashed service com.android.phone/.TelephonyDebugService in 0ms

[ 04-29 15:59:03.256  1056: 1306 W/ActivityManager ]
Service crashed 16 times, stopping: ServiceRecord{167fae1 u0 com.sony.transmitpower/.service.TransmitPowerService}

[ 04-29 15:59:03.256   541:  541 I/ServiceManager ]
service 'isms' died


[ 04-29 15:59:03.256   617:  617 I/Zygote   ]
Process 2865 exited due to signal (9)

[ 04-29 15:59:03.256  1056: 1295 D/ConnectivityService ]
unregisterNetworkFactory for PhoneSwitcherNetworkRequstListener

[ 04-29 15:59:03.257  1056: 1295 D/ConnectivityService ]
unregisterNetworkFactory for TelephonyNetworkFactory[0]

[ 04-29 15:59:03.257   541:  541 I/ServiceManager ]
service 'phone' died


[ 04-29 15:59:03.257  1056: 1080 W/libprocessgroup ]
kill(-2865, 9) failed: No such process

[ 04-29 15:59:03.257  1056: 1080 I/libprocessgroup ]
Successfully killed process cgroup uid 1001 pid 2865 in 0ms

[ 04-29 15:59:03.259   541:  541 I/ServiceManager ]
service 'carrier_config' died


[ 04-29 15:59:03.260  1056: 1306 W/ActivityManager ]
Re-adding persistent process ProcessRecord{5be1a7b 2865:com.android.phone/1001}

[ 04-29 15:59:03.260   541:  541 I/ServiceManager ]
service 'simphonebook' died


[ 04-29 15:59:03.262   541:  541 I/ServiceManager ]
service 'isub' died


[ 04-29 15:59:03.282  1056: 1079 I/ActivityManager ]
Start proc 2919:com.android.phone/1001 for restart com.android.phone
````

[logging.log](https://github.com/sonyxperiadev/bug_tracker/files/3129177/logging.log)

**Comment by wyzco** [comment] 2019-04-29 22:10
Also did a bugreport from adb

had to zip the log as it was 25mb
the links are below.
zip les than a 1mb [https://1drv.ms/u/s!AkcSaiNvj4TZgshO79q1Lg4GXWrJNg](url)
text/log 25mb    [https://1drv.ms/u/s!AkcSaiNvj4TZgshPn_CTK0OaAsFdIA](url)

**Comment by stefanhh0** [comment] 2019-04-29 22:21
47.2.A.10.45 is as well not a that good alternative at the moment. With the baseband version of 47.2.A.10.45 the phone has a very high energy consumption and the accu gets down very rapidly.

It would be good if someone can have a look into it. For the lilac device this is really a pretty severe bug, that makes it difficult to continue using aosp at all.

@jerpelea Any chance that you or any other can have a look into it soon? That would be great.

I have tried today on a fresh version:
**Kernel version:** 4.9.168-g5d170cfaf6cd
**Android version:** android-9.0.0_r35
**OEM Image:** SW_binaries_for_Xperia_Android_9.0_2.3.2_v8_yoshino.img
**Build:** aosp_g8441-userdebug 9 PQ2A.190405.003 eng.stefan.20190429.194842
**Version baseband:** 1307-7511_47.1.A.16.20

The build contains all the changes that have been done on 29.04.2019 to the repos.

The AOSP just says "SIM PIN operation failed!" or if the first SIM PIN was entered successfully then a few seconds later it ask again for the SIM PIN. 
I guess as soon as this bug has been fixed, the shutdown problem will also be fixed (not 100% sure though)...

Here are some updated logs from pure AOSP when the problem occurred:
[logcat.log](https://github.com/sonyxperiadev/bug_tracker/files/3129369/logcat.log)
[dropbox.tar.gz](https://github.com/sonyxperiadev/bug_tracker/files/3129370/dropbox.tar.gz)
[dmesg.log](https://github.com/sonyxperiadev/bug_tracker/files/3129371/dmesg.log)

**How to reproduce**
- Flash G8441_Customized_NOBA_1311-0104_47.1.A.16.20_R22B
- Flash a current AOSP
- Entering the SIM PIN shows SIM PIN operation failed or it shows shortly after SIM PIN has been entered again the SIM PIN dialog

**Comment by stefanhh0** [comment] 2019-05-02 21:09
With a fresh build from the most recent changes:
**Kernel version:** 4.9.170-g96e6d64d2d0c
**Android version:** android-9.0.0_r35
**OEM Image:** SW_binaries_for_Xperia_Android_9.0_2.3.2_v8_yoshino.img
**Build:** aosp_g8441-userdebug 9 PQ2A.190405.003 eng.stefan.20190502.183239
**Version baseband:** 1307-7511_47.1.A.16.20

Additionally via TWRP-3.3.0:
- Install Magisk-v19.1
- Install open_gapps-arm64-9.0-pico-20190502 
- Restore twrp data backup 

The initial problem of the phone shutdown and reboot to recovery is no longer occurring so the issue can be closed from my point of view. However the "SIM PIN operation failed" message is still coming sometimes but that is not that critical for me.  

@wyzco is it working for you now as well?

Thanks to all for bringing the phone back with basic operation on the stable version-baseband.

**Comment by stefanhh0** [comment] 2019-05-02 22:13
Okay, that was a little to quick, now it is happening again...
Here an uptodate logcat:
[logcat.log](https://github.com/sonyxperiadev/bug_tracker/files/3140099/logcat.log)

Because of that I have to return to version-baseband: 47.2.A.2.33

**Comment by jerpelea** [comment] 2019-05-03 05:23
please flash 47.1.A.16.20 sw (not firmaware only)
boot the device with SIM
shutdown and flash a custom Rom
I tested Lilac over 7 days and I could not replicate the issue

**Comment by stefanhh0** [comment] 2019-05-04 04:52
I have just realized that there is a new firmware available in emma:
G8441_Customized_US_1310-4371_47.1.A.16.20_R8B version-baseband: 1308-8921_47.1.A.16.20
This time I have flashed the newcomer instead of the longtime available:
G8441_Customized_NOBA_1311-0104_47.1.A.16.20_R22B version-baseband: 1307-7511_47.1.A.16.20

Is the difference between those two relevant? At least the version-basebands are different. Any recommendations which one to use of those two?

I'll get back with my findings for version-baseband 1308-8921_47.1.A.16.20 as soon as I have flashed aosp as well.

**Comment by stefanhh0** [comment] 2019-05-04 06:28
On 1308-8921_47.1.A.16.20 it is no longer shutting down.

For 1307-7511_47.1.A.16.20 a workaround might be to wait some time after the SIM PIN dialog occurred until `SIM CARD IS LOCKED. - EMERGENCY CALLS ONLY` remains stable (takes up to a minute for me) - however I haven't tested that...

@wyzco can you confirm this?

**Comment by stefanhh0** [comment] 2019-05-04 07:16
With the restored twrp data backup, opengapps and magisk, I made following observations:
 
Even after `SIM CARD IS LOCKED. - EMERGENCY CALLS ONLY` was stable for more than a minute, after logging in the SIM card "disappeared" (State was no SIM card inserted). Shortly after that the phone did a shutdown again.

On two reboot attempts the phone did not shutdown but crashed and rebooted... I have attached the pstore contents from the latest crash. After the last crash and reboot the phone runs stable. However the SIM disappeared once and reappeared. I have recorded some logs. Additionally I found a few tombstones in `/data/tombstones` which I have attached and also added the dropbox from `/data/system/dropbox`

So we still have the problem and it seems to be related to #393, there the SIM card behavior is as well unstable, the good thing is, it should be reproducible for you @jerpelea in #393 since it happens on pure sony aosp without any modifications. 

All in all also on 1308-8921_47.1.A.16.20 the SIM card behavior is still very unstable and may cause phone crash or causes the phone to shutdown. Sometimes the phone "survives" the first minutes and seems then to stay up stable.

Here the recorded logs and files:
[before_enter_pin_bugreport-aosp_g8441-PQ2A.190405.003-2019-05-04-08-45-08.zip](https://github.com/sonyxperiadev/bug_tracker/files/3144088/before_enter_pin_bugreport-aosp_g8441-PQ2A.190405.003-2019-05-04-08-45-08.zip)
[after_successful_login_bugreport-aosp_g8441-PQ2A.190405.003-2019-05-04-08-47-46.zip](https://github.com/sonyxperiadev/bug_tracker/files/3144089/after_successful_login_bugreport-aosp_g8441-PQ2A.190405.003-2019-05-04-08-47-46.zip)
[after_simcard_disappeared_and_reappeared_bugreport-aosp_g8441-PQ2A.190405.003-2019-05-04-08-50-43.zip](https://github.com/sonyxperiadev/bug_tracker/files/3144090/after_simcard_disappeared_and_reappeared_bugreport-aosp_g8441-PQ2A.190405.003-2019-05-04-08-50-43.zip)
[pstore.tar.gz](https://github.com/sonyxperiadev/bug_tracker/files/3144091/pstore.tar.gz)
[tombstones.tar.gz](https://github.com/sonyxperiadev/bug_tracker/files/3144093/tombstones.tar.gz)
[dropbox.tar.gz](https://github.com/sonyxperiadev/bug_tracker/files/3144094/dropbox.tar.gz)

**Comment by stefanhh0** [comment] 2019-05-04 16:18
A good workaround to avoid the shutdown: Directly after boot, immediately enter the device pin before the sim pin dialog appears. Then wait around a minute. After that enter the SIM PIN.

**Comment by wyzco** [comment] 2019-05-04 16:24
Sim Pin is off for me only device pin.

> A good workaround to avoid the shutdown: Directly after boot, immediately enter the device pin before the sim pin dialog appears. Then wait around a minute. After that enter the SIM PIN.

**Comment by stefanhh0** [comment] 2019-05-05 04:58
Sim PIN can be (re-)activated via activating :  Settings -> Security & location -> Advanced -> SIM card lock -> Lock SIM card

**Comment by stefanhh0** [comment] 2019-05-14 04:03
The problem has been fixed with all the latest changes from you guys, thanks for all your hard work!

For reference the version infos with that it is working again as expected :
**Kernel version:** 4.9.174-gd7ab313501f1
**Android version:** android-9.0.0_r37
**OEM Image:** SW_binaries_for_Xperia_Android_9.0_2.3.2_v8_yoshino.img
**Build:** aosp_g8441-userdebug 9 PQ3A.190505.002 eng.stefan.20190514.014237
**Version baseband:** 1308-8921_47.1.A.16.20

@wyzco can you confirm?

**Closed** 2019-05-14 06:58 UTC
