### ISSUE TITLE
[Seine/ganges][kirin/pdx201] "ringback" tone during gsm call is not routed to handset (loud speaker works)

### ISSUE THREAD

**Issue by AngryGami** [sonyxperiadev/bug_tracker#683] opened 2021-03-15 08:45 UTC
**Platform**: Seine
**Device**: pdx201, kirin
**Kernel version**: 4.14 (be667ecc267b81)
**Android version**: 10
**Software binaries version**: SW_binaries_for_Xperia_Android_10.0.7.1_r1_v12b_seine.img, SW_binaries_for_Xperia_Android_10.0.7.1_r1_v12a_ganges.img 

**Description**
When making a regular gsm call and waiting for another party to answer there is no "ringback" tone in handset and when switch to loud speaker sound appears. When switching back to handset sound gone again.

**Comment by MarijnS95** [comment] 2021-03-16 21:25
@AngryGami How about sharing logs where we can clearly see when the call starts, when it is picked up on the other side, and what audio routes are picked during each step in the process - together with all the extra information spammed by the audio HAL etc?

I have been told that this issue does not appear on Android 11. That is strange, given the fact that there is no audio-related difference between Q and R device branches. We've migrated to a newer HAL tag recently (for Edo) but the default routes are unlikely to change. Not impossible, but unlikely.

Without logs I can't debug this quickly and easily,

**Comment by AngryGami** [comment] 2021-03-16 23:13
[noringtone.log](https://github.com/sonyxperiadev/bug_tracker/files/6152680/noringtone.log)
I've looked through it more carefully (after looking into code of audio_hw.cpp and other stuff) and it might be that problem in not in the routing because when speaker is disabled here what it prints into log:
```
12-08 13:19:17.529   638  2579 D audio_route: Apply path: voice-handset
```
I've tried to find to which channel/stream/path tone is generated to but couldn't understand how this works.
I've also found that `device/sony/seine/rootdir/vendor/etc/caf_common_primary_audio_policy_configuration.xml` file (which is copied into image as `common_primary_audio_policy_configuration.xml`) contains duplicated definitions for `voip_tx`:
``` xml
// line 131
        <mixPort name="voip_tx" role="sink"
                 flags="AUDIO_INPUT_FLAG_VOIP_TX">
            <profile name="" format="AUDIO_FORMAT_PCM_16_BIT"
                     samplingRates="8000,16000,32000,48000"
                     channelMasks="AUDIO_CHANNEL_IN_MONO"/>
        </mixPort>
...
//  line 144
        <mixPort name="voip_tx" role="sink"
                 flags="AUDIO_INPUT_FLAG_VOIP_TX">
            <profile name="" format="AUDIO_FORMAT_PCM_16_BIT"
                     samplingRates="8000,16000,32000,48000"
                     channelMasks="AUDIO_CHANNEL_IN_MONO"/>
        </mixPort>
// line 298
        <route type="mix" sink="voip_tx"
               sources="Built-In Mic,Built-In Back Mic,BT SCO Headset Mic"/>
// line 302
        <route type="mix" sink="voip_tx"
               sources="Built-In Mic,Built-In Back Mic,BT SCO Headset Mic"/>
```
these are unlikely anything important since they are identical, though I doubt this is intended.

**Comment by AngryGami** [comment] 2021-03-19 14:42
After thorough testing of this problem I have found that no ringback problem actually only appears on `kirin` device, i.e. `pdx201` works fine.  Logs above though are from `kirin` and therefore should still be relevant.
Problem with `pdx201` have slightly different nature - volume of sound that comes from speaker is way too low (in loud speaker mode). I assume this might have something to do with acdb data or maybe volume configuration in either `mixer_paths.xml` or `audio_policy_volumes.xml` file.

**Comment by ix5** [comment] 2021-03-30 20:12
Is this just a duplicate of https://github.com/sonyxperiadev/bug_tracker/issues/670 ?
You didn't provide the necessary logs there ("chatty" lines = useless for us), please close or add more info.

**Comment by ix5** [comment] 2021-03-30 20:51
If you're getting "chatty" messages, that means the service/app/whatever you're trying to observe is emitting so many messages in such a short time that `logcat` refuses to pick them up. Most often, it's repeated stuff.

But hidden in there might be relevant info. E.g. in the log from #670, there is no info at all that could help us since it's all being swallowed by chatty. https://github.com/sonyxperiadev/bug_tracker/issues/670#issuecomment-750462790

Either try to disable some log statements or patch logcat to raise/ignore limits.

**Comment by MarijnS95** [comment] 2021-03-30 21:03
> Most often, it's [...]

... starting `logcat` too late! While playing with such bugs it is _generally advised_ to start and pipe `logcat` _before_ performing the operation that reproduces a bug. There are ways around logs expiring, see the `logcat` help/manual.

**Comment by AngryGami** [comment] 2021-03-30 21:29
@ix5 That's news to me... the fact that logcat can swallow messages... Though... neither of messages I got within these logs are generated by something I control. Does that mean that in order to disable some log statements I have to change arbitrary parts of AOSP?
These "chatty" messages you are talking about - there are not a lot of them and almost all of them doesn't look relevant to the problem:
```
12-08 13:19:02.118  2787  4259 I chatty  : uid=10083(com.android.dialer) DialerExecutors expire 1 line
12-08 13:19:03.532  2787  2787 I chatty  : uid=10083(com.android.dialer) expire 12 lines
12-08 13:19:04.241  1989  1989 I chatty  : uid=1001(radio) com.android.phone expire 3 lines
12-08 13:19:04.246   660   735 I chatty  : uid=1041(audioserver) Binder:660_1 expire 2 lines
12-08 13:19:10.587  1248  3869 I WifiService: getWifiApEnabledState uid=1001
12-08 13:19:11.530   638  2579 I chatty  : uid=1041(audioserver) HwBinder:638_4 expire 108 lines
12-08 13:19:22.872  1248  1380 I chatty  : uid=1000(system) ActivityManager identical 1 line
```
The only thing that looks related and might have something interesting swallowed is in `HwBinder:638_4 expire 108 lines`, but this message is generated AFTER I enable speaker, and ringback tone actually works in loud speaker mode.

@MarijnS95 Attached log was taken during call and it covers entire period of that call when there no ringback tone at the start (via handset), then enabling speaker, then disabling it back and then ending call. What makes you think that there must be other info that is relevant to the problem outside of this period? I can make new log (after Easter though) from device boot through the test call. Though I'm afraid I will force you to "wade through my unrelated nose" :)

**Comment by MarijnS95** [comment] 2021-03-30 21:37
> there are not a lot of them and almost all of them doesn't look relevant to the problem:

We were of course referencing the comment in #670 where any grep for `audioserver` shows expired lines only. The lines are not relevant to the problem, they are however relevant to know that some (or in that case **all**) info is lost.

> @MarijnS95 Attached log was taken during call and it covers entire period of that call when there no ringback tone at the start

I haven't checked this log yet, don't worry - my reply was to #670 only.

**Comment by AngryGami** [comment] 2021-03-30 21:42
@MarijnS95 Sometimes I have to rely on other people collecting logs and don't have good control over that process. So, yes, #670 logs might had been quite crippled

**Comment by jerpelea** [comment] 2023-04-11 07:47
Discontinued Android version

**Closed by jerpelea** 2023-04-11 07:47 UTC
Labels: bug
