### ISSUE TITLE
Xperia XA2 - In-call audio from the device lost after some time on headphones

### ISSUE THREAD

**Issue by dimitar10** [sonyxperiadev/bug_tracker#128] opened 2018-05-11 08:58 UTC
**Platform:** Nile
**Device:** Pioneer H4113
**Kernel version:** 4.4.130-ge9dcd44 -dirty
**Android version:** 8.1.0r26
**Firmware version:** 8.1.6.4_r1_v12_nile

**Description**
While in a regular call on wired headphones, the in-call audio from the device is lost, while the audio in the other direction is fine.

**Symptoms**
 In-call audio from the device is lost after some time when using headphones.

**How to reproduce**
1. Plug in headphones
2. Make or receive a call

Outcome:  In-call audio from the device is lost after some time (average 5-10 seconds). 

**Logs**

Important timestamps:

13:33 – no audio from the very first second
13:34 – no audio after approximately 12 seconds

The archive contains both the logcat and the dmesg.

[audio-lost-on-headphones-20180510.tar.gz](https://github.com/sonyxperiadev/bug_tracker/files/1994623/audio-lost-on-headphones-20180510.tar.gz)

**Comment by jerpelea** [comment] 2018-05-15 21:43
the fix is merged and the DSP is initialized
https://github.com/sonyxperiadev/device-sony-common/commit/11833ba1d081dfb2a8175150ea7144f6b69d9a5d

next step is routing

**Comment by jerpelea** [comment] 2018-05-18 14:56
please check the status

**Comment by jerpelea** [comment] 2018-05-21 17:32
I can't replicate the issue after latest commits

**Comment by jerpelea** [comment] 2018-05-25 07:57
any updates on this one ?

**Comment by dimitar10** [comment] 2018-05-25 12:27
The issue **cannot be reproduced anymore on a H3113 device**, running a prebuilt 4.4.131-g67827af3 kernel, and firmware v12. I will double check on a H4113 dual-sim device as soon as possible, just to make sure, and update the issue accordingly.

**Comment by jerpelea** [comment] 2018-05-25 12:42
thanks

**Comment by dimitar10** [comment] 2018-05-26 10:42
The issue **cannot be reproduced anymore on H4113 devices** as well, running a prebuilt 4.4.131-g67827af3 kernel, and firmware v12, so I will mark it as closed.

**Comment by dimitar10** [comment] 2018-06-12 15:54
Platform: Nile
Device: Pioneer H4113
Kernel version: 4.4.133-g21d74dd
Android version: 8.1.0r26
Firmware version: 8.1.6.4_r1_v12_nile

More comprehensive testing revealed that audio routing on headphones still sometimes fails to work properly. 

Further description would be that when the headphones are plugged in, and there's an ongoing call, when the user wants to switch to speakerphone, the sound will route to the speakerphone and when the user switches back, the headphones won't have any audio.

**Logs**
[outgoing-headphones-after-speaker-11-18.tar.gz](https://github.com/sonyxperiadev/bug_tracker/files/2094764/outgoing-headphones-after-speaker-11-18.tar.gz)
[outgoing-headphones-from-start-10-38.tar.gz](https://github.com/sonyxperiadev/bug_tracker/files/2094765/outgoing-headphones-from-start-10-38.tar.gz)

The two logs attached to the message are related to:

1. headphones plug in and call
2. headphones plug in and call and routing to speaker

**Comment by richardtullberg** [comment] 2018-06-20 07:40
I wasnt able to reproduce it on discovery so I tried to do it on latest Pioneer and I can't reproduce it there either. The last time I tried I had a 40min call where I plugged in headphones and let that go for a long while, no issue, unplugged them, let it go for a long while no issue, plugged them in and turned on speaker phone etc.

1. Plug in Headphones -> Make voice call (No issues)
2. Un-plug headphones (No issues)
3. Plug in Headphones (No issues)
4. Turn on speaker phone with plugged in headphones (no issues)

repeated and faster and shorter intervals for about 40min where I checked both mic/speaker on receiver and transmitter.

I just can't reproduce it, there must be something more. Can you think of something that I am doing wrong?

**Comment by jerpelea** [comment] 2018-06-29 14:46
@dimitar10

**Comment by dimitar10** [comment] 2018-07-02 11:46
Tested with **android-8.1.0_r3**0 and **4.4.136-g6816b50-dirty** , and the issue is still present. Here are the dmesg and the logcat: 
[audio-lost-headphones-20180702.tar.gz](https://github.com/sonyxperiadev/bug_tracker/files/2155045/audio-lost-headphones-20180702.tar.gz)

**Closed** 2018-07-03 09:23 UTC
