### ISSUE TITLE
[tone],[yoshino] Device regularly reboots when instructed to shut down

### ISSUE THREAD

**Issue by ix5** [sonyxperiadev/bug_tracker#268] opened 2018-12-18 06:18 UTC
**Platform:** Tone
**Device:** Kagura
**Kernel version:** 4.9
**Android version:** 9

**Description**
Instead of cleanly powering off when instructed to do so, the device reboots. This only happens maybe every 3 out of 5 times.

**Symptoms**
After a reboot happens, the pstore folder is filled with `pmsg-ramoops`, `dmesg-ramoops` and `console-ramoops` files. I suspect a kernel panic is the culprit. See the attached logs.

Of particular interest:

`console-ramoops:`
```
[ 1650.966623] <CORE> smem:mpss glink_open: Error 0 - unable to find transport
[ 1650.966695] <LBSRV> smem:mpss:LOOPBACK_CTL_APSS glink_lbsrv_open_worker: unable to open channel
[ 1650.969151] <SSR> glink_ssr_notify_rx: Missing do_cleanup data!
[ 1651.033755] QSEECOM: qseecom_unload_app: App id 131074 now unloaded
[ 1651.075310] IPC_RTR: do_read_data: No local port id 0000008b
[ 1651.075392] IPC_RTR: do_read_data: No local port id 0000008b
[ 1651.144851] IPC_RTR: do_read_data: No local port id 0000008b
[ 1652.000195] <SSR> notify_for_subsystem: Subsystem lpass failed to respond. Restarting.
[ 1652.000413] <SSR> notify_for_subsystem: Subsystem rpm failed to respond. Restarting.
[ 1652.000512] Kernel panic - not syncing: notify_for_subsystem: RPM failed to respond!
```
And
```
[ 1653.463121] ipa ipa2_active_clients_panic_notifier:309 
[ 1653.463121] ---- Active Clients Table ----
[ 1653.463121] Q6                                       1   SPECIAL
[ 1653.463121] 
[ 1653.463121] Total active clients count: 1
[ 1653.463549] Kernel Offset: disabled
[ 1653.463643] Memory Limit: none
[ 1653.498294] Rebooting in 5 seconds..
[ 1658.499418] SMP: stopping secondary CPUs
[ 1658.499537] Going down for restart now
[ 1658.500296] qcom,qpnp-power-on 400f000.qcom,spmi:pmi8994@2:qcom,power-on@800: PMIC@SID2: configuring PON for reset
[ 1658.501029] msm_restart_prepare : cmd is NULL, set to reboot mode
```
`dmesg:`
```
<14>[ 1651.428621] init: Untracked pid 1373 received signal 15
```

**How to reproduce**
Select "Power off" in the UI or issue a reboot command via adb. Happens with a cable connected and without.

**Attachments:**
[console-ramoops.txt](https://github.com/sonyxperiadev/bug_tracker/files/2689105/console-ramoops.txt)
[dmesg-ramoops-0.txt](https://github.com/sonyxperiadev/bug_tracker/files/2689106/dmesg-ramoops-0.txt)
[pmsg-ramoops-0.txt](https://github.com/sonyxperiadev/bug_tracker/files/2689107/pmsg-ramoops-0.txt)

**Comment by ix5** [comment] 2019-01-05 14:36
### Analysis

```
[  144.004660] ipa-wan __ipa_wwan_close:1026 [rmnet_ipa0]: ipa2_deregister_intf failed -22
...
[  144.588216] <SSR> glink_ssr_notify_rx: Missing do_cleanup data!
...
[  145.595534] <SSR> notify_for_subsystem: Subsystem lpass failed to respond. Restarting.
[  145.595926] <SSR> notify_for_subsystem: Subsystem dsps failed to respond. Restarting.
[  145.596421] <SSR> notify_for_subsystem: Subsystem rpm failed to respond. Restarting.
...
[  145.596624] Kernel panic - not syncing: notify_for_subsystem: RPM failed to respond!
```

`<SSR>` comes from drivers/soc/qcom/glink_ssr.c

rpm = Qualcomm's resource power manager

see Documentation/devicetree/bindings/soc/qcom/qcom,smd-rpm.txt

[drivers/soc/qcom/glink_ssr.c](https://github.com/sonyxperiadev/kernel/blob/801fa748d4fd43196012840dfe875ba96ffd06cb/drivers/soc/qcom/glink_ssr.c#L254) (abbreviated)
```
void glink_ssr_notify_rx(void *handle, const void *priv, const void *pkt_priv,
		const void *ptr, size_t size)
{
	struct do_cleanup_msg *do_cleanup_data =
				(struct do_cleanup_msg *)pkt_priv;

    /* @pkt_priv: Private packet data
    *  -> if no pkt_priv is received, shenagigans... */
	if (unlikely(!do_cleanup_data)) {
		GLINK_SSR_ERR("<SSR> %s: Missing do_cleanup data!\n", __func__);
		goto no_clean_done;
	}
no_clean_done:
	rx_done_work->ptr = ptr;
	rx_done_work->handle = handle;
	INIT_WORK(&rx_done_work->work, rx_done_cb_worker);
	queue_work(glink_ssr_wq, &rx_done_work->work);
	wake_up(&waitqueue);
	return;
}

int notify_for_subsystem(struct subsys_info *ss_info)
{
	list_for_each_entry(ss_leaf_entry, &ss_info->notify_list,
			notify_list_node) {
        if (!wait_ret && !IS_ERR_OR_NULL(ss_leaf_entry->cb_data)
                && !ss_leaf_entry->cb_data->responded) {
            GLINK_SSR_ERR("%s %s: Subsystem %s %s\n",
                "<SSR>", __func__, ss_leaf_entry->edge,
                "failed to respond. Restarting.");
            notifications_successful = false;
            /* Check for RPM, as it can't be restarted */
	    //
	    // PANIC HERE!!!!!!!
	    //
            if (!strcmp(ss_leaf_entry->ssr_name, "rpm"))
                panic("%s: RPM failed to respond!\n", __func__);
```

So it seems that the subsystems get shut down too early in the poweroff sequence, and since rtm_storage is deemed critical, misguided attempts to revive it cause a kernel panic.

**But**:  It also seems [each subsystem is notified when a kernel panic is already happening](https://github.com/sonyxperiadev/kernel/blob/801fa748d4fd43196012840dfe875ba96ffd06cb/drivers/soc/qcom/subsystem_restart.c#L1877-L1907).
So I am unsure about the sequence of events: Is `notify_for_subsystem()` called in the context of a regular interval probe, or is it called by `glink_ssr_restart_notifier_cb()`, which is a callback registered to the kernel's `panic_notifier_list`?

**Comment by russel5** [comment] 2019-01-28 08:35
We have same problem on lilac. When choose shutdown, phone off, wait some time, then leds blink green - blue light and phone boot up. After this phone reboots by itself and make it very often.

**Comment by jerpelea** [comment] 2019-02-06 14:29
the bug appears to be fixed

**Comment by jerpelea** [comment] 2019-02-06 14:41
@ix5 please test on a clean build

**Comment by ix5** [comment] 2019-02-06 16:51
So far, I've tried powering off about ten times and no panics.
Closing this for now, will reopen if @russel5 can produce it again.

**Comment by ix5** [comment] 2019-02-06 21:04
I'm sorry to say, but I've just encountered it again with a fresh build from yesterday. Symptoms are the same.
[dmesg-ramoops-0.txt](https://github.com/sonyxperiadev/bug_tracker/files/2838228/dmesg-ramoops-0.txt)

**Comment by stefanhh0** [comment] 2019-02-07 20:59
yoshino / lilac is also affected again, same behavior on a fresh clean build done today (kernel: 4.9.154-ge17b3925fe2a-dirty)

[dmesg-ramoops-0.txt](https://github.com/sonyxperiadev/bug_tracker/files/2842643/dmesg-ramoops-0.txt)

**Comment by russel5** [comment] 2019-02-08 08:12
Today i'm even can't setup my phone after clean install, it just freeze then reboot.

**Comment by stefanhh0** [comment] 2019-02-08 09:19
@russel5 are you using  a different setting in "Extended Settings" -> "Display white point calibration" than 6000K? If so https://github.com/sonyxperiadev/bug_tracker/issues/317#issuecomment-459884477 may help.

**Comment by russel5** [comment] 2019-02-08 09:22
@stefanhh0 nope, as im say fresh, clean build, wipe all on phone and clean install.
Turn phone on start setup wizard (with gapps) and phone freeze and reboot.

**Comment by stefanhh0** [comment] 2019-02-08 10:31
What is `fastboot getvar version-baseband` saying? It should be `47.2.A.2.33` on yoshino/lilac. On which kernel-version are you?

**Comment by russel5** [comment] 2019-02-08 10:44
> It should be `47.2.A.2.33` on yoshino/lilac.
Who told that? Im having 47.2.a.6.30
> On which kernel-version are you?
How do you think if im using clean build what version? 4.9.154

**Comment by stefanhh0** [comment] 2019-02-08 11:14
> > It should be `47.2.A.2.33` on yoshino/lilac.
> 
> Who told that? Im having 47.2.a.6.30

47.2.a.6.30 is even newer then what was available in Emma 2days ago... 
https://github.com/sonyxperiadev/bug_tracker/issues/270#issuecomment-461055678

> > On which kernel-version are you?
> 
> How do you think if im using clean build what version? 4.9.154

I just want to make sure that we are on the same version... So are you are on: 4.9.154-ge17b3925fe2a, right?

Another difference is, that I don't include gapps in my build. You could try it without gapps included to see if that makes a difference.

Also adb logcat and after the reboot the contents of /sys/fs/pstore could be helpful.

**Comment by russel5** [comment] 2019-02-08 11:21
Why I'm need used firmware without gapps? And im not used that firmware because it's not usable, always reboots by itself. Im just see what new and try it when something changes in kernel sources

**Comment by ix5** [comment] 2019-02-08 11:29
> @stefanhh0 nope, as im say fresh, clean build, wipe all on phone and clean install.
> Turn phone on start setup wizard (with gapps) and phone freeze and reboot.

I think you may have posted in the wrong bug thread, did you mean to use https://github.com/sonyxperiadev/bug_tracker/issues/270 ?
This bug is only related to kernel panics **on shutdown.**

**Comment by russel5** [comment] 2019-02-08 11:32
On lilac we have same problem. Phone not shutdown, boots up after some time and then always reboots by itself. Im post about it already upper ^^

**Comment by ix5** [comment] 2019-02-08 11:43
> Turn phone on start setup wizard (with gapps) and phone freeze and reboot.

That is a completely different issue. Please open a different bug for that.
This bug is only about panics on shutdown.

> On lilac we have same problem. Phone not shutdown, boots up after some time and then always reboots by itself.

I've changed the title to reflect that yoshino is also affected.

**Comment by russel5** [comment] 2019-02-08 18:18
Here my files from /sys/fs/pstore
After shutdown phone boots up
[here](https://drive.google.com/open?id=1pkup1dBhllnXpQCCdS-_CYETAhWamNIt)

**Comment by stefanhh0** [comment] 2019-02-10 18:05
Some more details for yoshino/lilac: 

1. To reproduce the reboot after shutdown it is required that "USB-Debugging" is activated and the phone is connected via USB.
2. If shutting down the phone while being connected to the USB and "USB-Debugging" is deactivated then the phone shuts down and restarts into flash-mode (green-led). I assume that is wrong and it should show the battery loading screen instead.
3. If the phone is not connected to the USB then the shutdown works as expected.

**Comment by jerpelea** [comment] 2019-02-12 11:38
@stefanhh0 that is expected behavior

The fix will be released in vendor v6

**Closed by jerpelea** 2019-02-12 11:38 UTC

**Comment by russel5** [comment] 2019-02-23 15:26
@jerpelea now we need to wait another month for new oem?

**Comment by jerpelea** [comment] 2019-02-23 19:24
v6 was released

**Comment by russel5** [comment] 2019-02-23 21:13
@jerpelea yes, but issue not solved and added more like sound...

**Comment by jerpelea** [comment] 2019-02-24 06:16
@russek what do you mean?
