### ISSUE TITLE
[Yoshino][Lilac] Android 10 Kernel 4.9 reproducible crash shortly after login/startup

### ISSUE THREAD

**Issue by stefanhh0** [sonyxperiadev/bug_tracker#502] opened 2019-12-04 07:05 UTC
**Platform:** Yoshino
**Device:** Lilac
**Kernel version:** 4.9.194-gf6e8610eb617
**Android version:** android-10.0.0_r10
**Software binaries version:** SW_binaries_for_Xperia_Android_9.0_2.3.2_v9_yoshino.img
**Version baseband:** 1308-8921_47.1.A.16.20
**Build:** aosp_g8441-userdebug 10 QP1A.191105.003 eng.stefan.20191203.234941

**Description**
With the latest changes that have been integrated past 01.12.2019 android system is pretty unstable. I reverted back to my build from 01.12.2019.

**Symptoms**
System starts, PIN dialog appears, after entering SIM PIN and System PIN, then keeping the phone busy with swyping, opening apps and so on, after a short amount of time (less than a minute) system freezes and reboots  

**Additional context**
Logcat until system freezes: [logcat.log](https://github.com/sonyxperiadev/bug_tracker/files/3920423/logcat.log)
After rebooting found following files in /sys/fs/pstore:
[pmsg-ramoops-0.log](https://github.com/sonyxperiadev/bug_tracker/files/3920448/pmsg-ramoops-0.log)
[console-ramoops-0.log](https://github.com/sonyxperiadev/bug_tracker/files/3920449/console-ramoops-0.log)
Used build-script : https://github.com/stefanhh0/aosp-10/blob/master/build-4.9.sh

**Comment by MarijnS95** [comment] 2019-12-04 14:31
Keep in mind that Android 10 on kernel 4.14 is not a supported _nor maintained_ configuration. We are getting closer to having 4.14 running on all platforms (it is currently running "perfect" on Tama, as daily driver), and there will be more and more commits spread across many repos to revert.

Anyway, the logs don't indicate any crash reason, but I stumbled by accident across the only log line showing FPC gestures. It has _finally_ been merged, but so far no-one has been willing to test the feature on Yoshino.
Now we discussed this point before where your device was also unstable, and [my recommendation to not pull all my PRs](https://github.com/sonyxperiadev/bug_tracker/issues/456#issuecomment-533862733) but just the single one necessary for Android 10 + k4.9 compatbility [fixed the issue](https://github.com/sonyxperiadev/bug_tracker/issues/456#issuecomment-534253025). There's a significant chance that Yoshino is in the same boat as Tone when it comes to these gestures, so please revert [that PR](https://github.com/sonyxperiadev/vendor-sony-oss-fingerprint/pull/50) and confirm whether this is the root cause.

**Comment by stefanhh0** [comment] 2019-12-04 15:53
Reverting it via:
```
pushd vendor/oss/fingerprint
    # Merge pull request #50 from MarijnS95/swipe-gestures
    git revert --no-edit -m 1 e8602743dead6296028c70e6d679731b53124053
popd
```
and will let you know if that changes the behavior.

**Comment by jerpelea** [comment] 2019-12-04 23:16
this combination is not supported officially

**Closed by jerpelea** 2019-12-04 23:16 UTC
Labels: bug

**Comment by stefanhh0** [comment] 2019-12-05 07:27
Flashed the phone without the pr50 and it is now stable again. Do you want me to provide any more files from the stable and/or unstable version? Is the PR independent from the kernel-version, or is it expected that with k4.14 it will then work?

**Comment by MarijnS95** [comment] 2019-12-05 08:23
Thanks for confirming, finally someone managed to test this on Yoshino after the PR has been open for six (!!) months. This platform is in the same boat as Tone, and since I don't have either there's nothing I can do about it (and even if I had one, the issue seems to lie too deep and behind signed blobs).

I'll submit the necessary PRs to disabled the feature in the FPC HAL, and remove the option from the gesture settings. The PR in Yoshino is the only other one to revert; there are no other changes. It works fine on k4.14 on other platforms, and the issue seems to be in the TZ-app itself. Which might be why so far Sony has never enabled this feature on any of their phones despite the sensor supporting it.

**Comment by stefanhh0** [comment] 2019-12-05 08:48
Thanks for explaining it and good that you've identified it so quickly.
