### ISSUE TITLE
[maple] Cameras crop and rotate photos when used in portrait mode

### ISSUE THREAD

**Issue by dimitar10** [sonyxperiadev/bug_tracker#38] opened 2017-11-14 14:47 UTC
**Platform:** yoshino
**Device:** maple
**Kernel version:** 4.4 (4cefd8e, built on Nov 14)
**Android version:** 7.1.1
**Firmware version:** v05

**Description**
Both of the device's cameras, when used in portrait orientation, rotate the resulting photo and crop it to a square.

**Symptoms**
 

**How to reproduce**
1. Launch Camera application
2. Make sure that the device is in portrait orientation
3. Take a photo with either the main or the front camera

**Logs**
N/A

**Comment by jerpelea** [comment] 2017-11-15 08:07
bug is not prezent in Android 8.0

**Comment by jerpelea** [comment] 2017-11-15 10:50
confirmed on Android 7.1 on all Yoshino devices when AOSP camera app is used

as an workaround you can use the opencamera aplication https://opencamera.sourceforge.io/

since the  bug is fixed in Android 8 we should check for the fix and backport it

**Comment by jerpelea** [comment] 2017-11-16 09:04
https://android.googlesource.com/platform/packages/apps/Camera2/+/8b17de0f4321fd981da98c64ad8a379ed6c0432a
should fix the issue

**Comment by jerpelea** [comment] 2017-12-01 12:25
https://github.com/sonyxperiadev/device-sony-yoshino/commit/f8b2c9289414a59cad8fda27b85dabf1e35203e4

**Comment by jerpelea** [comment] 2017-12-01 12:25
fixed

**Closed by jerpelea** 2017-12-01 12:25 UTC
