### ISSUE TITLE
[LENA][11][4.19] Screen randomly goes darker when adjusting at high brightness

### ISSUE THREAD

**Issue by sledges** [sonyxperiadev/bug_tracker#764] opened 2022-03-23 16:02 UTC
**Platform:** lena
**Device:** pdx213 xqbt52 (Xperia 10 III)
**Kernel version:** 4.19.188-gadf298fa3900
**Android version:** AOSP11 android-11.0.0_r46
**Software binaries version:** SW_binaries_for_Xperia_Android_11_4.19_v9a_lena.img

**Previously working on** stock Sony Android 62.0.A.3.70 (also when reflashed via Emma to 62.0.A.3.109).

**Description**
When adjusting brightness around 70-85% mark in small increments, screen randomly goes dim, instead of desired luminosity.

**Symptoms**
Display brightness is not corresponding to the slider value for certain levels of intensity.

**How to reproduce**

1. Uncheck Settings > Display > Adaptive brightness
1. Pull down top menu twice
1. Adjust brightness slider around 70-85% in small increments

**Additional context**
Logs only contain the following, which is normal whenever brightness is being adjusted:
```
01-19 18:24:07.098  1162  1357 V DisplayPowerController: Brightness [0.008951676] reason changing to: 'temporary', previous reason: 'manual'.
01-19 18:24:07.159  1162  1357 V DisplayPowerController: Brightness [0.033278756] reason changing to: 'manual', previous reason: 'temporary'.
```

**Comment by sledges** [comment] 2022-04-05 08:09
There is sort-of a dual-range for the brightness, but AOSP's slider just goes through the whole range instead. See for yourself (one lena):

`echo $VALUE > /sys/devices/platform/soc/ae00000.qcom,mdss_mdp/backlight/panel0-backlight/brightness`

Observable display brightness goes from ~5% to ~85% of max brightness for VALUEs from 1 to 3071 (0 is an invalid value).

And then it goes from 0% (pitch black) to 100% brightness for VALUEs from 3072 to 4095 (max_brightness).

**Comment by sledges** [comment] 2022-04-05 08:32
3072 is 3*1024, and there is regularity when testing with 256 increments, so there are certainly some bit-wise modes in play.

**Comment by MarijnS95** [comment] 2022-04-05 08:35
Perhaps the kernel driver "borrowed" the flawed (now fixed, though!) "look I can do much bitwise magic" from our `liblights` HAL at some point?

**Comment by sledges** [comment] 2022-04-06 14:57
Would you be able to point us for any info on what brightness modes the two most-significant bits might set?
Might it be somewhere in the history of https://github.com/sonyxperiadev/device-sony-common/tree/master/hardware/liblights

**Comment by MarijnS95** [comment] 2022-04-06 15:06
@sledges FWIW it was just a joke, because we had some funky wrong logic in there to convert an 8-bit "brightness" value to a 10-bit one, which would fill the least significant 2 bits instead of plainly left-shifting and never reaching max value (`255<<2 = 1020` instead of the max of `1023`).

As you confirmed with your test-case above this has nothing to do with `liblights`, it's somewhere in the kernel as the problem appears on the `sys` interface directly.

In this case I assume this to be a misconfiguration in the MDP driver/DT. You said 3071 is fine - which conveniently fills all bytes in `(1 << 10) - 1`, but `3072` rolls over and doesn't fill any. Surprisingly I'd have expected the exact same to happen at `1<<11=2048`.

**Comment by sledges** [comment] 2022-04-06 15:33
> @sledges FWIW it was just a joke

lol and I thought it was some legacy LEDs userspace lib, i.e. lights, which later transpired into kernel:)

> it's somewhere in the kernel as the problem appears on the `sys` interface directly. (In other words, I don't think - and hope not! - that there is extra meaning to bytes in the `brightness` attribute, it should just be in the range of `0 - max_brightness` and otherwise return `-EINVAL`).

It gets progresivelly brighter by setting at 1024 increments. So the whole range is split into intervals that are 1..1023 (pitch black..~85%), 1024..2048 (pitch black again..~90%), ..., 3072-4095 (pitch black..~100%).
All that can be seen via adjusting slider or from cmdline.
All this points to high bits having extra (sunshine, amplification?) brightness mode, the likes of which I vaguely but do recall on other manufacturers too.

Setting anything higher than max_brightness sets screen to max_brightness.

> Can you provide the value of `/sys/devices/platform/soc/ae00000.qcom,mdss_mdp/backlight/panel0-backlight/brightness`? It can really be anything because Lena is OLED and performs brightness scaling not by voltage of backlight/WLED 😬

It returns the same value it's echoed to, as in https://github.com/sonyxperiadev/bug_tracker/issues/764#issuecomment-1088399033

**Comment by MarijnS95** [comment] 2022-04-06 15:40
> It returns the same value it's echoed to, as in [#764 (comment)](https://github.com/sonyxperiadev/bug_tracker/issues/764#issuecomment-1088399033)

Oh I forgot to edit the path, should be `cat ..../max_brightness`. 

Glad to hear it also happens on `1024..`, confirms it's just the DT/driver being wrong/stupid about the width here.

**Comment by MarijnS95** [comment] 2022-04-08 08:10
Risking stating the obvious, this is where you'll want to look:

https://github.com/sonyxperiadev/kernel/blob/adf298fa39001c65ade069effc3682b8da746412/arch/arm64/boot/dts/qcom/lagoon-qrd.dtsi#L141-L144

It looks like the panel was configured to send brightness - indeed in range `(0, 4096)` (or `[1, 4095]` as it were :grimacing:) - through DCS commands, but somewhere the higher two bits either get lost or cannot be interpreted by the panel.

**Comment by MarijnS95** [comment] 2022-04-08 08:16
FWIW I'm scared for `panel->bl_config.bl_scale = MAX_BL_SCALE_LEVEL;`, this is always hardcoded to 1024:

https://github.com/sonyxperiadev/kernel-techpack-display-driver/blob/f123ea13f259e65c7ac0410dd452e40ed582c0f9/msm/dsi/dsi_panel.c#L2580

**Comment by Thaodan** [comment] 2022-04-13 09:01
> EDIT: It's exposed as a `bl_scale` DRM property, this looks like the typical additional magic logic moved into the display/composer HAL. though it's only used as multiplier in `dsi_display_set_backlight()` and I haven't seen any broken truncation yet, so it **should** not have an effect.

You mean there's additional logic to workaround this in HAL?

**Comment by MarijnS95** [comment] 2022-04-13 09:17
> > EDIT: It's exposed as a `bl_scale` DRM property, this looks like the typical additional magic logic moved into the display/composer HAL. though it's only used as multiplier in `dsi_display_set_backlight()` and I haven't seen any broken truncation yet, so it **should** not have an effect.
> 
> You mean there's additional logic to workaround this in HAL?

Repeat from quote part:

> so it **should** not have an effect.

It seems like a red herring. Better follow along the codepath in `dsi_panel_set_backlight`: https://github.com/sonyxperiadev/kernel-techpack-display-driver/blob/f123ea13f259e65c7ac0410dd452e40ed582c0f9/msm/dsi/dsi_panel.c#L870-L894. Add a couple prints and figure out if any truncation is of bits >=12 going on, repeat that process down into `dsi_panel_update_backlight` / `mipi_dsi_dcs_set_display_brightness`.

Perhaps it turns out that stock copylefts override the `4095` maximum in https://github.com/sonyxperiadev/kernel/blob/adf298fa39001c65ade069effc3682b8da746412/arch/arm64/boot/dts/qcom/lagoon-qrd.dtsi#L141-L144 with `1023` again, if it turns out this truncation happens on the panel side.

**Comment by sledges** [comment] 2022-04-20 14:26
Thanks to you for pointing in the right direction, the PR is now available ^

**Comment by MarijnS95** [comment] 2022-04-20 15:03
@sledges I had never expected such an utter terrible hack to be hidden in a common driver/function behind a platform-specific `#ifdef` https://github.com/sonyxperiadev/kernel/commit/af1ddf3c0940dc3990a764d224fd8be53653e07e. I said it above: "repeat that process into `mipi_dsi_dcs_set_display_brightness`", if only I had looked one function signature deeper before writing that...

Guess there's no shame after all for abandoning this project in favour of yet-unfinished (far from it) mainlining...

**Closed** 2022-04-21 14:58 UTC
Labels: bug

**Comment by MarijnS95** [comment] 2022-04-21 15:05
How'd this get closed by a PR on a different organization entirely, but not by the kernel PR on the same organization here? :thinking:
