### ISSUE TITLE
[ganges] wifi connection drops out after device sits idle for some time

### ISSUE THREAD

**Issue by Haxk20** [sonyxperiadev/bug_tracker#460] opened 2019-09-14 18:39 UTC
**Platform:** ganges
**Device:** mermaid
**Kernel version:** 4.9.185
**Android version:** 9
**Software binaries version:** latest 

**Description**
When i start the device wifi doesnt want to connect automatically to the Wifi thats saved. I have to manually go to settings and click on the saved wifi for it to connect to it. When its connected there are no issues. Then when i put the phone to sleep and after lets say 10 minutes or so the wifi connection drops out and i have to again go to settings for it to connect.

**How to reproduce**
Put phone to sleep when connected to wifi and look on it after some time.

**Additional context**
Maybe its just android killing it for battery saving but that woudlnt explain why wifi wont connect automatically on boot.
Also it seems like more devices have this issue look at #419 which is pretty much the same issue as me.
This makes the device very hard to use in daily scenario where you need to look at something quick but you cant since wifi dropped out.
Will try to grab logcat and dmesg when i get the time.

**Comment by xperia10dev** [comment] 2019-09-15 06:17
I can confirm this bug on an Xperia 10 Dual (kirin I4113).

Logcat with Wi-Fi Verbose Logging is attached. It starts after the point where the phone had been idle for 30 seconds, the screen had turned off and PowerManager sleep kicks in.

It looks like the PowerManager suspend process is aborted due to a wakeup held by wlan_wow_wl.
Two things happen from that point on:

1. Phone does not enter sleep state (which will probably affect battery consumption).
2. WiFi association with the AP is lost and will never be recovered unless the connection is requested again manually via Settings.

[logcat_kirin_wifi_disconnect_on_sleep.txt](https://github.com/sonyxperiadev/bug_tracker/files/3613447/logcat_kirin_wifi_disconnect_on_sleep.txt)

**Comment by Haxk20** [comment] 2019-09-15 14:32
@jerpelea Im sorry to ping you but could somebody look at this as this basically makes the build unusable for daily use.

**Comment by MarijnS95** [comment] 2019-09-16 13:48
@Haxk20 Maybe the [aosp_build](https://github.com/opengapps/aosp_build) project from opengapps is for you. While it doesn't solve the issue of installing zips through opengapps (and definitely has nothing to do with this WiFi issue), it allows you to build a systemimage with opengapps baked in.

**Comment by Haxk20** [comment] 2019-09-16 14:49
Definetly usefull. Thank you very much.

po 16. 9. 2019 o 15:48 MarijnS95 <notifications@github.com> napísal(a):

**Comment by jerpelea** [comment] 2020-01-13 09:54
please add 

<bool translatable="false" name="config_wifi_framework_use_single_radio_chain_scan_results_network_selection">true</bool>
 
in overlay 
frameworks\base\core\res\res\values\config.xml

**Comment by jerpelea** [comment] 2020-01-13 10:05
I managed to replicate the bug and I am trying to find a fix for this bug 
I will update the ticket ASAP

**Comment by chris42** [comment] 2020-01-13 16:18
Will it fix the dropouts in #419 as well? (Not sure if the WifiHAL errors are connected to it)

**Comment by xperia10dev** [comment] 2020-01-13 17:22
@jerpelea Thanks for taking a look at this, I'm available to do any testing that may be necessary to fix the bug.

**Comment by jerpelea** [comment] 2020-01-14 08:51
@chris42 no that is a different Wifi HW

**Closed by jerpelea** 2020-01-14 08:51 UTC
Labels: bug

**Comment by xperia10dev** [comment] 2020-02-15 09:10
May I ask which commit was applied to fix this issue?

I am still getting WiFi disconnections on a fresh Pie build following the official guide (kernel 4.9.210).

When device tries to suspend after 30 seconds of inactivity, the suspend will be interrupted multiple times in a row due to wakelocks held by the qcacld driver (wlan_wow_wl, vdev_stop).
Each of these times the WiFi is disconnected/reconnected again, and after a while WifiLastResortWatchdog kicks in and it seems to disable the association with the AP. From this point forward the only way to reconnect is manually from Settings. 

Symptoms appear to be mostly the same as in my previous comment https://github.com/sonyxperiadev/bug_tracker/issues/460#issuecomment-531538201.

Also tried to set gEnableWoW=0 in WCNSS_qcom_cfg.ini, to no avail.

Attached a file with the relevant logcat lines (SSIDs and MAC addresses redacted).
[issue_460_logcat_freshbuild.txt](https://github.com/sonyxperiadev/bug_tracker/files/4208104/issue_460_logcat_freshbuild.txt)

**Comment by Haxk20** [comment] 2020-02-16 13:01
> May I ask which commit was applied to fix this issue?
> 
> I am still getting WiFi disconnections on a fresh Pie build following the official guide (kernel 4.9.210).
> 
> When device tries to suspend after 30 seconds of inactivity, the suspend will be interrupted multiple times in a row due to wakelocks held by the qcacld driver (wlan_wow_wl, vdev_stop).
> Each of these times the WiFi is disconnected/reconnected again, and after a while WifiLastResortWatchdog kicks in and it seems to disable the association with the AP. From this point forward the only way to reconnect is manually from Settings.
> 
> Symptoms appear to be mostly the same as in my previous comment [#460 (comment)](https://github.com/sonyxperiadev/bug_tracker/issues/460#issuecomment-531538201).
> 
> Also tried to set gEnableWoW=0 in WCNSS_qcom_cfg.ini, to no avail.
> 
> Attached a file with the relevant logcat lines (SSIDs and MAC addresses redacted).
> [issue_460_logcat_freshbuild.txt](https://github.com/sonyxperiadev/bug_tracker/files/4208104/issue_460_logcat_freshbuild.txt)

Could you please try removing your WCNSS_qcom_cfg.ini and replace it with this one ?

[WCNSS_qcom_cfg.zip](https://github.com/sonyxperiadev/bug_tracker/files/4209768/WCNSS_qcom_cfg.zip)
Unpack it and place it in place of the old one.
Report back if the issue is fixed or not.
Thank you

**Comment by xperia10dev** [comment] 2020-02-16 16:15
@Haxk20, the WCNSS_qcom_cfg.ini from Nile p-mr1 branch did not fix the issue. Same behaviour, same logcat messages.

Thanks for trying to help though! What made you think about using the Nile configuration?

**Comment by Haxk20** [comment] 2020-02-16 16:47
Nile does not have this issue and Nile is basically the same thing as Ganges with the same wifi chip so now we know its not config issue.

**Comment by MartinX3** [comment] 2020-02-24 07:48
@Haxk20 your wifi PR's got merged.

**Comment by Haxk20** [comment] 2020-02-28 16:07
@xperia10dev My PR for updating wifi drivers to latest version got merged few days ago. Could you please update your sources locally. By repo sync or if you have used some script then that.
Also please tell me which kernel version you are on.
Thats very important to know.

**Comment by xperia10dev** [comment] 2020-02-28 16:15
@Haxk20 Already tried to update the sources locally via repo sync and compile a new kernel. Unfortunately I'm stuck on Android 9 / kernel 4.9 for now due to other outstanding issues (notably #517), and branch LA.UM.7.1.r1 of the wifi driver where your PR got merged does not seem to compile with kernel 4.9.

**Comment by Haxk20** [comment] 2020-02-28 16:49
@xperia10dev The new OEM files will fix that bug. No clue when they are going to be released but i can say you that that bug is fixed in the new version.

There is no way to compile that driver in 4.9. Its totally different branch.

Also 4.14 has sadly few more bugs that are kinda more important. As device not waking up when somebody is calling you. Or random GPU crashes. Yeah it has some bugs that still need to be fixed.

**Comment by Haxk20** [comment] 2020-02-28 16:51
Ohhhh they have already been released. Well thats good. Yes those blobs fix the bug
