### ISSUE TITLE
Xperia XZ Premium - Offline charging loop when charging from a PC

### ISSUE THREAD

**Issue by dimitar10** [sonyxperiadev/bug_tracker#33] opened 2017-11-13 12:42 UTC
**Platform:** yoshino
**Device:** maple
**Kernel version:** 4.4 (9c6cb35, manually built on 13 Nov)
**Android version:** 8.0.0
**Firmware version:** v05

**Description**
After being shut down and connected to a PC via USB to charge, the device enters an offline charging loop.

**Symptoms**
The device successfully boots up to the offline charging screen and then shuts down and boot up again, ad infinitum. 

**How to reproduce**
1. Turn off device
2. Plug in device to a PC via USB (to charge)

**Logs**
N/A

**Comment by kholk** [comment] 2017-11-14 17:42
Please, anyone check whether this issue is present or not on Poplar, Lilac.

**Comment by jerpelea** [comment] 2017-11-15 07:48
replicated on all yoshino devices

**Comment by humberos** [comment] 2017-11-18 12:27
kagura [tone maybe] also has issues during offline charging when charging from a PC.
I can't see charging progress after white boot splash then device [re]boots to fastboot mode.

**Comment by jamuir** [comment] 2017-12-06 02:35
I also see this with 7.1.1.

**Comment by jerpelea** [comment] 2018-01-29 14:15
it appears to be working fine on the 6.4 branch

**Comment by humberos** [comment] 2018-02-13 17:01
Make sure that you are following build instructions. This requires changes in system/core.
If you already have the system/core revert then just ignore this comment.

**Comment by jerpelea** [comment] 2018-02-14 23:58
to recap 
please check that in system/core you have 
git revert --no-edit 1d540dd0f44c1c7d40878f6a7bb447e85e6207ad
git fetch https:://android.googlesource.com/platform/system/core refs/changes/37/469437/1 && git cherry-pick FETCH_HEAD

**Comment by jerpelea** [comment] 2018-02-14 23:58
I can not replicate this bug anymore
@kholk @humberos @bartcubbins please try to replicate the bug

**Comment by kholk** [comment] 2018-02-15 00:01
Alin, I tried to replicate 2 weeks ago on Maple. As I said already, works fine for me!

**Comment by jerpelea** [comment] 2018-02-15 03:29
@kholk thanks but lets hear the others to be able to close the bug

**Comment by humberos** [comment] 2018-02-15 04:01
**android-8.1.0_r10 + V10 (6.4 kernel)**

1. Charging from A/C power adapter (wall charger)
    - Kagura/Suzu: No issues

2. Charging from a PC (USB):
    - Kagura: Device starts in Flashmode state (green led).
    - Suzu: No issues.

**Comment by jerpelea** [comment] 2018-02-15 04:03
thanks @humberos

**Comment by dimitar10** [comment] 2018-02-16 15:41
The aforementioned changes were indeed included, i.e. the `./repo_update.sh` script correctly applied the patches, and I double checked in the /system/core project that they were there. Also I made sure that everything was up to date. 

For **Suzu**, running a userdebug build built this afternoon (**android-8.1.0_r10 + V10 (6.4 kernel)**), the issue seems to be resolved (both for precompiled and manually compiled kernels).

I will update the issue for **Maple** and **Kagura**, as soon as the builds are complete.

**Comment by kholk** [comment] 2018-02-16 18:15
Just a note: if it doesn't work, please try to full flash the latest FTF for the device(s), make a full boot, then reflash the Open Devices images and retry.

**Comment by humberos** [comment] 2018-02-17 15:40
@kholk 
Thank you!
Kagura is fully fixed after BL updated (from 41.3.A.2.58)
So loire and tone are OK!

**Comment by humberos** [comment] 2018-02-18 06:45
@kholk 
Although tone is fixed by the BL updating but now loire is broken by using BL from 34.4.A.0.364 
:(
Device starts in bootloader mode (blue led).

**Comment by humberos** [comment] 2018-02-18 06:48
So loire@34.4.A.0.364

1. Charging from A/C power adapter (wall charger)
    Device reboots to system

2. Charging from a PC (USB):
    Device starts in bootloader mode (blue led)

**Comment by jerpelea** [comment] 2018-02-20 07:40
can anyone replicate the bug ?

**Comment by humberos** [comment] 2018-02-20 12:25
@jerpelea
Loire and Tone are ok. 
Sorry, i can't test yoshino.

**Comment by bartcubbins** [comment] 2018-02-20 12:31
loire is ok

**Comment by dimitar10** [comment] 2018-02-20 12:38
Flashed the following (latest available firmwares) with Flashtool:

**Suzu F5121** with **34.3.A.0.252** 

1. Wall charger - OK
2. PC Charge - Battery drain issue #84 

**Kagura F8331** with **41.3.A.2.24**

1. Wall charger - stuck at white Sony boot screen
2. PC charger - boots into Flashing mode

**Maple G8142** with **45.0.A.7.137**

1. Wall charger - stuck at white Sony boot screen
2. PC charger - reboot  loop

From the previous posts, newer FTF firmware versions are mentioned, perhaps this can be the source of confusion?

**Comment by jerpelea** [comment] 2018-02-20 12:41
please update your devices to the latest FW

F5121 - 34.4.A.0.364
F8331 - 41.3.A.2.24
G8141 - 47.1.A.8.49

**Comment by dimitar10** [comment] 2018-02-20 15:22
@jerpelea except for the Kagura F8331, the Emma flashtool does not show the newer firmwares for Suzu F5121 and Maple G8142 as available services. (the flashtool version is 2.18.2.201...)

And from above, @humberos has mentioned a newer 41.3.A.2.58 firmware for the Kagura, which is also not available.

Is it possible that these newer firmwares be added to the list of services so that they can be flashed with the flashtool?

**Comment by jerpelea** [comment] 2018-02-20 16:13
let me check what is released for your g8142

**Comment by bartcubbins** [comment] 2018-02-20 16:29
G8142 47.1.A.12.75

**Comment by jerpelea** [comment] 2018-02-21 08:05
G8142 - 47.1.A.12.75 is released

**Comment by jerpelea** [comment] 2018-02-21 08:08
@dimitar10 F5121 - 34.4.A.0.364 is not availabe for your region but it will be soon

**Comment by jerpelea** [comment] 2018-02-26 09:47
@dimitar10 34.4.A.0.364 is released plase test again and update the ticket

**Comment by dimitar10** [comment] 2018-02-27 16:52
**F8331 - 41.3.A.2.24** (fw v10, latest 27 Feb prebuilt kernel)

1. **wall charger**: charging works, but no battery status animation (only the Sony boot logo with white background is shown and the LED is indication that the device is charging)
2. **PC charger**: same battery drain / discharge issue as Suzu: #84

 



**G8142 - 47.1.A.12.75** (fw v10, latest 27 Feb prebuilt kernel)

1. **wall charger**: charging works, but no battery status animation (only the Sony boot logo with white background is shown and the LED is indication that the device is charging)
2. **PC charger**: charging reboot loop. The device manages to reach the Sony boot logo with white background, and then repeatedly will reboot. There are differences between the reboots. When the devices reaches the Sony boot logo, before the first reboot the LED will remain in the same color i.e. bright red, and on the next reboot the LED will change from bright red to yellow. It seems that the device is repeatedly trying to boot into charging mode and fails every time.

**F5121 - 34.4.A.0.364**
I will update the issue for Suzu as soon as I have access to the device.

**Comment by jerpelea** [comment] 2018-02-27 17:00
thanks for the updates

today I fixed the mount race and devices are always entering charging mode

**Comment by kholk** [comment] 2018-03-04 16:09
@dimitar10 Can you re-test everything, please?
The Loire/Tone charging issues should be solved now....
...also, I tried for the (102!*4)^67 time but my Maple doesn't miss a shot, so perhaps... the only thing I can think of is either a bad cable or a "bad" USB controller on your motherboard.

If you still have charge mode issues on SoMC Maple, can you please try again by using a different cable on a different PC?

Thanks!

**Comment by jerpelea** [comment] 2018-03-04 16:10
@dimitar10 please rebuild kernel and retest since both the race and the discharge issue are fixed

I would recommand to try:
an usb port from the back of your computer
a different USB cable 
a different computer

**Comment by jerpelea** [comment] 2018-03-08 09:29
**NOTE:**
When a device is updated to a new Sony SW version **THE DEVICE MUST BE BOOTED WITH THE SONY SW** to update the fw and device configuration before flashing AOSP or any custom SW

**Comment by nailyk-fr** [comment] 2018-03-08 11:13
FI it happens on shinano too (3.10 or 3.4)

**Comment by humberos** [comment] 2018-03-12 23:41
Oh! I think this should be the problem!
Actually we were using **android-8.1.0_r3**  branch from  (https://github.com/sonyxperiadev/repo_update ) which have the patch and the revert on system/core ( https://github.com/sonyxperiadev/repo_update/commit/f43585e1f98faa906473d32b1c9c400cf481b1f0 ).

Now the same patchset was merged on **master** branch.
https://github.com/sonyxperiadev/repo_update/commit/77d8148c54c27f1ac4597df2f905f3126d2ef7b4

**Comment by jerpelea** [comment] 2018-04-06 13:14
on some PC usb  (broken charging)
maple:/ $ cat /sys/class/power_supply/usb/online
0
maple:/ $ cat /sys/class/power_supply/usb/type
USB_PD

on other PC usb  (working charging)
maple:/ $ cat /sys/class/power_supply/usb/online
1
maple:/ $ cat /sys/class/power_supply/usb/type
USB_PD

**Comment by jamuir** [comment] 2018-05-10 14:33
I still see this in the latest XZP image built from `android-8.1.0_r26` (on both G8141 and G8142).

**Comment by jamuir** [comment] 2018-05-11 16:46
@jerpelea:  I did a quick test of various machines in our office (14 in total, including a mac, a windows machine and a NAS device).  I am using the precompiled 4.4.130 kernel.  With the XZP turned off, I went to each machine and plugged into a usb port.

13 of 14 machines show the broken behaviour.  The XZP's screen powers on; the white sony splash screen is shown; the led turns from red to yellow; then, a few seconds later, the device reboots.

For the 1 machine that does not show the broken behaviour, I can confirm that `cat /sys/class/power_supply/usb/online` gives `1`.

I checked two of machines with the broken behaviour, and there `cat /sys/class/power_supply/usb/online` gives `0`.

**Comment by jerpelea** [comment] 2018-05-11 17:18
did you try the front USB ports or the back ones?

thanks

**Comment by jamuir** [comment] 2018-05-11 17:39
About half the machines were laptops, which do not have front and back ports.

For the other machines, sometimes I tested a front port and sometimes a back port.

**Comment by jerpelea** [comment] 2018-05-11 18:00
cen you please enable usn debug inkernel

**Comment by kholk** [comment] 2018-05-11 18:15
Wow, that's pretty much a bad luck. For me all 3 of my machines are making it work fine....
One is an x86 i3 tablet with one USB3 port, one is an old Phenom x4 Toshiba laptop with only usb2 and the other one is my main rig, TR/X399 desktop pc with two USB controllers, one on the X399 chipset with USB2+3 and a separate one with 3.1+typec.

I've even tested both of the controllers on the desktop one, and they unluckily work fine. 

I really wish I had a machine that makes this issue appear to be able to find a fix.. :(


But yeah, well, enable verbose debugging and post a log please, that's the best you can provide, unfortunately.

**Comment by jamuir** [comment] 2018-05-14 22:49
I ran `dmesg -c > /dev/null` and then plugged and unplugged a usb cable 3 or 4 times (each time I waited for the little charging icon to appear in the status bar), then captured dmesg.

Here are logs from a bad machine and a good one:

[dmesg-bad.4.txt](https://github.com/sonyxperiadev/bug_tracker/files/2002814/dmesg-bad.4.txt)
[dmesg-good.5.txt](https://github.com/sonyxperiadev/bug_tracker/files/2002815/dmesg-good.5.txt)

There is a log message from healthd that is different (`system/core/healthd/BatteryMonitor.cpp`).  In one case we see `chg=u` and the other `chg=a`:

```
# bad
[ 1535.548608] usbpd usbpd0: Type-C Source (default) connected
[ 1535.563721] healthd: battery l=100 v=4313 t=26.7 h=2 st=3 c=78 fc=3424000 chg=
[ 1535.563733] msm-dwc3 a800000.ssusb: DWC3 exited from low power mode
[ 1535.664747] healthd: battery l=100 v=4313 t=26.7 h=2 st=3 c=78 fc=3424000 chg=
[ 1535.796071] msm-dwc3 a800000.ssusb: Avail curr from USB = 100
[ 1535.871523] healthd: battery l=100 v=4313 t=26.7 h=2 st=4 c=78 fc=3424000 chg=u
[ 1535.905619] android_work: sent uevent USB_STATE=CONNECTED
[ 1535.907830] healthd: battery l=100 v=4313 t=26.7 h=2 st=4 c=78 fc=3424000 chg=u
[ 1535.908986] android_work: sent uevent USB_STATE=DISCONNECTED
[ 1535.922928] healthd: battery l=100 v=4313 t=26.7 h=2 st=4 c=78 fc=3424000 chg=u
```

```
# good
[  157.285773] usbpd usbpd0: Type-C Source (default) connected
[  157.296092] healthd: battery l=100 v=4276 t=29.5 h=2 st=4 c=245 fc=3424000 chg=a
[  157.319726] msm-dwc3 a800000.ssusb: DWC3 exited from low power mode
[  157.425537] healthd: battery l=100 v=4276 t=29.5 h=2 st=4 c=245 fc=3424000 chg=a
```

**Comment by jerpelea** [comment] 2018-05-25 15:37
an interesting commit 
https://android.googlesource.com/kernel/msm/+/1e352b291031d023d2677fa59842542deb8a3a46

**Comment by aolexiy** [comment] 2018-06-14 13:05
USB isn't initialized for charger mode, this - https://github.com/sonyxperiadev/device-sony-yoshino/pull/95 - sets up a mass_storage function via init script. Seems to fix the charging issues (checked on G8141 & G8341). In order to fix the charger UI the following is also needed - https://github.com/sonyxperiadev/device-sony-maple/pull/48

**Comment by jerpelea** [comment] 2018-06-17 19:52
https://github.com/sonyxperiadev/device-sony-common/commit/4ac93ddeb596845b68adcfc8bd60794c3f076cde

**Comment by jerpelea** [comment] 2018-06-17 19:53
@abioteau

**Comment by jamuir** [comment] 2018-06-18 19:05
just did an oreo build for XZP (G8141).  I can confirm offline charging is working now.

thank-you @aolexiy !

**Comment by dimitar10** [comment] 2018-06-18 22:53
I can confirm that it's working as well, tested on a Maple G8142 running 8.1.0 with the latest 4.4 kernel and v12 firmware. Regular and quick-chargers also work for the device, in reference to #130. Will do the test for the Kagura F8331 as soon as I have the time.

**Closed** 2018-06-19 05:48 UTC

**Comment by abioteau** [comment] 2018-06-19 07:08
It's still not working on a Maple G8142 running 8.0.0 with kernel 4.4 rebuild.

**Comment by jerpelea** [comment] 2018-06-19 07:15
Android 8.0 needs some backports from 8.1
