### ISSUE TITLE
[10][4.14][Yoshino] [Poplar] The volume keys are super un-responsive

### ISSUE THREAD

**Issue by yuezhengbaizhi** [sonyxperiadev/bug_tracker#556] opened 2020-03-07 15:56 UTC
**Platform:** Yoshino
**Device:** Poplar
**Kernel version:**4.14 
**Android version:** 10
**Software binaries version:** v4c 

**Previously working on**
it was working on pie/stock

**Description**
when i press the volume key, i have to wait 5s for the panel to show up

**How to reproduce**
flash these https://drive.google.com/open?id=1kaT0NFKx35ce7Jq5qzJ93rzgeyr2HETa and go through setup and press volume keys 

**Additional context**

logcat 
[xz11.txt](https://github.com/sonyxperiadev/bug_tracker/files/4302089/xz11.txt)

**Comment by MarijnS95** [comment] 2020-03-07 16:10
As said in https://github.com/sonyxperiadev/bug_tracker/issues/553 _too_ you should figure out why the entire audio system keeps crashing, first.

```
03-07 10:20:05.369 13629 13674 W ServiceManager: Permission failure: android.permission.CAPTURE_AUDIO_OUTPUT from uid=10097 pid=4164
03-07 10:20:05.370 13629 13674 D PermissionCache: checking android.permission.CAPTURE_AUDIO_OUTPUT for uid=10097 => denied (615 us)
03-07 10:20:05.372 13629 13674 D PermissionCache: checking android.permission.CAPTURE_AUDIO_HOTWORD for uid=10097 => granted (206 us)
03-07 10:20:05.373 13629 13674 F libc    : Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 13674 (Binder:13629_6), pid 13629 (audioserver)
```

If I had to guess the dialog is simply waiting for the audio system to become available. Nothing wrong with Android or SODP, but your ROM.

**Comment by yuezhengbaizhi** [comment] 2020-03-07 17:41
> As said in #553 _too_ you should figure out why the entire audio system keeps crashing, first.
> 
> ```
> 03-07 10:20:05.369 13629 13674 W ServiceManager: Permission failure: android.permission.CAPTURE_AUDIO_OUTPUT from uid=10097 pid=4164
> 03-07 10:20:05.370 13629 13674 D PermissionCache: checking android.permission.CAPTURE_AUDIO_OUTPUT for uid=10097 => denied (615 us)
> 03-07 10:20:05.372 13629 13674 D PermissionCache: checking android.permission.CAPTURE_AUDIO_HOTWORD for uid=10097 => granted (206 us)
> 03-07 10:20:05.373 13629 13674 F libc    : Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 13674 (Binder:13629_6), pid 13629 (audioserver)
> ```
> 
> If I had to guess the dialog is simply waiting for the audio system to become available. Nothing wrong with SODP, but your ROM.

Okay, but it's the second room I tried that is based on sodp so I think it should be an sodp problem

**Comment by MarijnS95** [comment] 2020-03-07 21:55
Remember that SODP is an _open source_ project; contributors should _never_ have to download a random image from you and backup+flash it on their daily device.
Instead, **you** are responsible for syncing and building a clean version of this project before reporting issues. If you are not in a position to do that, report it to the ROM builder instead. They can decide whether it an issue on their end or SODP. Don't think for yourself whether `so I think it should be an sodp problem` unless there are compelling reasons to do so.

Now, about the issue itself: Why don't you just _tell us_ what random ROM you are using? Why are the images hidden behind a private drive share link?

Did you read the snippet I pasted from the logs? If not, look at it again. Understand what the permissions mean. Trace back the PID and understand which application is throwing the audio policy engine overboard. Then report that to your ROM builder.

**Comment by AlbertBackenhof** [comment] 2020-03-08 09:26
I'm having the same issue on my lilac. No audio at all and volume keys are slow to react (but as previously stated this is most likely because of failing audio system).

I'm using the very latest build that I synced, built and flashed according to the Xperia AOSP guide yesterday.

**Comment by MarijnS95** [comment] 2020-03-08 11:03
@AlbertBackenhof The same question applies to you too: Is there anything applied or installed on top of a plain SODP image? If the situation is anything like the logs from @yuezhengbaizhi it is far from a clean system image, but you didn't provide any logs for us to confirm.

Let me repeat again that you need to be specific while reporting bugs. We can't pull solutions out of thin air, especially when the system has been tampered with (hint: gapps...).

**Comment by AlbertBackenhof** [comment] 2020-03-08 11:42
@MarijnS95 I knew you were going to say that :P Sorry didn't have time earlier to get the logs etc.

I'm using a completely clean SODP. Only done what's in the official guide. My config is:

**Platform**: Yoshino
**Device**: Lilac
**Kernel version**: 4.14.171
**Android version**: 10
**Software binaries version**: v4c

[dmesg_aosp10_no_audio.log](https://github.com/sonyxperiadev/bug_tracker/files/4303131/dmesg_aosp10_no_audio.log)
[logcat_aosp10_no_audio.log](https://github.com/sonyxperiadev/bug_tracker/files/4303132/logcat_aosp10_no_audio.log)

**Comment by MarijnS95** [comment] 2020-03-08 11:53
```
03-08 02:41:41.106   605   605 E audio_hw_primary: adev_open: Failed to init platform data, aborting.
03-08 02:41:41.106   605   605 E DevicesFactoryHAL: loadAudioInterface couldn't open audio hw device in audio.primary (Invalid argument)
03-08 02:41:41.107   636   636 E AudioFlinger: loadHwModule() error -19 loading module primary
03-08 02:41:41.107   636   636 W APM_AudioPolicyManager: could not open HW module primary
```
Looks like the audio HAL is not included on your side either. (Which crashes the audio policy manager when checking Gapps permissions for @yuezhengbaizhi).

Can you provide the output of?
```sh
ls -l /vendor/lib*/hw/audio*
```
If there's no `audio.primary.msm8998.so`, can you try invoking a build with `make audio.primary.msm8998` to see if it is available?

**Comment by AlbertBackenhof** [comment] 2020-03-08 12:23
In /dev/snd/ there's only one file: _timer_.

I don't know if this has been a problem before. Previous versions of 4.14 I've tried has had terrible performance and black screen of death, so never tried the audio and haven't looked in the logs for problems with it.

**Comment by MarijnS95** [comment] 2020-03-08 12:25
@AlbertBackenhof Thanks for the info. Looks like there is indeed a misconfiguration causing the entire audio subsystem to be missing. I'll get that looked into.

**Comment by AlbertBackenhof** [comment] 2020-03-13 13:20
Any updates on this? Anything I can try or look at? I've already tried to find any "obvious" mistake but not really sure where to look.

**Comment by wyzco** [comment] 2020-03-28 12:39
New OEM Binary are out, will see if any thing changes.

**Comment by AlbertBackenhof** [comment] 2020-03-28 14:07
Still no audio for me. I'll return with the logs later; but behavior is the same as before so I'm guessing the problem remains.

**Comment by kholk** [comment] 2020-05-08 15:48
Audio issues have been solved.

Please report back.

**Comment by stefanhh0** [comment] 2020-05-12 04:00
Verified, using:

**Platform:** Yoshino
**Device:** Lilac
**Kernel version:** 4.14.176-gf0356fa3bcac:
- https://github.com/sonyxperiadev/kernel/commit/39a85fa2d0ac283af82b383542fa1e88744a9d36
- Kernel PR 2261

**Android version:** android-10.0.0_r36
**Software binaries version:** SW_binaries_for_Xperia_Android_10.0.7.1_r1_v6_yoshino.img
**Version baseband:** 1307-7511_47.2.A.11.228
**Build:** aosp_g8441-userdebug 10 QQ2A.200501.001.B3 eng.stefan.20200510.170705

Don't know if there can be difference on Yoshino/Lilac and Yoshino/Poplar. For Lilac everything is fine. Since @yuezhengbaizhi didn't report back yet, I'd say it is okay to just close the issue since it is rather likely that the problem is really fixed. If not one can open a new issue anyway with more recent logs. 

@jerpelea I think this issue can just be closed.

**Comment by kholk** [comment] 2020-06-08 21:09
Please close this issue.

**Closed** 2020-06-08 21:44 UTC
Labels: bug
