### ISSUE TITLE
[Lilac][Yoshino] After crash device only boots on power supply

### ISSUE THREAD

**Issue by djselbeck** [sonyxperiadev/bug_tracker#368] opened 2019-04-10 07:35 UTC
**Platform:** Yoshino
**Device:** Lilac
**Kernel version:** Up to head at April 9th tested from March 8th
**Android version:** Up to head at April 9th tested from March 8th

**Description**
After my device froze during music listening over bluetooth (#348) it never rebooted successful again to the AOSP installation. I tried reflashing all images (system, vendor,userdata, oem, boot, recovery), it did not help. 

Then I reflashed Stock Android 8 (via Emma), booted up successful after flashing. Works stable, with and without power supply. 

After reflashing AOSP the device will still not boot but randomly I found out that it boots up when connected to a real (sony) power supply. Seems to work stable after boot up even with out power supply. 

I tried to flash Stock Rom (android 9) via newflasher, it also works very stable (no crash after one day of use), boots with and without power supply.

**Symptoms**
AOSP will only boot if connected to a power supply

**How to reproduce**
Difficult. I never had problems of this kind until the crash occurred. I even tried booting images from March that worked before for weeks, they don't boot now until I plug the device in.

I described a bit of the problems in #364 as it might be related.

**Comment by VictorRyabov** [comment] 2019-04-10 09:12
Just to confirm-this happened to me and 2 people on 4pda forums. We've switched to stock after the above described issue occured. We are guessing that it is kernel stability related issue like #364

**Comment by jerpelea** [comment] 2019-04-10 12:20
What is the Sony SW vresion that you flashed on the device?

The BT bug is mitigard in v8 release
Thanks for reporting it!

**Comment by VictorRyabov** [comment] 2019-04-10 15:23
I was using G8441_47.1.A.16.20_1310-5279_R9B as you advised.

**Comment by djselbeck** [comment] 2019-04-10 15:37
I tried 8.0 from Emma, 9.0 from Emma and a Customized Germany from XperiFirm, I don't have the exact version numbers at hand right now, but the behavior was the same for all of them. Thanks for your continuous support.

**Comment by jerpelea** [comment] 2019-04-10 17:21
please use the 8.0 one not 9.0

**Comment by djselbeck** [comment] 2019-04-10 17:22
Will do, after roughly two weeks. Need the device functional at the moment. Before I try using AOSP again, I'll downgrade

**Comment by invalidsudo** [comment] 2019-04-12 00:15
I can confirm this issue, AOSP on lilac can only boot when connected to a power supply.

**Comment by stefanhh0** [comment] 2019-04-13 07:54
- Flashed G8441_Customized_NOBA_1311-0104_47.1.A.16.20_R22B via newflasher and booted once with sim inserted
- Flashed a build from 2019_04_02 (Kernel is newer (2019_04_05): 4.9.166-gb62e061b9a47) -> AOSP boots as expected
- Flashed a build from 2019_04_12 evening -> AOSP boot hangs always for me: 
  - When USB is connected to the charger
  - When USB is connected to the computer
  - When USB is not connected
- Reverted to the AOSP build from 2019_04_02 -> AOSP boots as expected again

To revert to a previous AOSP I had to flash the full set of images:
- fastboot flash boot boot.img
- fastboot flash recovery twrp-3.2.3-0-lilac-pie-2.img
- fastboot flash oem SW_binaries_for_Xperia_Android_9.0_2.3.2_v7_yoshino.img
- fastboot flash system system.img
- fastboot flash userdata userdata.img
- fastboot flash vendor vendor.img

I have also tried to simply revert via flashing boot, system and vendor but than also the older AOSP was no longer booting.

Unfortunately I can't provide any files, however it seems to be easy reproducible.

For now current AOSP is no longer useable on lilac/yoshino and all should stay on their previous running versions until a fix is available for this.

**Comment by russel5** [comment] 2019-04-13 15:31
@stefanhh0, yes on latest build (compiling 12.04.19) phone not boot anymore
I'm think this is because team change display to SDE and we need to wait new oem files.

**Comment by stefanhh0** [comment] 2019-04-13 17:55
@russel5 thanks for confirming the new situation. Well, the switch to SDE would be a good explanation, however https://github.com/sonyxperiadev/device-sony-common/blob/master/common-odm.mk#L2 is still on v7 and should have been increased then accordingly. Maybe that will happen soon...

**Comment by jerpelea** [comment] 2019-04-14 05:33
please do a full build on your device (not only kernel) and try to get a log
we tested all devices on v7 and they boot fine

**Comment by russel5** [comment] 2019-04-14 07:06
how i can get log if on sony logo my screen have broken line and phone not react for anything
and i always build full rom with kernel_build=true

**Comment by stefanhh0** [comment] 2019-04-14 10:34
@jerpelea I did a full build before flashing and as Ruslan already said the phone gets not past the initial black Sony logo on white screen, I've tried several times. It paints sometimes colorfull vertical thin lines, thats all. So providing a log is really not possible at the moment.

I did a repo_update.sh on 2019_04_12 evening after you have integrated all the changes, since then nothing additionally was merged back (just double-checked it). Did a make clean && make -j 4 and flashed all images from that build with one exception the recovery:
```
boot.img
twrp-3.2.3-0-lilac-pie-2.img
SW_binaries_for_Xperia_Android_9.0_2.3.2_v7_yoshino.img
system.img
userdata.img
vendor.img
```
1. I flashed also  G8441_Customized_NOBA_1311-0104_47.1.A.16.20_R22B via newflaser booted it once with sim inserted
2. Then flashed an older full AOSP which also booted just fine
3. After flashing the most recent AOSP it is no longer booting 
4. I had to revert again to the older AOSP, then it was able to boot again

The blob in vendor-sony-kernel and the kernel itself are on the same commit sonyxperiadev/kernel@bbb435ce9d7c4e3a35494173e8df9c2bfdd659e9 therefore I assume it makes no difference whether kernel is self-built or the pre-built is used.  However I've also used the self-built kernel since I've removed kernel/sony/msm-4.9/common-kernel before doing the build.

I am currently out of ideas what I could try to get it booting with the most recent AOSP or how to get any logs from it in that state.

**Comment by jerpelea** [comment] 2019-04-15 06:58
@stefanhh0 please post the dmesg from the last booting rom (from boot)

**Comment by stefanhh0** [comment] 2019-04-15 19:16
Here is the dmesg from a fresh boot using my build from 2019_04_02 with kernel 4.9.166-gb62e061b9a47: [dmesg.log](https://github.com/sonyxperiadev/bug_tracker/files/3081736/dmesg.log)

**Comment by jerpelea** [comment] 2019-04-18 13:28
@stefanhh0 v8 is released !
please rebuild and test

**Comment by stefanhh0** [comment] 2019-04-18 22:00
With v8 and latest build it just booted fine when connected to usb the first time. 

I tried also to boot when not connected to usb and while booting I got a crash, after that crash the phone rebooted fine (still not connected to usb) I am going to open a new bug for that, since that is something different than the symptoms that have been reported here.

Since I didn't encounter the original problem that was reported in this issue it would be good if:
- @djselbeck, 
- @invalidsudo and/or
- @VictorRyabov

can confirm if the here reported problem is now fixed for them.
To me it seems to be the case.

**Comment by djselbeck** [comment] 2019-04-18 23:10
@stefanhh0 I am not even sure I was affected by the same issue as my device never really started booting in contrast to yours. Anyway I am unable to test for the next two weeks at least. Sorry

**Comment by stefanhh0** [comment] 2019-04-18 23:54
@djselbeck Understand, then I guess it would be good to just close this issue, I anyway have opened a new bug regarding boot instability with v8. See #370.

**Comment by djselbeck** [comment] 2019-04-18 23:57
Why close it?

**Comment by stefanhh0** [comment] 2019-04-19 00:23
Many things have changed since the initial report and the boot behavior has now new different issues.
Additionally I can't reproduce this issue with the current aosp. If also no one else can reproduce this bug in the next couple of days the bug should be really closed and not stay open for another two weeks or so.

I guess the reason for not being exactly reproducible that time back for me was, that we always have been on slightly different AOSP versions. 

In case it turns out that you then are still affected by this boot bug then this issue can be reopened anyway or a new one can be opened with uptodate infos.

**Comment by djselbeck** [comment] 2019-04-19 00:56
As I have said before your issue is not the same. @VictorRyabov and @invalidsudo both confirmed MY issue. So please do not hijack the original issue.

**Comment by stefanhh0** [comment] 2019-04-19 05:29
I didn't mean to hijack your issue... I am sorry to have evoked anger.

**Comment by djselbeck** [comment] 2019-04-19 09:29
It is alright, I just wanted to clarify that these are probable two different issues, as your device seemingly boots to some point in the system because you get some log output and my device and the others do not even progress so far. 

The problem why I can't test it right now is because I am depending on a working phone at the moment because of travel arrangements ;-). It is not that I would not like to help.

**Comment by stefanhh0** [comment] 2019-05-14 04:18
@djselbeck Have you been able to re-test it again on a fresh build on 47.1.A.16.20 version-baseband?

**Comment by jerpelea** [comment] 2019-05-14 11:02
I can not replicate the bug on latest HEAD

**Closed by jerpelea** 2019-05-14 11:02 UTC
