### ISSUE TITLE
XZ1 frontal camera quality when in video mode

### ISSUE THREAD

**Issue by AlexandreStumpf** [sonyxperiadev/bug_tracker#198] opened 2018-10-08 17:04 UTC
**Platform:** 
MSM8998 
**Device:** 
XZ1
**Kernel version:** 
4.4
**Android version:** 
8,.1

**Description**
Frontal camera quality is unusable for video call software. This is not the same behaviour of the default Sony XZ1 Android build.

**Symptoms**
Frontal camera quality is too bad (dark) when using with video mode.

**How to reproduce**
Open the Camera App on aXZ1 running an AOSP build and also in a XZ1 running default Sony Android build. Select the 'video' mode and compare both images.

Attached are the images that shows this differences. The phone on the left are running the AOSP build and the one on the right is running the Sony Android XZ1 build. Both are Sony XZ1.

Please note that one image shows when in Camera mode (photo) and the other when in video mode.

![whatsapp image 2018-10-08 at 13 47 44](https://user-images.githubusercontent.com/3493532/46623083-e65c9380-cb02-11e8-8d8c-562c89847297.jpeg)
![whatsapp image 2018-10-08 at 13 47 21](https://user-images.githubusercontent.com/3493532/46623084-e65c9380-cb02-11e8-9fe6-3c2b715f4988.jpeg)

**Comment by oshmoun** [comment] 2018-10-09 01:30
(probable) duplicate of https://github.com/sonyxperiadev/bug_tracker/issues/112

**Comment by jerpelea** [comment] 2018-10-09 10:05
I will take a look on imx258 sensor

**Comment by oshmoun** [comment] 2018-10-09 11:13
@jerpelea this is unnecessary. it just takes a quick test using opencamera to know if it's the same issue as #112

**Comment by jerpelea** [comment] 2018-10-09 13:07
the imx258 sensor has been improved and the fix will come soon in the vendor v16 for Android 8.1

**Comment by AlexandreStumpf** [comment] 2018-10-10 16:55
When will you release v16? Any plans to do it this month?

**Comment by jerpelea** [comment] 2018-10-10 17:12
the plan is to release it soon

**Comment by AlexandreStumpf** [comment] 2018-10-11 16:07
Problem solved. 

Thanks

**Closed** 2018-10-11 16:39 UTC
