### ISSUE TITLE
[loire][suzu] RAW10 does not work on main camera

### ISSUE THREAD

**Issue by YuriyMosiychuk** [sonyxperiadev/bug_tracker#330] opened 2019-02-07 16:20 UTC
**Platform:** loire
**Device:** suzu
**Kernel version:** 4.9.150
**Android version:** 9
**OEM version:** 5

**Description**
**RAW10** does not work on main camera, but on front works good.
More about RAW10: https://developer.android.com/reference/android/graphics/ImageFormat.html#RAW10
**RAW_SENSOR** work, but viewfinder very laggy (buffer bug).

**Symptoms**
When you take a picture on the main camera in RAW10 mode, the picture is spoiled. (see attachment)

**How to reproduce**
Install any one Google Camera and take a shot, for example: https://f.celsoazevedo.com/file/gcamera/MGC_6.1.021_BSG_Arnova-based_v.1.3e_TlnNeun.apk
![screenshot_20190207-180541](https://user-images.githubusercontent.com/13708205/52424667-1d6ba180-2b03-11e9-82dc-f531aca3e7a9.png)
**Shot:**
![img_20190207_175400](https://user-images.githubusercontent.com/13708205/52424949-b39fc780-2b03-11e9-9929-fc9a1b4733c0.jpg)

**Comment by YuriyMosiychuk** [comment] 2019-02-09 11:00
Maybe this will help you fix it?
https://gitlab.tubit.tu-berlin.de/justus.beyer/streamagame_platform_frameworks_base/commit/d1988a98ed69db8c33b77b5c085ab91d22ef3bbc

**Comment by sjllls** [comment] 2019-03-29 12:36
Log uploaded,
Android 9 , OEM V7, built on 2019.3.24.
[SuzuGcam_1.log](https://github.com/sonyxperiadev/bug_tracker/files/3022626/SuzuGcam_1.log)

**Comment by YuriyMosiychuk** [comment] 2019-04-05 05:48
> Log uploaded,
> Android 9 , OEM V7, built on 2019.3.24.
> Issue still exists.
> [SuzuGcam_1.log](https://github.com/sonyxperiadev/bug_tracker/files/3022626/SuzuGcam_1.log)

thanks for log. But developers ignore this issue.

**Comment by jerpelea** [comment] 2019-04-05 06:04
The issue is acknowledged but it has low priority due to limited BW

**Comment by MartinX3** [comment] 2019-04-05 06:07
What does BW mean? :)

**Comment by jerpelea** [comment] 2019-04-05 06:09
Bandwith

**Comment by jerpelea** [comment] 2019-04-17 11:00
unfortunately this bug will not be fixed on suzu

**Closed by jerpelea** 2019-04-17 11:00 UTC

**Comment by YuriyMosiychuk** [comment] 2019-04-17 12:04
@jerpelea why not?
