### ISSUE TITLE
[4.14][YOSHINO][AOSP11] Sensors.qcom missing from v5

### ISSUE THREAD

**Issue by ShujathMohd** [sonyxperiadev/bug_tracker#699] opened 2021-06-15 13:28 UTC
**Platform:** Yoshino
**Device:**  maple
**Kernel version:** 4.14 
**Android version:**  11
**Software binaries version:** V5b 

**Previously working on** V3
Has this always been a problem, or is it a new issue?  Started from V4

**Description**
Since V4 binaries for yoshino sensors are not working and also sim detection doesnt work with the below log 

--------- beginning of crash
06-14 19:05:43.525  2013  2013 E AndroidRuntime: FATAL EXCEPTION: main
06-14 19:05:43.525  2013  2013 E AndroidRuntime: Process: com.android.phone, PID: 2013
06-14 19:05:43.525  2013  2013 E AndroidRuntime: java.lang.RuntimeException: Unable to start receiver com.sony.transmitpower.sensor.FeatureIntentReceiver: java.lang.IllegalStateException: Sensor is null.
06-14 19:05:43.525  2013  2013 E AndroidRuntime: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4035)
06-14 19:05:43.525  2013  2013 E AndroidRuntime: 	at android.app.ActivityThread.access$1400(ActivityThread.java:237)
06-14 19:05:43.525  2013  2013 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1924)
06-14 19:05:43.525  2013  2013 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
06-14 19:05:43.525  2013  2013 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:223)
06-14 19:05:43.525  2013  2013 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7664)
06-14 19:05:43.525  2013  2013 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-14 19:05:43.525  2013  2013 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
06-14 19:05:43.525  2013  2013 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
06-14 19:05:43.525  2013  2013 E AndroidRuntime: Caused by: java.lang.IllegalStateException: Sensor is null.
06-14 19:05:43.525  2013  2013 E AndroidRuntime: 	at com.sony.transmitpower.sensor.SensorBase.init(SensorBase.java:48)
06-14 19:05:43.525  2013  2013 E AndroidRuntime: 	at com.sony.transmitpower.sensor.Accelerometer.init(Accelerometer.java:68)
06-14 19:05:43.525  2013  2013 E AndroidRuntime: 	at com.sony.transmitpower.sensor.SensorFeature.init(SensorFeature.java:43)
06-14 19:05:43.525  2013  2013 E AndroidRuntime: 	at com.sony.transmitpower.sensor.FeatureIntentReceiver.onReceive(FeatureIntentReceiver.java:35)
06-14 19:05:43.525  2013  2013 E AndroidRuntime: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4026)
06-14 19:05:43.525  2013  2013 E AndroidRuntime: 	... 8 more
06-14 19:05:43.525  3175  3175 D CellBroadcastReceiver: Start Cell Broadcast configuration.
06-14 19:05:43.526  3219  3219 I hw-BpHwBinder: onLastStrongRef automatically unlinking death recipients
06-14 19:05:43.526  1565  1565 V KeyguardUpdateMonitor: onSubscriptionInfoChanged()
06-14 19:05:43.527  2939  2970 W MessagingApp: PhoneUtils.getForLMR1(): invalid subId = -1

After investigating found sensors.qcom is missing (which was last seen in v3). /odm/bin/sensors.qcom

https://github.com/sonyxperiadev/device-sony-common/blob/r-mr1/rootdir/vendor/etc/init/sensors.rc#L20

**Symptoms**
Test sensors failed

**How to reproduce**
Use any app to test the sensors and they will fail.(No data from sensor).

**Comment by MarijnS95** [comment] 2021-06-16 08:48
That file should be reworked, sensors are nowadays handled by the multihal and its rc file provided in `/vendor/etc/init/android.hardware.sensors@2.1-service-multihal.rc`. See also https://github.com/sonyxperiadev/device-sony-common/pull/821.

The stacktrace pasted here is a _result_ of the missing service. Please share the failure reason for this service itself. Hint: `adb logcat -v color | rg -ie sensor -e ssc` during boot.

**Comment by ShujathMohd** [comment] 2021-06-16 22:38
[Sensors.txt](https://github.com/sonyxperiadev/bug_tracker/files/6666192/Sensors.txt)

Thanks for the information and hint @MarijnS95 ,
Attaching the sensors log.

**Comment by MarijnS95** [comment] 2021-06-17 09:10
> E init : Control message: Could not find 'android.hardware.sensors@2.1::ISensors/default' for ctl.interface_start from pid: 506 (/system/bin/hwservicemanager)�[0m

That just says the service was not started nor could it be lazily started (`android.hardware.sensors@2.1-service-multihal.rc` does not define the `interface`). I'm interested in what comes after:

```
[38;5;40m06-24 08:51:06.406     0     0 I init    : starting service 'vendor.sensors-hal-2-1-multihal'...[0m
```

As that is the actual service start, which hosts `@2.1::ISensors`. None of the usual expected messages show up here, but this is what comes out on my side:

```
06-17 11:07:52.651  3089  3089 I sensors : sensors_hw_module:139, create sensors sub-hal instance
06-17 11:07:52.652  3089  3089 I sensors-hal: get_system_config:63, log_level: 2
06-17 11:07:52.653  3089  3089 I sensors-hal: is_rt_thread_enabled:82, ssc_enable_rt_task : true
06-17 11:07:52.655  3089  3089 I sensors-hal: sensors_hal:172, initializing sensors_hal
06-17 11:07:52.656  3089  3089 I sensors-hal: get_sns_settings:198, settings 0
06-17 11:07:52.657  3089  3089 I sensors-hal: get_qmi_debug_flag:241, support_qmi_debug : false
```

Iirc the problem is that the new sensor configuration has to be ported to Yoshino (and Nile, and Ganges) since we bumped to the SSC sensor driver (`/odm/lib64/hw/sensors.ssc.so`).

**Comment by ShujathMohd** [comment] 2021-07-16 08:51
@MarijnS95 Sorry I am going away from the subject issue.
One more thing I noticed on maple, graphics nodes are not available

maple:/ $ ls /sys/class/graphics/
maple:/ $ ls /sys/devices/virtual/graphics/
ls: /sys/devices/virtual/graphics/: No such file or directory

Permissions are getting assigned here

https://github.com/sonyxperiadev/device-sony-common/blob/r-mr1/rootdir/vendor/etc/init/hw/init.common.rc#L214

**Comment by MarijnS95** [comment] 2021-07-16 09:00
@ShujathMohd Please make a new issue. The only overlap with #699 is that it "also concerns maple"?

**Comment by Haxk20** [comment] 2021-07-23 12:20
> Iirc the problem is that the new sensor configuration has to be ported to Yoshino (and Nile, and Ganges) since we bumped to the SSC sensor driver (`/odm/lib64/hw/sensors.ssc.so`).

Correct. My maple is currently on pmOS but i will see what i can do. Since yoshino seems to be the 1 platform where things dont go nuts before reading the config files.

**Comment by jerpelea** [comment] 2021-09-09 06:54
fixed in v7

**Closed by jerpelea** 2021-09-09 06:54 UTC
Labels: bug
