### ISSUE TITLE
Enforcing selinux

### ISSUE THREAD

**Issue by yshui** [sonyxperiadev/bug_tracker#589] opened 2020-05-29 19:23 UTC
Is there any plan to add support for enforcing selinux on Sony AOSP? IIUC right now Sony AOSP only runs in the permissive mode.

There seems to be some work done by custom rom developers, and they seems to have selinux enforcement on Oreo and Pie.

**Comment by MarijnS95** [comment] 2020-05-29 19:56
Hi @yshui!

This is an old decision afaik, you have to [opt-in](https://github.com/sonyxperiadev/device-sony-common/blob/a5f7f38c97f189c182c72c15ca42cec4d46d3416/CommonConfig.mk#L31-L33) by setting `BOARD_USE_ENFORCING_SELINUX := true`, usually in your customization folder/repostitory (`device/sony/customization/Customization.mk`, watch the capitalization on that file).

I doubt we'll ever change this though. Many like to build without to toy with their device or install software that cannot live with enforcing mode, but other than that we are pretty much entirely covered on the rules - I myself always run enforcing on the daily driver.
Aside from that we can only start writing and updating policy as soon as we have the blobs in our hands, which is tedious and cumbersome at the same time. So if you happen to sync during that timeframe things might break inadvertently.

**Comment by yshui** [comment] 2020-05-30 05:30
@MarijnS95 Thanks for the answer!

My impression that Enforcing doesn't work came from Oreo. I tried to enable enforcing there and that broke a lot of stuff. I had to merge rules from a custom rom to get it working.

I will try and see if enforcing works on 10.

**Comment by MarijnS95** [comment] 2020-05-30 09:08
@yshui As far as I'm aware sepolicy was maintained on Oreo too, and I [took over that duty](is:pr is:merged author:marijns95 sort:created-asc ) back when joining this project just as Pie dropped. It should all be fine now, apart a few things in ODM V7 I have yet to PR.

If you find and fix anything be sure to open a PR, but watch out for rogue apps trying to touch bits and bobs all over your system. Those are best `neverallow`ed :grin:

**Comment by yshui** [comment] 2020-05-30 18:24
@MarijnS95 _maybe_ it's causing some problem to the sensors process?

```
[  230.667443] type=1400 audit(1590861957.181:100): avc: denied { search } for comm="sensors.qcom" name="sensors" dev="sda33" ino=12 scontext=u:r:sensors:s0 tcontext=u:object_r:unlabeled:s0 tclass=dir permissive=0
[  230.667668] type=1400 audit(1590861957.182:101): avc: denied { getattr } for comm="sensors.qcom" path="/mnt/vendor/persist/sensors" dev="sda33" ino=12 scontext=u:r:sensors:s0 tcontext=u:object_r:unlabeled:s0 tclass=dir permissive=0
[  230.675052] type=1400 audit(1590861957.182:101): avc: denied { getattr } for comm="sensors.qcom" path="/mnt/vendor/persist/sensors" dev="sda33" ino=12 scontext=u:r:sensors:s0 tcontext=u:object_r:unlabeled:s0 tclass=dir permissive=0
[  230.675261] type=1400 audit(1590861957.188:102): avc: denied { search } for comm="sensors.qcom" name="sensors" dev="sda33" ino=12 scontext=u:r:sensors:s0 tcontext=u:object_r:unlabeled:s0 tclass=dir permissive=0
[  240.731535] type=1400 audit(1590861967.245:103): avc: denied { search } for comm="sensors.qcom" name="sensors" dev="sda33" ino=12 scontext=u:r:sensors:s0 tcontext=u:object_r:unlabeled:s0 tclass=dir permissive=0
[  240.731775] type=1400 audit(1590861967.245:104): avc: denied { getattr } for comm="sensors.qcom" path="/mnt/vendor/persist/sensors" dev="sda33" ino=12 scontext=u:r:sensors:s0 tcontext=u:object_r:unlabeled:s0 tclass=dir permissive=0
[  240.738660] type=1400 audit(1590861967.245:104): avc: denied { getattr } for comm="sensors.qcom" path="/mnt/vendor/persist/sensors" dev="sda33" ino=12 scontext=u:r:sensors:s0 tcontext=u:object_r:unlabeled:s0 tclass=dir permissive=0
[  240.738845] type=1400 audit(1590861967.252:105): avc: denied { search } for comm="sensors.qcom" name="sensors" dev="sda33" ino=12 scontext=u:r:sensors:s0 tcontext=u:object_r:unlabeled:s0 tclass=dir permissive=0
[  250.114399] healthd: battery l=69 v=4041 t=37.5 h=2 st=2 c=-450 fc=2820000 chg=u
[  250.782182] type=1400 audit(1590861977.296:106): avc: denied { search } for comm="sensors.qcom" name="sensors" dev="sda33" ino=12 scontext=u:r:sensors:s0 tcontext=u:object_r:unlabeled:s0 tclass=dir permissive=0
[  250.782340] type=1400 audit(1590861977.296:107): avc: denied { getattr } for comm="sensors.qcom" path="/mnt/vendor/persist/sensors" dev="sda33" ino=12 scontext=u:r:sensors:s0 tcontext=u:object_r:unlabeled:s0 tclass=dir permissive=0
[  250.797940] type=1400 audit(1590861977.296:107): avc: denied { getattr } for comm="sensors.qcom" path="/mnt/vendor/persist/sensors" dev="sda33" ino=12 scontext=u:r:sensors:s0 tcontext=u:object_r:unlabeled:s0 tclass=dir permissive=0
[  250.798711] type=1400 audit(1590861977.310:108): avc: denied { search } for comm="sensors.qcom" name="sensors" dev="sda33" ino=12 scontext=u:r:sensors:s0 tcontext=u:object_r:unlabeled:s0 tclass=dir permissive=0
[  260.871899] type=1400 audit(1590861987.386:109): avc: denied { search } for comm="sensors.qcom" name="sensors" dev="sda33" ino=12 scontext=u:r:sensors:s0 tcontext=u:object_r:unlabeled:s0 tclass=dir permissive=0
[  260.872071] type=1400 audit(1590861987.386:110): avc: denied { getattr } for comm="sensors.qcom" path="/mnt/vendor/persist/sensors" dev="sda33" ino=12 scontext=u:r:sensors:s0 tcontext=u:object_r:unlabeled:s0 tclass=dir permissive=0
[  260.878405] type=1400 audit(1590861987.386:110): avc: denied { getattr } for comm="sensors.qcom" path="/mnt/vendor/persist/sensors" dev="sda33" ino=12 scontext=u:r:sensors:s0 tcontext=u:object_r:unlabeled:s0 tclass=dir permissive=0
[  260.878592] type=1400 audit(1590861987.392:111): avc: denied { search } for comm="sensors.qcom" name="sensors" dev="sda33" ino=12 scontext=u:r:sensors:s0 tcontext=u:object_r:unlabeled:s0 tclass=dir permissive=0
[  270.923768] type=1400 audit(1590861997.437:112): avc: denied { search } for comm="sensors.qcom" name="sensors" dev="sda33" ino=12 scontext=u:r:sensors:s0 tcontext=u:object_r:unlabeled:s0 tclass=dir permissive=0
[  270.923913] type=1400 audit(1590861997.438:113): avc: denied { getattr } for comm="sensors.qcom" path="/mnt/vendor/persist/sensors" dev="sda33" ino=12 scontext=u:r:sensors:s0 tcontext=u:object_r:unlabeled:s0 tclass=dir permissive=0
[  270.927939] type=1400 audit(1590861997.438:113): avc: denied { getattr } for comm="sensors.qcom" path="/mnt/vendor/persist/sensors" dev="sda33" ino=12 scontext=u:r:sensors:s0 tcontext=u:object_r:unlabeled:s0 tclass=dir permissive=0
[  270.928137] type=1400 audit(1590861997.442:114): avc: denied { search } for comm="sensors.qcom" name="sensors" dev="sda33" ino=12 scontext=u:r:sensors:s0 tcontext=u:object_r:unlabeled:s0 tclass=dir permissive=0
[  275.626358] healthd: battery l=69 v=4043 t=37.0 h=2 st=2 c=-458 fc=2820000 chg=u
[  280.942236] init: updatable process 'vendor.sensors' exited 4 times in 4 minutes
```

**Comment by MarijnS95** [comment] 2020-05-30 18:39
@yshui Assuming you didn't run enforcing selinux before this should not have been an issue. Otherwise at least logs should indicate that it fails to read files and such.

The problem is an Android "caching"/"optimization" mechanism backfiring on us. I could explain it here but our attempt to fix it upstream explains it in much better detail:
https://android-review.googlesource.com/c/platform/system/core/+/959678

We use `restorecon_recursive` to clean up labels in the `/persist` partition, which we cannot wipe when users come from stock because it sets up stuff that we use too (at this point I/we should perhaps validate if that's still the case). This optimization prevents `restorecon_recursive` from entering directories and fixing files, leaving unknown (seen as `unlabeled`) files in the tree.

You can easily fix this manually by running `restorecon -RF /persist` from a rooted shell (`adb root`).

@ix5 and me both have patches in the works that are more aggressive at removing the optimization hash and getting the restorecon through. But it's not enough, because that script itself is _also_ enforced by sepolicy 😁 

At this point I'm _SO_ fed up with this particular sepolicy issue that we might just add their label name and grant sensors acces to it too. But other applications reading/writing `/persist` face the same issues, which is really not maintainable across 8 platforms, 20 devices, all coming from different versions of Stock.

**Comment by yshui** [comment] 2020-05-30 23:10
> restorecon -RF /persist

Will this cause problem if I go back to stock?

**Comment by MarijnS95** [comment] 2020-05-31 08:00
@yshui This is totally safe to do: when returning to stock (either through Emma or a third-party tool) `persist` is reflashed.

**Closed** 2021-04-12 10:45 UTC
Labels: enhancement

**Comment by jerpelea** [comment] 2021-04-12 10:46
permisive is a good start for development but you can locally set it to enforcing
