### ISSUE TITLE
 [yoshino][lilac] android 11: no sensor data

### ISSUE THREAD

**Issue by lada04** [sonyxperiadev/bug_tracker#710] opened 2021-08-04 22:05 UTC
**Platform: lilac** 
**Device: Xperia XZ1 Compact (aosp_g8441)** 
**Kernel version: 4.14.232-g36679be59282** 
**Android version:11** 
**Software binaries version:SW_binaries_for_Xperia_Android_11_4.14_v5b_yoshino** 

**Previously working on**
not known

**Description**
Non of the sensors is working, neither accelerometer, nor gyro, nor magnetic field sensor.

**Symptoms**
Display is not rotating automatically. Neither SatStat nor Phyphox are reporting any values.

**How to reproduce**
Open SatStat or Phyphox

**Additional context**
Screenshot from SatStat
![Screenshot_20210804-223852](https://user-images.githubusercontent.com/66674914/128261138-f3c7f96a-b894-4bcb-bba4-78ca6812d2e8.png)

**Comment by ShujathMohd** [comment] 2021-08-07 06:05
Duplicate of #699

**Comment by jerpelea** [comment] 2021-09-09 06:53
fixed in v7

**Closed by jerpelea** 2021-09-09 06:53 UTC
Labels: bug
