### ISSUE TITLE
[Yoshino] All yoshino platform devices will freeze on Pie.

### ISSUE THREAD

**Issue by sjllls** [sonyxperiadev/bug_tracker#286] opened 2018-12-26 14:46 UTC
**Platform:** Yoshino
**Device:** All yoshino platform devices
**Kernel version:** 4.9
**Android version:** 9.0
**Software Binaries version:** V4

**Description**
All yoshino platform devices will freeze on Pie after closing the screen.

**How to reproduce**
Build Rom with newest source codes and run it.

**Comment by djselbeck** [comment] 2018-12-27 07:14
Probably a duplicate of #257

**Comment by sjllls** [comment] 2019-01-05 01:18
This problem has solved on poplar, build with pre-build kernel on 2019.1.5.

@jerpelea

**Closed** 2019-01-05 01:19 UTC
